cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_BINARY_DIR OR
   NOT DEFINED FIXTURE OR NOT DEFINED PROJECT_VERSION)
  message(FATAL_ERROR "performance-report contract requires complete paths and version")
endif()
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}")
execute_process(COMMAND "${FIXTURE}" RESULT_VARIABLE fixture_status OUTPUT_VARIABLE fixture_json)
if(NOT fixture_status EQUAL 0)
  message(FATAL_ERROR "performance-report fixture failed")
endif()

foreach(mode IN ITEMS rejected accepted wrong-version)
  set(version "${PROJECT_VERSION}")
  set(matlab_limit 500000000)
  if(mode STREQUAL "rejected")
    set(matlab_limit 250000000)
  elseif(mode STREQUAL "wrong-version")
    set(version "invalid")
  endif()
  set(baseline "${TEST_BINARY_DIR}/${mode}-baseline.json")
  set(report "${TEST_BINARY_DIR}/${mode}-report.json")
  file(REMOVE "${report}")
  file(WRITE "${baseline}"
    "{\"schemaVersion\":3,\"projectVersion\":\"${version}\",\"maxLatencyNanoseconds\":1000000000,\"minThroughputBytesPerSecond\":10000,\"maxPeakArenaBytes\":67108864,\"maxGeneratedBytes\":8388608,\"matlabMaxLatencyNanoseconds\":${matlab_limit},\"matlabMinThroughputBytesPerSecond\":45000,\"matlabMaxGeneratedBytes\":1048576,\"scenarioLimits\":{}}")
  execute_process(
    COMMAND "${CMAKE_COMMAND}" "-DBENCHMARK=${FIXTURE}" "-DBASELINE=${baseline}"
      "-DREPORT=${report}" "-DPROJECT_VERSION=${PROJECT_VERSION}" -DBUILD_CONFIG=Release
      -P "${SOURCE_DIR}/cmake/verify_performance.cmake"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(mode STREQUAL "accepted")
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "valid performance report rejected: ${output}\n${error}")
    endif()
  else()
    if(status EQUAL 0)
      message(FATAL_ERROR "performance gate accepted ${mode} measurements")
    endif()
    if(mode STREQUAL "rejected" AND NOT error MATCHES "Matlab performance regression")
      message(FATAL_ERROR "performance fixture failed for the wrong reason: ${error}")
    elseif(mode STREQUAL "wrong-version" AND NOT error MATCHES "version mismatch")
      message(FATAL_ERROR "version fixture failed for the wrong reason: ${error}")
    endif()
  endif()
  if(NOT EXISTS "${report}")
    message(FATAL_ERROR "${mode} gate did not preserve its benchmark evidence")
  endif()
  file(READ "${report}" preserved)
  if(NOT preserved STREQUAL fixture_json)
    message(FATAL_ERROR "${mode} gate changed the captured benchmark measurements")
  endif()
endforeach()
