cmake_minimum_required(VERSION 3.20)

foreach(required SOURCE_DIR REFERENCE_DIR DIFFERENTIAL_RESULT SOURCE_REVISION)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Native Matlab reference verification requires ${required}")
  endif()
endforeach()
string(LENGTH "${SOURCE_REVISION}" revision_length)
if(NOT revision_length EQUAL 40 OR NOT SOURCE_REVISION MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Native Matlab reference requires a full source revision")
endif()

function(read_json output json)
  string(JSON value ERROR_VARIABLE error GET "${json}" ${ARGN})
  if(NOT error STREQUAL "NOTFOUND")
    message(FATAL_ERROR "Invalid native Matlab reference JSON: ${error}")
  endif()
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(normalize_tokens output text)
  string(REGEX REPLACE "[ \t\r\n]+" " " text "${text}")
  string(STRIP "${text}" text)
  set(${output} "${text}" PARENT_SCOPE)
endfunction()

function(check_artifact path root)
  if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "Missing native reference artifact: ${path}")
  endif()
  file(REAL_PATH "${path}" resolved)
  cmake_path(IS_PREFIX root "${resolved}" NORMALIZE owned)
  if(NOT owned)
    message(FATAL_ERROR "Native reference artifact escapes its owned build directory")
  endif()
endfunction()

function(read_result output key)
  set(found FALSE)
  foreach(line IN LISTS differential_lines)
    if(line MATCHES "^${key}=(.*)$")
      if(found)
        message(FATAL_ERROR "Duplicate generated-target result field: ${key}")
      endif()
      set(found TRUE)
      set(value "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  if(NOT found OR value STREQUAL "" OR value STREQUAL "<not-run>" OR value MATCHES "-NOTFOUND$")
    message(FATAL_ERROR "Missing executed generated-target result field: ${key}")
  endif()
  set(${output} "${value}" PARENT_SCOPE)
endfunction()

file(REAL_PATH "${SOURCE_DIR}" source_root)
file(REAL_PATH "${source_root}/build" build_root)
file(REAL_PATH "${REFERENCE_DIR}" reference_root)
cmake_path(IS_PREFIX build_root "${reference_root}" NORMALIZE under_build)
if(NOT under_build OR reference_root STREQUAL build_root)
  message(FATAL_ERROR "Native Matlab reference artifacts must remain beneath root build/")
endif()

check_artifact("${reference_root}/provenance.json" "${reference_root}")
check_artifact("${DIFFERENTIAL_RESULT}" "${build_root}")
file(READ "${reference_root}/provenance.json" provenance)
read_json(schema "${provenance}" schemaVersion)
read_json(release "${provenance}" matlabRelease)
read_json(matlab_version "${provenance}" matlabVersion)
read_json(revision "${provenance}" sourceRevision)
read_json(case_name "${provenance}" caseName)
read_json(input "${provenance}" source)
read_json(snapshot "${provenance}" sourceSnapshot)
if(NOT schema STREQUAL "1" OR NOT release STREQUAL "R2024b" OR matlab_version STREQUAL "")
  message(FATAL_ERROR "Native Matlab provenance does not identify the required R2024b runtime")
endif()
if(NOT revision STREQUAL SOURCE_REVISION)
  message(FATAL_ERROR "Native Matlab provenance revision differs from the tested source")
endif()
if(NOT case_name STREQUAL "matlab-invocation-context" OR
    NOT input STREQUAL "examples/matlab/invocation_context.m" OR
    NOT snapshot STREQUAL "source/invocation_context.m")
  message(FATAL_ERROR "Native Matlab provenance has an unexpected source inventory")
endif()
file(SHA256 "${source_root}/${input}" input_hash)
check_artifact("${reference_root}/${snapshot}" "${reference_root}")
file(SHA256 "${reference_root}/${snapshot}" snapshot_hash)
if(NOT input_hash STREQUAL snapshot_hash)
  message(FATAL_ERROR "Native Matlab source snapshot differs from the translated input")
endif()

check_artifact("${reference_root}/${case_name}.stdout" "${reference_root}")
file(READ "${reference_root}/${case_name}.stdout" native_text)
normalize_tokens(native_output "${native_text}")
if(native_output STREQUAL "")
  message(FATAL_ERROR "Native Matlab execution produced no invocation evidence")
endif()
file(STRINGS "${DIFFERENTIAL_RESULT}" differential_lines ENCODING UTF-8)
read_result(generated_case case)
read_result(generated_input input)
read_result(node node)
read_result(compiler cxx-compiler)
read_result(javascript javascript)
read_result(cpp cpp)
if(NOT generated_case STREQUAL case_name OR
    NOT generated_input STREQUAL "${source_root}/${input}")
  message(FATAL_ERROR "Generated targets did not execute the native reference source")
endif()
normalize_tokens(javascript "${javascript}")
normalize_tokens(cpp "${cpp}")
if(NOT native_output STREQUAL javascript OR NOT native_output STREQUAL cpp)
  message(FATAL_ERROR
    "R2024b/JavaScript/cpp invocation mismatch: native='${native_output}' "
    "javascript='${javascript}' cpp='${cpp}'")
endif()

check_artifact("${reference_root}/output-semantics.json" "${reference_root}")
file(READ "${reference_root}/output-semantics.json" observations)
read_json(observation_schema "${observations}" schemaVersion)
read_json(observation_release "${observations}" matlabRelease)
read_json(observation_version "${observations}" matlabVersion)
read_json(observation_revision "${observations}" sourceRevision)
if(NOT observation_schema STREQUAL "1" OR NOT observation_release STREQUAL release OR
    NOT observation_version STREQUAL matlab_version OR NOT observation_revision STREQUAL revision)
  message(FATAL_ERROR "Native output observations do not share the runtime/source provenance")
endif()
string(JSON observation_count ERROR_VARIABLE observation_error LENGTH "${observations}" cases)
set(expected_names
  conditional-one conditional-two validated-conditional-one validated-conditional-two
  missing-requested-first missing-requested-second ignored-missing-second ignored-missing-first
  ignored-count assigned-unrequested-validation assigned-discarded-validation
  missing-first-versus-second-validator first-validator-versus-second-missing
  return-outside-body-handler shared-input-output default-count-one default-count-two
  parenthesized-ans bare-ans void-ans-retained absent-ans-retained default-count-zero
  failed-output-ans restricted-default-nargout-bare restricted-default-nargout-call
  restricted-input-validator-nargout restricted-output-validator-nargout)
list(LENGTH expected_names expected_count)
if(NOT observation_error STREQUAL "NOTFOUND" OR NOT observation_count EQUAL expected_count)
  message(FATAL_ERROR "Native output observation inventory is incomplete")
endif()
file(READ "${source_root}/tests/reference/matlab/output-semantics-contract.json" contract)
read_json(contract_schema "${contract}" schemaVersion)
read_json(contract_release "${contract}" matlabRelease)
string(JSON contract_count LENGTH "${contract}" cases)
if(NOT contract_schema STREQUAL "1" OR NOT contract_release STREQUAL release OR
    NOT contract_count EQUAL expected_count)
  message(FATAL_ERROR "Native output-semantic baseline has an invalid release/inventory")
endif()
read_json(isargout "${observations}" builtinAvailability isargout)
read_json(expected_isargout "${contract}" builtinAvailability isargout)
string(JSON availability_type TYPE "${observations}" builtinAvailability isargout)
if(NOT availability_type STREQUAL "NUMBER" OR NOT isargout STREQUAL expected_isargout)
  message(FATAL_ERROR "Native builtin availability differs from the recorded R2024b baseline")
endif()
math(EXPR last "${observation_count} - 1")
foreach(index RANGE 0 ${last})
  read_json(name "${observations}" cases ${index} name)
  list(GET expected_names ${index} expected_name)
  if(NOT name STREQUAL expected_name)
    message(FATAL_ERROR "Native output observation order/name differs at ${index}")
  endif()
  read_json(succeeded "${observations}" cases ${index} succeeded)
  read_json(identifier "${observations}" cases ${index} exceptionIdentifier)
  read_json(message "${observations}" cases ${index} exceptionMessage)
  read_json(values "${observations}" cases ${index} values)
  read_json(value_class "${observations}" cases ${index} valueClass)
  read_json(value_size "${observations}" cases ${index} valueSize)
  foreach(field name valueClass exceptionIdentifier exceptionMessage)
    string(JSON field_type TYPE "${observations}" cases ${index} ${field})
    if(NOT field_type STREQUAL "STRING")
      message(FATAL_ERROR "Native output observation textual metadata must be strings")
    endif()
  endforeach()
  string(JSON size_type TYPE "${observations}" cases ${index} valueSize)
  string(JSON values_type TYPE "${observations}" cases ${index} values)
  if(NOT size_type STREQUAL "ARRAY" OR
      NOT values_type MATCHES "^(NUMBER|BOOLEAN|ARRAY)$")
    message(FATAL_ERROR "Native output observation has invalid value/size metadata")
  endif()
  string(JSON success_type TYPE "${observations}" cases ${index} succeeded)
  if(NOT success_type STREQUAL "BOOLEAN")
    message(FATAL_ERROR "Native output observation outcome must be a boolean")
  endif()
  if(succeeded)
    if(NOT identifier STREQUAL "" OR NOT message STREQUAL "" OR
        value_class STREQUAL "" OR value_size STREQUAL "[]")
      message(FATAL_ERROR "Successful native output observation has no complete value metadata")
    endif()
  elseif(identifier STREQUAL "" OR message STREQUAL "")
    message(FATAL_ERROR "Failed native output observation has no exception metadata")
  endif()
  foreach(field name succeeded values valueClass valueSize exceptionIdentifier)
    read_json(actual_value "${observations}" cases ${index} ${field})
    read_json(expected_value "${contract}" cases ${index} ${field})
    if(NOT actual_value STREQUAL expected_value)
      message(FATAL_ERROR
        "Native output semantic differs from the recorded R2024b baseline: ${name}/${field}")
    endif()
  endforeach()
  read_json(expected_message "${contract}" cases ${index} exceptionMessageContains)
  string(FIND "${message}" "${expected_message}" message_position)
  if(message_position LESS 0)
    message(FATAL_ERROR
      "Native exception ordering/message differs from the recorded R2024b baseline: ${name}")
  endif()
endforeach()
message(STATUS "Verified R2024b reference provenance/snapshot and both target results on ${revision}")
message(STATUS "Checked ${observation_count} native output observations; pending MPF parity is not implied")
