cmake_minimum_required(VERSION 3.20)

foreach(required SOURCE_DIR TEST_BINARY_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Matlab reference verifier contract requires ${required}")
  endif()
endforeach()
if(NOT DEFINED REFERENCE_CONTRACT_SECTION)
  set(REFERENCE_CONTRACT_SECTION core)
endif()
if(NOT REFERENCE_CONTRACT_SECTION MATCHES "^(core|empty-validators)$")
  message(FATAL_ERROR "Unknown native-reference contract section")
endif()
file(REAL_PATH "${SOURCE_DIR}" SOURCE_DIR)
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/synthetic evidence")
set(reference "${TEST_BINARY_DIR}/synthetic evidence")
set(snapshot "source/invocation_context.m")
set(case_name matlab-invocation-context)
string(REPEAT a 40 revision)
set(provenance "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"matlabVersion\":\"synthetic verifier fixture, not runtime evidence\","
  "\"sourceRevision\":\"${revision}\",\"caseName\":\"${case_name}\","
  "\"source\":\"examples/matlab/invocation_context.m\","
  "\"sourceSnapshot\":\"${snapshot}\"}")
string(JOIN "" provenance ${provenance})
set(names
  conditional-one conditional-two validated-conditional-one validated-conditional-two
  missing-requested-first missing-requested-second ignored-missing-second ignored-missing-first
  ignored-count assigned-unrequested-validation assigned-discarded-validation
  missing-first-versus-second-validator first-validator-versus-second-missing
  return-outside-body-handler shared-input-output default-count-one default-count-two
  parenthesized-ans bare-ans void-ans-retained absent-ans-retained default-count-zero
  failed-output-ans restricted-default-nargout-bare restricted-default-nargout-call
  restricted-input-validator-nargout restricted-output-validator-nargout)
file(READ "${SOURCE_DIR}/tests/reference/matlab/output-semantics-contract.json" contract)
string(JSON cases GET "${contract}" cases)
list(LENGTH names case_count)
math(EXPR last "${case_count} - 1")
foreach(index RANGE 0 ${last})
  string(JSON message GET "${cases}" ${index} exceptionMessageContains)
  string(JSON succeeded GET "${cases}" ${index} succeeded)
  if(NOT succeeded)
    string(APPEND message " Synthetic verifier fixture; not a MATLAB execution.")
  endif()
  string(REPLACE "\\" "\\\\" message "${message}")
  string(REPLACE "\"" "\\\"" message "${message}")
  string(JSON cases REMOVE "${cases}" ${index} exceptionMessageContains)
  string(JSON cases SET "${cases}" ${index} exceptionMessage "\"${message}\"")
endforeach()
set(observations "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"matlabVersion\":\"synthetic verifier fixture, not runtime evidence\","
  "\"sourceRevision\":\"${revision}\",\"builtinAvailability\":{\"isargout\":0},"
  "\"cases\":${cases}}")
string(JOIN "" observations ${observations})
set(result "case=${case_name}\ninput=${SOURCE_DIR}/examples/matlab/invocation_context.m\n"
  "node=synthetic-node\ncxx-compiler=synthetic-compiler\n"
  "javascript=1 2\ncpp=1 2\n")
string(JOIN "" result ${result})
set(result_file "${TEST_BINARY_DIR}/synthetic-target-result.txt")

# Structural verifier fixtures are not a MATLAB execution or target parity evidence.
file(READ "${SOURCE_DIR}/tests/reference/matlab/validator-semantics-contract.json" validator_contract)
string(JSON validator_cases GET "${validator_contract}" cases)
string(JSON validator_count LENGTH "${validator_cases}")
math(EXPR validator_last "${validator_count} - 1")
foreach(index RANGE 0 ${validator_last})
  string(JSON message GET "${validator_cases}" ${index} exceptionMessageContains)
  string(JSON success GET "${validator_cases}" ${index} succeeded)
  if(NOT success)
    string(APPEND message " Synthetic verifier fixture; not a MATLAB execution.")
  endif()
  string(REPLACE "\\" "\\\\" message "${message}")
  string(REPLACE "\"" "\\\"" message "${message}")
  string(JSON validator_cases REMOVE "${validator_cases}" ${index} exceptionMessageContains)
  string(JSON validator_cases SET "${validator_cases}" ${index} exceptionMessage "\"${message}\"")
endforeach()
set(validator_observations "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"matlabVersion\":\"synthetic verifier fixture, not runtime evidence\","
  "\"sourceRevision\":\"${revision}\",\"cases\":${validator_cases}}")
string(JOIN "" validator_observations ${validator_observations})
file(READ "${SOURCE_DIR}/tests/reference/matlab/empty-validator-semantics-contract.json"
  empty_validator_contract)
foreach(matrix emptyCharacter emptyNumeric)
  string(JSON empty_cases GET "${empty_validator_contract}" "${matrix}")
  string(JSON empty_count LENGTH "${empty_cases}")
  math(EXPR empty_last "${empty_count} - 1")
  foreach(index RANGE 0 ${empty_last})
    string(JSON message GET "${empty_cases}" ${index} exceptionMessageContains)
    string(JSON success GET "${empty_cases}" ${index} succeeded)
    if(NOT success)
      string(APPEND message " Synthetic verifier fixture; not a MATLAB execution.")
    endif()
    string(REPLACE "\\" "\\\\" message "${message}")
    string(REPLACE "\"" "\\\"" message "${message}")
    string(JSON empty_cases REMOVE "${empty_cases}" ${index} exceptionMessageContains)
    string(JSON empty_cases SET "${empty_cases}" ${index} exceptionMessage "\"${message}\"")
  endforeach()
  string(JSON validator_observations SET "${validator_observations}" "${matrix}" "${empty_cases}")
endforeach()
set(validator_parity_provenance "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"matlabVersion\":\"synthetic verifier fixture, not runtime evidence\","
  "\"sourceRevision\":\"${revision}\",\"caseName\":\"matlab-validator-identities\","
  "\"source\":\"tests/fixtures/matlab_validator_exception_identity.m\","
  "\"sourceSnapshot\":\"source/matlab_validator_exception_identity.m\"}")
string(JOIN "" validator_parity_provenance ${validator_parity_provenance})
foreach(index RANGE 0 ${validator_last})
  string(JSON name GET "${validator_cases}" ${index} name)
  string(JSON identifier GET "${validator_cases}" ${index} exceptionIdentifier)
  set(expected_${name} "${identifier}")
endforeach()
set(validator_keys
  numeric numeric_or_logical floating real finite
  non_nan positive nonpositive nonnegative negative
  nonzero integer nonempty scalar_or_empty vector
  row column matrix nonmissing nonzero_length_text
  text text_scalar valid_variable_name greater_than greater_than_or_equal
  less_than less_than_or_equal in_range positive-complex positive-text
  integer-complex integer-text valid-variable-name-type greater-than-complex greater-than-text
  nonzero-length-text-empty-double range-exclusive range-exclude-lower range-exclude-upper
)
set(validator_tokens)
foreach(key IN LISTS validator_keys)
  foreach(context input output)
    list(APPEND validator_tokens "${expected_${key}-${context}}")
  endforeach()
endforeach()
list(APPEND validator_tokens accepted-text accepted-text
  "${expected_numeric-input}" "${expected_numeric-output}")
foreach(matrix emptyCharacter emptyNumeric)
  string(JSON empty_cases GET "${validator_observations}" "${matrix}")
  string(JSON empty_count LENGTH "${empty_cases}")
  math(EXPR empty_last "${empty_count} - 1")
  foreach(index RANGE 0 ${empty_last})
    string(JSON context GET "${empty_cases}" ${index} context)
    if(context STREQUAL "direct")
      continue()
    endif()
    string(JSON success GET "${empty_cases}" ${index} succeeded)
    string(JSON identifier GET "${empty_cases}" ${index} exceptionIdentifier)
    if(success)
      list(APPEND validator_tokens accepted-empty)
    else()
      list(APPEND validator_tokens "${identifier}")
    endif()
  endforeach()
endforeach()
string(JOIN " " validator_stdout ${validator_tokens})
set(validator_result "case=matlab-validator-identities\n"
  "input=${SOURCE_DIR}/tests/fixtures/matlab_validator_exception_identity.m\n"
  "node=synthetic-node\ncxx-compiler=synthetic-compiler\n"
  "javascript=${validator_stdout}\ncpp=${validator_stdout}\n")
string(JOIN "" validator_result ${validator_result})
set(validator_result_file "${TEST_BINARY_DIR}/synthetic-validator-target-result.txt")

function(reset_fixture)
  file(WRITE "${reference}/provenance.json" "${provenance}")
  file(WRITE "${reference}/output-semantics.json" "${observations}")
  file(WRITE "${reference}/validator-semantics.json" "${validator_observations}")
  file(WRITE "${reference}/validator-parity-provenance.json" "${validator_parity_provenance}")
  file(WRITE "${reference}/matlab-validator-identities.stdout" "${validator_stdout}\n")
  file(WRITE "${reference}/${case_name}.stdout" "1\r\n   2\n")
  file(MAKE_DIRECTORY "${reference}/source")
  file(REMOVE "${reference}/${snapshot}")
  configure_file("${SOURCE_DIR}/examples/matlab/invocation_context.m"
    "${reference}/${snapshot}" COPYONLY)
  file(REMOVE "${reference}/source/matlab_validator_exception_identity.m")
  configure_file("${SOURCE_DIR}/tests/fixtures/matlab_validator_exception_identity.m"
    "${reference}/source/matlab_validator_exception_identity.m" COPYONLY)
  file(WRITE "${result_file}" "${result}")
  file(WRITE "${validator_result_file}" "${validator_result}")
endfunction()

function(check_fixture expected diagnostic)
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DSOURCE_DIR=${SOURCE_DIR}" "-DREFERENCE_DIR=${reference}"
    "-DDIFFERENTIAL_RESULT=${result_file}" "-DSOURCE_REVISION=${revision}"
    "-DVALIDATOR_DIFFERENTIAL_RESULT=${validator_result_file}"
    -P "${SOURCE_DIR}/tests/cmake/verify_matlab_reference.cmake"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected STREQUAL "success")
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Synthetic positive verifier fixture failed: ${output}${error}")
    endif()
  elseif(status EQUAL 0)
    message(FATAL_ERROR "Corrupted native reference fixture was accepted: ${diagnostic}")
  else()
    string(REGEX REPLACE "[ \t\r\n]+" " " normalized "${output}${error}")
    if(NOT normalized MATCHES "${diagnostic}")
      message(FATAL_ERROR "Verifier failed for the wrong reason: ${output}${error}")
    endif()
  endif()
endfunction()

reset_fixture()
check_fixture(success "")
if(REFERENCE_CONTRACT_SECTION STREQUAL "core")
  string(JSON observed_failure SET "${observations}" cases 9 exceptionMessage
    "\"Invalid output 'second'. Another synthetic error record; not a MATLAB execution.\"")
  file(WRITE "${reference}/output-semantics.json" "${observed_failure}")
  check_fixture(success "")
  reset_fixture()
  string(REPLACE "\"R2024b\"" "\"R2024a\"" invalid "${provenance}")
  file(WRITE "${reference}/provenance.json" "${invalid}")
  check_fixture(failure "required R2024b runtime")
  reset_fixture()
  string(REPEAT b 40 wrong_revision)
  string(REPLACE "${revision}" "${wrong_revision}" invalid "${provenance}")
  file(WRITE "${reference}/provenance.json" "${invalid}")
  check_fixture(failure "revision differs")
  reset_fixture()
  string(REPLACE "\"${snapshot}\"" "\"../outside.m\"" invalid "${provenance}")
  file(WRITE "${reference}/provenance.json" "${invalid}")
  check_fixture(failure "unexpected source inventory")
  reset_fixture()
  file(APPEND "${reference}/${snapshot}" "\n% modified snapshot\n")
  check_fixture(failure "snapshot differs")
  reset_fixture()
  file(WRITE "${reference}/${case_name}.stdout"
    "Warning: Function transpose has the same name as a MATLAB built-in.\n1 2\n")
  check_fixture(failure "invocation mismatch")
  reset_fixture()
  file(WRITE "${reference}/${case_name}.stdout" "1 3")
  check_fixture(failure "invocation mismatch")
  reset_fixture()
  string(REPLACE "cpp=1 2" "cpp=1 3" invalid "${result}")
  file(WRITE "${result_file}" "${invalid}")
  check_fixture(failure "invocation mismatch")
  reset_fixture()
  string(REPLACE "node=synthetic-node" "node=node-NOTFOUND" invalid "${result}")
  file(WRITE "${result_file}" "${invalid}")
  check_fixture(failure "Missing executed generated-target")
  reset_fixture()
  file(APPEND "${result_file}" "javascript=1 2\n")
  check_fixture(failure "Duplicate generated-target")
  reset_fixture()
  string(REPLACE "case=${case_name}" "case=wrong-case" invalid "${result}")
  file(WRITE "${result_file}" "${invalid}")
  check_fixture(failure "did not execute the native reference source")
  reset_fixture()
  string(REPLACE "\"R2024b\"" "\"R2024a\"" invalid "${observations}")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "do not share")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases "[]")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "inventory is incomplete")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 0 name "\"wrong-observation\"")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "order/name differs")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 0 succeeded "1")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "outcome must be a boolean")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 0 succeeded "false")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "no exception metadata")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 0 valueClass "\"\"")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "no complete value metadata")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 0 exceptionMessage "42")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "textual metadata must be strings")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 0 valueSize "42")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "invalid value/size metadata")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 17 values "1")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "Native output semantic differs")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 6 exceptionIdentifier
    "\"MATLAB:validators:mustBePositive\"")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "Native output semantic differs")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 11 exceptionMessage
    "\"Invalid output 'first'. Synthetic wrong ordering.\"")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "Native exception ordering/message differs")
  reset_fixture()
  string(JSON invalid SET "${observations}" builtinAvailability isargout "5")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "Native builtin availability differs")
  reset_fixture()
  string(JSON invalid SET "${observations}" matlabVersion "\"foreign-runtime-version\"")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "do not share")
  reset_fixture()
  string(JSON invalid SET "${observations}" cases 6 succeeded "true")
  string(JSON invalid SET "${invalid}" cases 6 values "1")
  string(JSON invalid SET "${invalid}" cases 6 valueClass "\"double\"")
  string(JSON invalid SET "${invalid}" cases 6 valueSize "[1,1]")
  string(JSON invalid SET "${invalid}" cases 6 exceptionIdentifier "\"\"")
  string(JSON invalid SET "${invalid}" cases 6 exceptionMessage "\"\"")
  file(WRITE "${reference}/output-semantics.json" "${invalid}")
  check_fixture(failure "Native output semantic differs")
  reset_fixture()
  file(WRITE "${reference}/provenance.json" "{invalid")
  check_fixture(failure "Invalid native Matlab reference JSON")
  reset_fixture()
  file(REMOVE "${reference}/provenance.json")
  check_fixture(failure "Missing native reference artifact")
  reset_fixture()
  set(outside_copy "${TEST_BINARY_DIR}/outside-reference.m")
  configure_file("${SOURCE_DIR}/examples/matlab/invocation_context.m" "${outside_copy}" COPYONLY)
  file(REMOVE "${reference}/${snapshot}")
  file(CREATE_LINK "${outside_copy}" "${reference}/${snapshot}" SYMBOLIC RESULT link_status)
  if(link_status STREQUAL "0")
    check_fixture(failure "escapes its owned build directory")
  else()
    message(STATUS "Reference snapshot symlink fixture unavailable: ${link_status}")
  endif()
  reset_fixture()
  file(REMOVE "${reference}/validator-semantics.json")
  check_fixture(failure "Missing native reference artifact")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" sourceRevision "\"wrong-revision\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "validator revision differs")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" cases 0 succeeded "\"false\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "outcome/cause metadata has invalid types")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" cases 0 exceptionIdentifier "\"MPF:TypeError\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "no complete native exception")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" cases 84 exceptionIdentifier
    "\"MATLAB:validators:mustBePositive\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "differs from the R2024b baseline")
  reset_fixture()
  string(JSON invalid REMOVE "${validator_observations}" cases 0)
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "observation inventory is incomplete")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" cases 2 exceptionMessage "\"Wrong output context\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "exception context/message differs")
  reset_fixture()
  file(APPEND "${reference}/source/matlab_validator_exception_identity.m" "\n% corrupted snapshot\n")
  check_fixture(failure "validator source snapshot differs")
  reset_fixture()
  string(JSON invalid SET "${validator_parity_provenance}" caseName "\"wrong-case\"")
  file(WRITE "${reference}/validator-parity-provenance.json" "${invalid}")
  check_fixture(failure "invalid runtime/revision/source provenance")
  reset_fixture()
  file(WRITE "${reference}/matlab-validator-identities.stdout" "MATLAB:validators:mustBePositive")
  check_fixture(failure "fixture output differs")
  reset_fixture()
  string(REPLACE "javascript=${validator_stdout}" "javascript=wrong-output" invalid "${validator_result}")
  file(WRITE "${validator_result_file}" "${invalid}")
  check_fixture(failure "validator identity execution mismatch")
  reset_fixture()
  string(REPLACE "case=matlab-validator-identities" "case=wrong-source" invalid "${validator_result}")
  file(WRITE "${validator_result_file}" "${invalid}")
  check_fixture(failure "did not execute the native validator source")
  reset_fixture()
  file(APPEND "${validator_result_file}" "cpp=duplicate\n")
  check_fixture(failure "Duplicate generated-target result field")
  message(STATUS "Verified synthetic core native-reference fixtures; no MATLAB execution claim")
  return()
endif()
foreach(matrix emptyCharacter emptyNumeric)
  reset_fixture()
  string(JSON invalid REMOVE "${validator_observations}" "${matrix}")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator inventory is incomplete")
  reset_fixture()
  string(JSON invalid REMOVE "${validator_observations}" "${matrix}" 0)
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator inventory is incomplete")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" "${matrix}" 0 succeeded "\"false\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator outcome must be a boolean")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" "${matrix}" 0 name "\"other-case\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator order/identity differs")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" "${matrix}" 0 validator "\"mustBeRow\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator differs from R2024b")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" "${matrix}" 0 causeIdentifiers "false")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator causes must be an array")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" "${matrix}" 45 exceptionMessage
    "\"Synthetic error with missing input/output context\"")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator exception context/message differs")
  reset_fixture()
  string(JSON invalid SET "${validator_observations}" "${matrix}" 45 succeeded "true")
  file(WRITE "${reference}/validator-semantics.json" "${invalid}")
  check_fixture(failure "empty-validator differs from R2024b")
endforeach()
reset_fixture()
string(JSON invalid SET "${validator_observations}" emptyNumeric 0 exceptionMessage
  "\"Successful empty numeric value retained a synthetic exception\"")
file(WRITE "${reference}/validator-semantics.json" "${invalid}")
check_fixture(failure "Successful native empty-validator retains an exception")
reset_fixture()
string(JSON invalid SET "${validator_observations}" emptyCharacter 46 exceptionIdentifier
  "\"MATLAB:validators:mustBeVector\"")
file(WRITE "${reference}/validator-semantics.json" "${invalid}")
check_fixture(failure "empty-validator differs from R2024b")
message(STATUS "Verified synthetic native-reference contract fixtures; no MATLAB execution claim")
