cmake_minimum_required(VERSION 3.20)

foreach(required SOURCE_DIR TEST_BINARY_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Matlab reference verifier contract requires ${required}")
  endif()
endforeach()
file(REAL_PATH "${SOURCE_DIR}" SOURCE_DIR)
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/synthetic evidence")
set(reference "${TEST_BINARY_DIR}/synthetic evidence")
set(case_name matlab-invocation-context)
string(REPEAT a 40 revision)
set(provenance "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"matlabVersion\":\"synthetic verifier fixture, not runtime evidence\","
  "\"sourceRevision\":\"${revision}\",\"caseName\":\"${case_name}\","
  "\"source\":\"examples/matlab/invocation_context.m\","
  "\"sourceSnapshot\":\"${case_name}.m\"}")
string(JOIN "" provenance ${provenance})
set(names
  conditional-one conditional-two validated-conditional-one validated-conditional-two
  missing-requested-first missing-requested-second ignored-missing-second ignored-missing-first
  ignored-count assigned-unrequested-validation assigned-discarded-validation
  missing-first-versus-second-validator first-validator-versus-second-missing
  return-outside-body-handler shared-input-output default-count-one default-count-two
  parenthesized-ans bare-ans void-ans-retained absent-ans-retained default-count-zero
  failed-output-ans)
set(cases "")
foreach(name IN LISTS names)
  if(NOT cases STREQUAL "")
    string(APPEND cases ",")
  endif()
  string(APPEND cases
    "{\"name\":\"${name}\",\"succeeded\":true,\"values\":1,"
    "\"valueClass\":\"double\",\"valueSize\":[1,1],"
    "\"exceptionIdentifier\":\"\",\"exceptionMessage\":\"\"}")
endforeach()
set(observations "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"sourceRevision\":\"${revision}\",\"cases\":[${cases}]}")
string(JOIN "" observations ${observations})
set(result "case=${case_name}\ninput=${SOURCE_DIR}/examples/matlab/invocation_context.m\n"
  "node=synthetic-node\ncxx-compiler=synthetic-compiler\n"
  "javascript=1 2\ncpp=1 2\n")
string(JOIN "" result ${result})
set(result_file "${TEST_BINARY_DIR}/synthetic-target-result.txt")

function(reset_fixture)
  file(WRITE "${reference}/provenance.json" "${provenance}")
  file(WRITE "${reference}/output-semantics.json" "${observations}")
  file(WRITE "${reference}/${case_name}.stdout" "1\r\n   2\n")
  file(REMOVE "${reference}/${case_name}.m")
  configure_file("${SOURCE_DIR}/examples/matlab/invocation_context.m"
    "${reference}/${case_name}.m" COPYONLY)
  file(WRITE "${result_file}" "${result}")
endfunction()

function(check_fixture expected diagnostic)
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DSOURCE_DIR=${SOURCE_DIR}" "-DREFERENCE_DIR=${reference}"
    "-DDIFFERENTIAL_RESULT=${result_file}" "-DSOURCE_REVISION=${revision}"
    -P "${SOURCE_DIR}/tests/cmake/verify_matlab_reference.cmake"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected STREQUAL "success")
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Synthetic positive verifier fixture failed: ${output}${error}")
    endif()
  elseif(status EQUAL 0)
    message(FATAL_ERROR "Corrupted native reference fixture was accepted: ${diagnostic}")
  else()
    string(REGEX REPLACE "[ \t\r\n]+" " " normalized "${output}${error}")
    if(NOT normalized MATCHES "${diagnostic}")
      message(FATAL_ERROR "Verifier failed for the wrong reason: ${output}${error}")
    endif()
  endif()
endfunction()

reset_fixture()
check_fixture(success "")
string(JSON observed_failure SET "${observations}" cases 0 succeeded "false")
string(JSON observed_failure SET "${observed_failure}" cases 0 exceptionIdentifier
  "\"MATLAB:syntheticVerifierFixture\"")
string(JSON observed_failure SET "${observed_failure}" cases 0 exceptionMessage
  "\"synthetic error record; not an observed MATLAB exception\"")
string(JSON observed_failure SET "${observed_failure}" cases 0 values "[]")
string(JSON observed_failure SET "${observed_failure}" cases 0 valueClass "\"\"")
string(JSON observed_failure SET "${observed_failure}" cases 0 valueSize "[]")
file(WRITE "${reference}/output-semantics.json" "${observed_failure}")
check_fixture(success "")
reset_fixture()
string(REPLACE "\"R2024b\"" "\"R2024a\"" invalid "${provenance}")
file(WRITE "${reference}/provenance.json" "${invalid}")
check_fixture(failure "required R2024b runtime")
reset_fixture()
string(REPEAT b 40 wrong_revision)
string(REPLACE "${revision}" "${wrong_revision}" invalid "${provenance}")
file(WRITE "${reference}/provenance.json" "${invalid}")
check_fixture(failure "revision differs")
reset_fixture()
string(REPLACE "\"matlab-invocation-context.m\"" "\"../outside.m\"" invalid "${provenance}")
file(WRITE "${reference}/provenance.json" "${invalid}")
check_fixture(failure "unexpected source inventory")
reset_fixture()
file(APPEND "${reference}/${case_name}.m" "\n% modified snapshot\n")
check_fixture(failure "snapshot differs")
reset_fixture()
file(WRITE "${reference}/${case_name}.stdout" "1 3")
check_fixture(failure "invocation mismatch")
reset_fixture()
string(REPLACE "cpp=1 2" "cpp=1 3" invalid "${result}")
file(WRITE "${result_file}" "${invalid}")
check_fixture(failure "invocation mismatch")
reset_fixture()
string(REPLACE "node=synthetic-node" "node=node-NOTFOUND" invalid "${result}")
file(WRITE "${result_file}" "${invalid}")
check_fixture(failure "Missing executed generated-target")
reset_fixture()
file(APPEND "${result_file}" "javascript=1 2\n")
check_fixture(failure "Duplicate generated-target")
reset_fixture()
string(REPLACE "case=${case_name}" "case=wrong-case" invalid "${result}")
file(WRITE "${result_file}" "${invalid}")
check_fixture(failure "did not execute the native reference source")
reset_fixture()
string(REPLACE "\"R2024b\"" "\"R2024a\"" invalid "${observations}")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "do not share")
reset_fixture()
string(JSON invalid SET "${observations}" cases "[]")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "inventory is incomplete")
reset_fixture()
string(JSON invalid SET "${observations}" cases 0 name "\"wrong-observation\"")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "order/name differs")
reset_fixture()
string(JSON invalid SET "${observations}" cases 0 succeeded "1")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "outcome must be a boolean")
reset_fixture()
string(JSON invalid SET "${observations}" cases 0 succeeded "false")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "no exception metadata")
reset_fixture()
string(JSON invalid SET "${observations}" cases 0 valueClass "\"\"")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "no complete value metadata")
reset_fixture()
string(JSON invalid SET "${observations}" cases 0 exceptionMessage "42")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "textual metadata must be strings")
reset_fixture()
string(JSON invalid SET "${observations}" cases 0 valueSize "42")
file(WRITE "${reference}/output-semantics.json" "${invalid}")
check_fixture(failure "invalid value/size metadata")
reset_fixture()
file(WRITE "${reference}/provenance.json" "{invalid")
check_fixture(failure "Invalid native Matlab reference JSON")
reset_fixture()
file(REMOVE "${reference}/provenance.json")
check_fixture(failure "Missing native reference artifact")
reset_fixture()
set(outside_copy "${TEST_BINARY_DIR}/outside-reference.m")
configure_file("${SOURCE_DIR}/examples/matlab/invocation_context.m" "${outside_copy}" COPYONLY)
file(REMOVE "${reference}/${case_name}.m")
file(CREATE_LINK "${outside_copy}" "${reference}/${case_name}.m" SYMBOLIC RESULT link_status)
if(link_status STREQUAL "0")
  check_fixture(failure "escapes its owned build directory")
else()
  message(STATUS "Reference snapshot symlink fixture unavailable: ${link_status}")
endif()
message(STATUS "Verified synthetic native-reference contract fixtures; no MATLAB execution claim")
