cmake_minimum_required(VERSION 3.20)

foreach(required SOURCE_DIR REFERENCE_DIR SOURCE_REVISION ARRAY_RESULT VALUE_RESULT SPACING_RESULT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "native control-join parity requires ${required}")
  endif()
endforeach()
string(LENGTH "${SOURCE_REVISION}" revision_length)
if(NOT revision_length EQUAL 40 OR NOT SOURCE_REVISION MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "native control-join parity requires the full tested source SHA")
endif()
file(REAL_PATH "${SOURCE_DIR}" source_root)
file(REAL_PATH "${source_root}/build" build_root)
file(REAL_PATH "${REFERENCE_DIR}" reference_root)
cmake_path(IS_PREFIX build_root "${reference_root}" NORMALIZE owned)
if(NOT owned OR reference_root STREQUAL build_root)
  message(FATAL_ERROR "native control-join evidence must be beneath root build/")
endif()
function(require_artifact path root)
  if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
    message(FATAL_ERROR "missing native control-join artifact: ${path}")
  endif()
  file(REAL_PATH "${path}" resolved)
  cmake_path(IS_PREFIX root "${resolved}" NORMALIZE owned)
  if(NOT owned)
    message(FATAL_ERROR "native control-join artifact escapes its evidence directory")
  endif()
endfunction()
function(read_field output key)
  set(found FALSE)
  foreach(line IN LISTS result_lines)
    if(line MATCHES "^${key}=(.*)$")
      if(found)
        message(FATAL_ERROR "duplicate control-join target result field: ${key}")
      endif()
      set(found TRUE)
      set(value "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  if(NOT found OR value STREQUAL "" OR value STREQUAL "<not-run>" OR value MATCHES "-NOTFOUND$")
    message(FATAL_ERROR "missing executed control-join target field: ${key}")
  endif()
  set(${output} "${value}" PARENT_SCOPE)
endfunction()
function(normalize output value)
  string(REGEX REPLACE "[ \t\r\n]+" " " value "${value}")
  string(STRIP "${value}" value)
  set(${output} "${value}" PARENT_SCOPE)
endfunction()
require_artifact("${reference_root}/control-join-parity.json" "${reference_root}")
file(READ "${reference_root}/control-join-parity.json" provenance)
foreach(field schemaVersion matlabRelease matlabVersion sourceRevision cases)
  string(JSON field_type TYPE "${provenance}" ${field})
  if(field STREQUAL "schemaVersion")
    set(expected_type NUMBER)
  elseif(field STREQUAL "cases")
    set(expected_type ARRAY)
  else()
    set(expected_type STRING)
  endif()
  if(NOT field_type STREQUAL expected_type)
    message(FATAL_ERROR "native control-join metadata has an invalid type: ${field}")
  endif()
endforeach()
string(JSON schema GET "${provenance}" schemaVersion)
string(JSON release GET "${provenance}" matlabRelease)
string(JSON version GET "${provenance}" matlabVersion)
string(JSON revision GET "${provenance}" sourceRevision)
string(JSON count LENGTH "${provenance}" cases)
if(NOT schema STREQUAL "1" OR NOT release STREQUAL "R2024b" OR version STREQUAL "" OR
   NOT revision STREQUAL SOURCE_REVISION OR NOT count EQUAL 3)
  message(FATAL_ERROR "native control-join runtime/revision/inventory does not match")
endif()
set(names matlab-mutable-array-joins matlab-mutable-value-joins matlab-matrix-expression-spacing)
set(sources examples/matlab/mutable_array_joins.m tests/fixtures/matlab_mutable_value_joins.m
  examples/matlab/matrix_expression_spacing.m)
set(results "${ARRAY_RESULT}" "${VALUE_RESULT}" "${SPACING_RESULT}")
foreach(index RANGE 0 2)
  list(GET names ${index} expected_name)
  list(GET sources ${index} expected_source)
  list(GET results ${index} target_result)
  string(JSON case GET "${provenance}" cases ${index})
  foreach(field caseName source sourceSnapshot)
    string(JSON field_type TYPE "${case}" ${field})
    if(NOT field_type STREQUAL "STRING")
      message(FATAL_ERROR "native control-join source metadata must be strings")
    endif()
  endforeach()
  string(JSON name GET "${case}" caseName)
  string(JSON source GET "${case}" source)
  string(JSON snapshot GET "${case}" sourceSnapshot)
  get_filename_component(basename "${expected_source}" NAME)
  if(NOT name STREQUAL expected_name OR NOT source STREQUAL expected_source OR
     NOT snapshot STREQUAL "source/${basename}")
    message(FATAL_ERROR "native control-join source inventory differs at ${index}")
  endif()
  require_artifact("${reference_root}/${snapshot}" "${reference_root}")
  file(SHA256 "${source_root}/${source}" source_hash)
  file(SHA256 "${reference_root}/${snapshot}" snapshot_hash)
  if(NOT source_hash STREQUAL snapshot_hash)
    message(FATAL_ERROR "native control-join source snapshot is not byte-identical")
  endif()
  require_artifact("${reference_root}/${name}.stdout" "${reference_root}")
  require_artifact("${target_result}" "${build_root}")
  file(READ "${reference_root}/${name}.stdout" native_text)
  normalize(native "${native_text}")
  if(native STREQUAL "")
    message(FATAL_ERROR "native control-join execution produced no output")
  endif()
  file(STRINGS "${target_result}" result_lines ENCODING UTF-8)
  read_field(actual_case case)
  read_field(input input)
  read_field(node node)
  read_field(javascript javascript)
  read_field(cpp cpp)
  if(NOT actual_case STREQUAL name OR NOT input STREQUAL "${source_root}/${source}")
    message(FATAL_ERROR "control-join target execution has a different source")
  endif()
  normalize(javascript "${javascript}")
  if(NOT native STREQUAL javascript)
    message(FATAL_ERROR "R2024b/JavaScript control-join mismatch for ${name}")
  endif()
  if(index EQUAL 1)
    if(NOT cpp STREQUAL "MPF2007")
      message(FATAL_ERROR "mixed values lost their independent C++ capability boundary")
    endif()
    get_filename_component(target_directory "${target_result}" DIRECTORY)
    require_artifact("${target_directory}/cpp-diagnostics.json" "${build_root}")
    file(READ "${target_directory}/cpp-diagnostics.json" diagnostics)
    string(JSON diagnostic_count LENGTH "${diagnostics}" diagnostics)
    if(diagnostic_count LESS 1)
      message(FATAL_ERROR "C++ capability rejection has no diagnostic")
    endif()
    math(EXPR last "${diagnostic_count} - 1")
    set(capability FALSE)
    foreach(item RANGE 0 ${last})
      string(JSON code GET "${diagnostics}" diagnostics ${item} code)
      string(JSON diagnostic_source GET "${diagnostics}" diagnostics ${item} source)
      if(NOT diagnostic_source STREQUAL input OR code STREQUAL "MPF0006")
        message(FATAL_ERROR "C++ rejected mixed values at the wrong compilation boundary")
      endif()
      if(code STREQUAL "MPF2007")
        set(capability TRUE)
      endif()
    endforeach()
    if(NOT capability)
      message(FATAL_ERROR "C++ rejection has no target capability error")
    endif()
  else()
    read_field(compiler cxx-compiler)
    normalize(cpp "${cpp}")
    if(NOT native STREQUAL cpp)
      message(FATAL_ERROR "R2024b/cpp control-join mismatch for ${name}")
    endif()
  endif()
endforeach()
message(STATUS "R2024b mutable joins/matrix whitespace, snapshot provenance and target parity verified")
