cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED CTEST_COMMAND OR NOT DEFINED PROJECT_BUILD_DIR OR NOT DEFINED CONFIG)
  message(FATAL_ERROR "nested-build budget test is missing required arguments")
endif()

execute_process(
  COMMAND "${CTEST_COMMAND}" --test-dir "${PROJECT_BUILD_DIR}" -C "${CONFIG}"
    --show-only=json-v1
  RESULT_VARIABLE inspection_result
  OUTPUT_VARIABLE inventory
  ERROR_VARIABLE inspection_error)
if(NOT inspection_result EQUAL 0)
  message(FATAL_ERROR "test inventory inspection failed: ${inspection_error}")
endif()

set(expected_names javascript-only cpp-only core-only)
string(JSON test_count LENGTH "${inventory}" tests)
math(EXPR last_test "${test_count} - 1")
foreach(index RANGE 0 ${last_test})
  string(JSON name GET "${inventory}" tests ${index} name)
  if(NOT name MATCHES "^mpf\\.backend-isolation\\.(.+)$")
    continue()
  endif()
  set(variant "${CMAKE_MATCH_1}")
  if(NOT variant IN_LIST expected_names)
    message(FATAL_ERROR "unexpected or duplicate isolation test: ${name}")
  endif()
  list(REMOVE_ITEM expected_names "${variant}")

  set(processors "")
  set(timeout "")
  string(JSON property_count LENGTH "${inventory}" tests ${index} properties)
  math(EXPR last_property "${property_count} - 1")
  foreach(property RANGE 0 ${last_property})
    string(JSON key GET "${inventory}" tests ${index} properties ${property} name)
    if(key STREQUAL "PROCESSORS")
      string(JSON processors GET "${inventory}" tests ${index} properties ${property} value)
    elseif(key STREQUAL "TIMEOUT")
      string(JSON timeout GET "${inventory}" tests ${index} properties ${property} value)
    endif()
  endforeach()
  if(NOT processors EQUAL 2 OR NOT timeout EQUAL 300)
    message(FATAL_ERROR "${name} must retain a two-worker budget and 300-second timeout")
  endif()

  set(has_matching_budget FALSE)
  string(JSON command_count LENGTH "${inventory}" tests ${index} command)
  math(EXPR last_argument "${command_count} - 1")
  foreach(argument RANGE 0 ${last_argument})
    string(JSON value GET "${inventory}" tests ${index} command ${argument})
    if(value STREQUAL "-DBUILD_PARALLELISM=${processors}")
      set(has_matching_budget TRUE)
    endif()
  endforeach()
  if(NOT has_matching_budget)
    message(FATAL_ERROR "${name} does not pass its scheduler budget to the nested build")
  endif()
endforeach()
if(expected_names)
  message(FATAL_ERROR "missing isolation-budget coverage: ${expected_names}")
endif()
