cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED SOURCE_DIR OR NOT DEFINED TEST_BINARY_DIR)
  message(FATAL_ERROR "SOURCE_DIR and TEST_BINARY_DIR are required")
endif()
file(REAL_PATH "${SOURCE_DIR}/build" build_root)
cmake_path(ABSOLUTE_PATH TEST_BINARY_DIR NORMALIZE OUTPUT_VARIABLE test_root)
cmake_path(IS_PREFIX build_root "${test_root}" NORMALIZE under_build)
if(NOT under_build OR test_root STREQUAL build_root)
  message(FATAL_ERROR "synthetic control-join artifacts must stay beneath root build/")
endif()
# Deliberately synthetic evidence tests verifier rejection only, never MATLAB execution.
set(reference "${TEST_BINARY_DIR}/official")
file(MAKE_DIRECTORY "${reference}/source")
set(revision "0123456789abcdef0123456789abcdef01234567")
set(names matlab-mutable-array-joins matlab-mutable-value-joins matlab-matrix-expression-spacing)
set(sources examples/matlab/mutable_array_joins.m tests/fixtures/matlab_mutable_value_joins.m
  examples/matlab/matrix_expression_spacing.m)
set(outputs "4 3 5 3" "2 1 1 2 3" "2 3 2 3 2 -3 2 4 2 4 4 5 3 2 4 8")
set(cases "")
foreach(index RANGE 0 2)
  list(GET names ${index} name)
  list(GET sources ${index} source)
  list(GET outputs ${index} output)
  get_filename_component(basename "${source}" NAME)
  configure_file("${SOURCE_DIR}/${source}" "${reference}/source/${basename}" COPYONLY)
  file(WRITE "${reference}/${name}.stdout" "${output}\n")
  file(WRITE "${TEST_BINARY_DIR}/${name}.txt"
    "case=${name}\ninput=${SOURCE_DIR}/${source}\nnode=synthetic-node\njavascript=${output}\n")
  if(index EQUAL 1)
    file(APPEND "${TEST_BINARY_DIR}/${name}.txt" "cpp=MPF2007\n")
    set(diagnostics "{\"diagnostics\":[{\"code\":\"MPF2007\",\"source\":\"${SOURCE_DIR}/${source}\"}]}")
    file(WRITE "${TEST_BINARY_DIR}/cpp-diagnostics.json" "${diagnostics}")
  else()
    file(APPEND "${TEST_BINARY_DIR}/${name}.txt" "cxx-compiler=synthetic-cxx\ncpp=${output}\n")
  endif()
  if(index GREATER 0)
    string(APPEND cases ",")
  endif()
  string(APPEND cases "{\"caseName\":\"${name}\",\"source\":\"${source}\","
    "\"sourceSnapshot\":\"source/${basename}\"}")
endforeach()
set(provenance "{\"schemaVersion\":1,\"matlabRelease\":\"R2024b\","
  "\"matlabVersion\":\"synthetic-verifier-fixture\",\"sourceRevision\":\"${revision}\",\"cases\":[${cases}]}")
string(JOIN "" provenance ${provenance})
file(WRITE "${reference}/control-join-parity.json" "${provenance}")
function(check case_name expected_success)
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DSOURCE_DIR=${SOURCE_DIR}" "-DREFERENCE_DIR=${reference}" "-DSOURCE_REVISION=${revision}"
    "-DARRAY_RESULT=${TEST_BINARY_DIR}/matlab-mutable-array-joins.txt"
    "-DVALUE_RESULT=${TEST_BINARY_DIR}/matlab-mutable-value-joins.txt"
    "-DSPACING_RESULT=${TEST_BINARY_DIR}/matlab-matrix-expression-spacing.txt"
    -P "${SOURCE_DIR}/tests/cmake/verify_matlab_control_join_parity.cmake"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${TEST_BINARY_DIR}/${case_name}.log" "${output}${error}")
  if((expected_success AND NOT status EQUAL 0) OR (NOT expected_success AND status EQUAL 0))
    message(FATAL_ERROR "synthetic control-join verifier ${case_name}: ${output}${error}")
  endif()
endfunction()
check(positive TRUE)
file(APPEND "${reference}/source/mutable_array_joins.m" "\n% corrupted snapshot\n")
check(changed-snapshot FALSE)
configure_file("${SOURCE_DIR}/examples/matlab/mutable_array_joins.m"
  "${reference}/source/mutable_array_joins.m" COPYONLY)
file(WRITE "${reference}/matlab-mutable-value-joins.stdout" "2 1 1 2 99")
check(changed-native-result FALSE)
file(WRITE "${reference}/matlab-mutable-value-joins.stdout" "2 1 1 2 3")
file(APPEND "${TEST_BINARY_DIR}/matlab-mutable-array-joins.txt" "cpp=4 3 5 3\n")
check(duplicate-target-field FALSE)
file(READ "${TEST_BINARY_DIR}/matlab-mutable-array-joins.txt" target)
string(REGEX REPLACE "cpp=4 3 5 3\n$" "" target "${target}")
file(WRITE "${TEST_BINARY_DIR}/matlab-mutable-array-joins.txt" "${target}")
string(REPLACE "MPF2007" "MPF0006" poisoned "${diagnostics}")
file(WRITE "${TEST_BINARY_DIR}/cpp-diagnostics.json" "${poisoned}")
check(public-MIR-rejection FALSE)
file(WRITE "${TEST_BINARY_DIR}/cpp-diagnostics.json" "${diagnostics}")
string(REPLACE "R2024b" "R2023b" poisoned "${provenance}")
file(WRITE "${reference}/control-join-parity.json" "${poisoned}")
check(wrong-runtime FALSE)
file(WRITE "${reference}/control-join-parity.json" "${provenance}")
string(REPLACE "${revision}" "abcdef0123456789abcdef0123456789abcdef01" poisoned "${provenance}")
file(WRITE "${reference}/control-join-parity.json" "${poisoned}")
check(wrong-revision FALSE)
file(WRITE "${reference}/control-join-parity.json" "${provenance}")
file(REMOVE "${reference}/source/matlab_mutable_value_joins.m")
check(missing-source FALSE)
message(STATUS "synthetic control-join verifier positive and seven rejection contracts passed")
