cmake_minimum_required(VERSION 3.20)

# Frozen from an actual R2024b execution; collection alone is not target parity.
function(verify_matlab_empty_validator_observations observations contract_path)
  file(READ "${contract_path}" contract)
  string(JSON schema ERROR_VARIABLE error GET "${contract}" schemaVersion)
  if(NOT error STREQUAL "NOTFOUND" OR NOT schema STREQUAL "1")
    message(FATAL_ERROR "Invalid empty-validator baseline schema")
  endif()
  string(JSON release GET "${contract}" matlabRelease)
  if(NOT release STREQUAL "R2024b")
    message(FATAL_ERROR "Empty-validator baseline requires R2024b")
  endif()
  set(keys
    numeric numeric_or_logical floating real finite
    non_nan positive nonpositive nonnegative negative
    nonzero integer nonempty scalar_or_empty vector
    row column matrix nonmissing nonzero_length_text
    text text_scalar valid_variable_name greater_than greater_than_or_equal
    less_than less_than_or_equal in_range
  )
  set(contexts direct input output)
  list(LENGTH keys key_count)
  math(EXPR expected_count "${key_count} * 3")
  foreach(matrix emptyCharacter emptyNumeric)
    string(JSON count ERROR_VARIABLE error LENGTH "${observations}" "${matrix}")
    string(JSON contract_count LENGTH "${contract}" "${matrix}")
    if(NOT error STREQUAL "NOTFOUND" OR NOT count EQUAL expected_count OR
        NOT contract_count EQUAL expected_count)
      message(FATAL_ERROR "Native empty-validator inventory is incomplete: ${matrix}")
    endif()
    string(JSON records GET "${observations}" "${matrix}")
    string(JSON expected_records GET "${contract}" "${matrix}")
    set(index 0)
    foreach(key IN LISTS keys)
      foreach(context IN LISTS contexts)
        string(JSON record GET "${records}" ${index})
        string(JSON expected_record GET "${expected_records}" ${index})
        foreach(field name validator context exceptionIdentifier exceptionMessage)
          string(JSON field_type ERROR_VARIABLE error TYPE
            "${record}" "${field}")
          if(NOT error STREQUAL "NOTFOUND" OR NOT field_type STREQUAL "STRING")
            message(FATAL_ERROR "Native empty-validator textual metadata must be strings")
          endif()
        endforeach()
        string(JSON name GET "${record}" name)
        string(JSON actual_context GET "${record}" context)
        if(NOT name STREQUAL "${key}-${context}" OR NOT actual_context STREQUAL context)
          message(FATAL_ERROR "Native empty-validator order/identity differs: ${matrix}/${index}")
        endif()
        string(JSON success_type ERROR_VARIABLE error TYPE
          "${record}" succeeded)
        if(NOT error STREQUAL "NOTFOUND" OR NOT success_type STREQUAL "BOOLEAN")
          message(FATAL_ERROR "Native empty-validator outcome must be a boolean")
        endif()
        string(JSON cause_type ERROR_VARIABLE error TYPE
          "${record}" causeIdentifiers)
        if(NOT error STREQUAL "NOTFOUND" OR NOT cause_type STREQUAL "ARRAY")
          message(FATAL_ERROR "Native empty-validator causes must be an array")
        endif()
        foreach(field name validator context succeeded exceptionIdentifier causeIdentifiers)
          string(JSON actual GET "${record}" "${field}")
          string(JSON expected GET "${expected_record}" "${field}")
          if(NOT actual STREQUAL expected)
            message(FATAL_ERROR
              "Native empty-validator differs from R2024b: ${matrix}/${name}/${field}")
          endif()
        endforeach()
        string(JSON success GET "${record}" succeeded)
        string(JSON identifier GET "${record}" exceptionIdentifier)
        string(JSON message GET "${record}" exceptionMessage)
        if(success)
          if(NOT identifier STREQUAL "" OR NOT message STREQUAL "")
            message(FATAL_ERROR "Successful native empty-validator retains an exception")
          endif()
        elseif(NOT identifier MATCHES "^MATLAB:validators:[A-Za-z]+$" OR message STREQUAL "")
          message(FATAL_ERROR "Failed native empty-validator has no complete exception")
        endif()
        string(JSON fragment GET "${expected_record}" exceptionMessageContains)
        string(FIND "${message}" "${fragment}" position)
        if(position LESS 0)
          message(FATAL_ERROR "Native empty-validator exception context/message differs")
        endif()
        math(EXPR index "${index} + 1")
      endforeach()
    endforeach()
  endforeach()
  math(EXPR total "${expected_count} * 2")
  message(STATUS "Checked ${total} native empty-validator observations; target parity is separate")
endfunction()
