#include "matrix_runtime.hpp"

#include <ostream>

namespace mpf::detail {

void emit_javascript_matrix_solve_runtime(std::ostream& output) {
  output << "function __mpf_matlab_cpqr_factor(values) {\n"
            "  const rows = values.length; const columns = values[0].length;\n"
            "  const pivots = Math.min(rows, columns);\n"
            "  const qr = values.map((row) => row.slice());\n"
            "  const tau = new Array(pivots).fill(0);\n"
            "  const permutation = Array.from({ length: columns }, (_, index) => index);\n"
            "  let scale = 0;\n"
            "  for (let column = 0; column < columns; ++column) {\n"
            "    let norm = 0;\n"
            "    for (let row = 0; row < rows; ++row) norm = Math.hypot(norm, qr[row][column]);\n"
            "    scale = Math.max(scale, norm);\n"
            "  }\n"
            "  const tolerance = Number.EPSILON * Math.max(rows, columns) * scale;\n"
            "  let rank = 0;\n"
            "  for (let pivot = 0; pivot < pivots; ++pivot) {\n"
            "    let selected = pivot; let selectedNorm = -1;\n"
            "    for (let column = pivot; column < columns; ++column) {\n"
            "      let norm = 0;\n"
            "      for (let row = pivot; row < rows; ++row) "
            "norm = Math.hypot(norm, qr[row][column]);\n"
            "      if (norm > selectedNorm) { selected = column; selectedNorm = norm; }\n"
            "    }\n"
            "    if (selectedNorm <= tolerance) break;\n"
            "    if (selected !== pivot) {\n"
            "      for (let row = 0; row < rows; ++row) "
            "[qr[row][pivot], qr[row][selected]] = [qr[row][selected], qr[row][pivot]];\n"
            "      [permutation[pivot], permutation[selected]] = "
            "[permutation[selected], permutation[pivot]];\n"
            "    }\n"
            "    const alpha = qr[pivot][pivot];\n"
            "    const beta = alpha <= 0 ? selectedNorm : -selectedNorm;\n"
            "    const leading = alpha - beta;\n"
            "    tau[pivot] = (beta - alpha) / beta;\n"
            "    qr[pivot][pivot] = beta;\n"
            "    for (let row = pivot + 1; row < rows; ++row) qr[row][pivot] /= leading;\n"
            "    for (let column = pivot + 1; column < columns; ++column) {\n"
            "      let projection = qr[pivot][column];\n"
            "      for (let row = pivot + 1; row < rows; ++row) "
            "projection += qr[row][pivot] * qr[row][column];\n"
            "      projection *= tau[pivot];\n"
            "      qr[pivot][column] -= projection;\n"
            "      for (let row = pivot + 1; row < rows; ++row) "
            "qr[row][column] -= qr[row][pivot] * projection;\n"
            "    }\n"
            "    rank = pivot + 1;\n"
            "  }\n"
            "  return { qr, tau, permutation, rank, tolerance };\n"
            "}\n"
            "function __mpf_matlab_apply_cpqr_qt(factor, values) {\n"
            "  const result = values.map((row) => row.slice());\n"
            "  for (let pivot = 0; pivot < factor.rank; ++pivot) {\n"
            "    for (let column = 0; column < result[0].length; ++column) {\n"
            "      let projection = result[pivot][column];\n"
            "      for (let row = pivot + 1; row < result.length; ++row) "
            "projection += factor.qr[row][pivot] * result[row][column];\n"
            "      projection *= factor.tau[pivot];\n"
            "      result[pivot][column] -= projection;\n"
            "      for (let row = pivot + 1; row < result.length; ++row) "
            "result[row][column] -= factor.qr[row][pivot] * projection;\n"
            "    }\n"
            "  }\n"
            "  return result;\n"
            "}\n"
            "function __mpf_matlab_basic_least_squares(left, right) {\n"
            "  const factor = __mpf_matlab_cpqr_factor(left);\n"
            "  const transformed = __mpf_matlab_apply_cpqr_qt(factor, right);\n"
            "  const columns = left[0].length; const outputs = right[0].length;\n"
            "  if (factor.rank < Math.min(left.length, columns)) console.warn(\n"
            "    `MPF Matlab matrix is rank deficient to working precision (rank "
            "${factor.rank}, tolerance ${factor.tolerance}); using a basic least-squares "
            "solution`);\n"
            "  const pivoted = Array.from({ length: columns }, () => new Array(outputs).fill(0));\n"
            "  for (let reverse = factor.rank; reverse > 0; --reverse) {\n"
            "    const row = reverse - 1;\n"
            "    for (let output = 0; output < outputs; ++output) {\n"
            "      let value = transformed[row][output];\n"
            "      for (let inner = row + 1; inner < columns; ++inner) "
            "value -= factor.qr[row][inner] * pivoted[inner][output];\n"
            "      pivoted[row][output] = value / factor.qr[row][row];\n"
            "    }\n"
            "  }\n"
            "  const result = Array.from({ length: columns }, () => new Array(outputs).fill(0));\n"
            "  for (let row = 0; row < columns; ++row) "
            "result[factor.permutation[row]] = pivoted[row];\n"
            "  return result;\n"
            "}\n"
            "function __mpf_matlab_overdetermined_solve(left, right) {\n"
            "  return __mpf_matlab_basic_least_squares(left, right);\n"
            "}\n"
            "function __mpf_matlab_underdetermined_solve(left, right) {\n"
            "  return __mpf_matlab_basic_least_squares(left, right);\n"
            "}\n"
            "function __mpf_matlab_matrix_solve_planned(leftValue, rightValue, solve) {\n"
            "  const left = __mpf_matlab_dense_matrix(leftValue, 'coefficient matrix');\n"
            "  const right = __mpf_matlab_dense_matrix(rightValue, 'right-hand side');\n"
            "  if (right.length !== left.length) "
            "throw new RangeError('MPF Matlab matrix solve shape mismatch');\n"
            "  if (solve === 'square' && left.length === left[0].length) "
            "return __mpf_matlab_lu_solve(left, right);\n"
            "  if (solve === 'overdetermined' && left.length > left[0].length) "
            "return __mpf_matlab_overdetermined_solve(left, right);\n"
            "  if (solve === 'underdetermined' && left.length < left[0].length) "
            "return __mpf_matlab_underdetermined_solve(left, right);\n"
            "  throw new RangeError('MPF Matlab matrix solve disagrees with its static solve "
            "plan');\n"
            "}\n"
            "function __mpf_matlab_mldivide_square(left, right) {\n"
            "  return __mpf_matlab_matrix_solve_planned(left, right, 'square');\n"
            "}\n"
            "function __mpf_matlab_mldivide_overdetermined(left, right) {\n"
            "  return __mpf_matlab_matrix_solve_planned(left, right, 'overdetermined');\n"
            "}\n"
            "function __mpf_matlab_mldivide_underdetermined(left, right) {\n"
            "  return __mpf_matlab_matrix_solve_planned(left, right, 'underdetermined');\n"
            "}\n"
            "function __mpf_matlab_mrdivide_planned(left, right, solve) {\n"
            "  const normalizedLeft = __mpf_matlab_dense_matrix(left, 'left operand');\n"
            "  const normalizedRight = __mpf_matlab_dense_matrix(right, 'right divisor');\n"
            "  return __mpf_matlab_matrix_transpose(__mpf_matlab_matrix_solve_planned("
            "__mpf_matlab_matrix_transpose(normalizedRight), "
            "__mpf_matlab_matrix_transpose(normalizedLeft), solve));\n"
            "}\n"
            "function __mpf_matlab_mrdivide_square(left, right) {\n"
            "  return __mpf_matlab_mrdivide_planned(left, right, 'square');\n"
            "}\n"
            "function __mpf_matlab_mrdivide_overdetermined(left, right) {\n"
            "  return __mpf_matlab_mrdivide_planned(left, right, 'overdetermined');\n"
            "}\n"
            "function __mpf_matlab_mrdivide_underdetermined(left, right) {\n"
            "  return __mpf_matlab_mrdivide_planned(left, right, 'underdetermined');\n"
            "}\n";
}

}  // namespace mpf::detail
