#include "matrix_runtime.hpp"

#include <ostream>

namespace mpf::detail {

void emit_javascript_matrix_solve_runtime(std::ostream& output) {
  output
      << "function __mpf_matlab_matrix_one_norm(values) {\n"
         "  let maximum = 0;\n"
         "  for (let column = 0; column < values[0].length; ++column) {\n"
         "    let sum = 0;\n"
         "    for (let row = 0; row < values.length; ++row) {\n"
         "      if (!Number.isFinite(values[row][column])) return Infinity;\n"
         "      sum += Math.abs(values[row][column]);\n"
         "    }\n"
         "    maximum = Math.max(maximum, sum);\n"
         "  }\n"
         "  return maximum;\n"
         "}\n"
         "function __mpf_matlab_lu_factor(coefficients) {\n"
         "  const size = coefficients.length;\n"
         "  const lu = coefficients.map((row) => row.slice());\n"
         "  const swaps = new Array(size);\n"
         "  let singular = false;\n"
         "  for (let pivot = 0; pivot < size; ++pivot) {\n"
         "    let selected = pivot;\n"
         "    for (let row = pivot + 1; row < size; ++row) "
         "if (Math.abs(lu[row][pivot]) > Math.abs(lu[selected][pivot])) selected = row;\n"
         "    swaps[pivot] = selected;\n"
         "    if (selected !== pivot) [lu[pivot], lu[selected]] = [lu[selected], lu[pivot]];\n"
         "    const diagonal = lu[pivot][pivot];\n"
         "    if (diagonal === 0) { singular = true; continue; }\n"
         "    for (let row = pivot + 1; row < size; ++row) {\n"
         "      lu[row][pivot] /= diagonal;\n"
         "      for (let column = pivot + 1; column < size; ++column) "
         "lu[row][column] -= lu[row][pivot] * lu[pivot][column];\n"
         "    }\n"
         "  }\n"
         "  return { lu, swaps, singular };\n"
         "}\n"
         "function __mpf_matlab_lu_apply(factor, values) {\n"
         "  const size = factor.lu.length;\n"
         "  const result = values.map((row) => row.slice());\n"
         "  for (let pivot = 0; pivot < size; ++pivot) {\n"
         "    const selected = factor.swaps[pivot];\n"
         "    if (selected !== pivot) [result[pivot], result[selected]] = "
         "[result[selected], result[pivot]];\n"
         "  }\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let inner = 0; inner < row; ++inner) {\n"
         "      const coefficient = factor.lu[row][inner];\n"
         "      if (coefficient === 0) continue;\n"
         "      for (let column = 0; column < result[0].length; ++column) "
         "result[row][column] -= coefficient * result[inner][column];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let column = 0; column < result[0].length; ++column) {\n"
         "      let value = result[row][column];\n"
         "      for (let inner = row + 1; inner < size; ++inner) {\n"
         "        const coefficient = factor.lu[row][inner];\n"
         "        if (coefficient !== 0) value -= coefficient * result[inner][column];\n"
         "      }\n"
         "      result[row][column] = value / factor.lu[row][row];\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_lu_apply_transpose(factor, values) {\n"
         "  const size = factor.lu.length;\n"
         "  const result = values.map((row) => row.slice());\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let column = 0; column < result[0].length; ++column) {\n"
         "      let value = result[row][column];\n"
         "      for (let inner = 0; inner < row; ++inner) {\n"
         "        const coefficient = factor.lu[inner][row];\n"
         "        if (coefficient !== 0) value -= coefficient * result[inner][column];\n"
         "      }\n"
         "      result[row][column] = value / factor.lu[row][row];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let inner = row + 1; inner < size; ++inner) {\n"
         "      const coefficient = factor.lu[inner][row];\n"
         "      if (coefficient === 0) continue;\n"
         "      for (let column = 0; column < result[0].length; ++column) "
         "result[row][column] -= coefficient * result[inner][column];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const pivot = reverse - 1; const selected = factor.swaps[pivot];\n"
         "    if (selected !== pivot) [result[pivot], result[selected]] = "
         "[result[selected], result[pivot]];\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_solver_rcond(coefficients, solve, solveTranspose) {\n"
         "  const norm = __mpf_matlab_matrix_one_norm(coefficients);\n"
         "  if (norm === 0 || !Number.isFinite(norm)) return 0;\n"
         "  const size = coefficients.length;\n"
         "  let vector = Array.from({ length: size }, () => [1 / size]);\n"
         "  let inverseNorm = 0;\n"
         "  for (let iteration = 0; iteration < 5; ++iteration) {\n"
         "    const solved = solve(vector);\n"
         "    const estimate = solved.reduce((sum, row) => sum + Math.abs(row[0]), 0);\n"
         "    if (!Number.isFinite(estimate)) return 0;\n"
         "    inverseNorm = Math.max(inverseNorm, estimate);\n"
         "    const signs = solved.map((row) => [row[0] >= 0 ? 1 : -1]);\n"
         "    const transposed = solveTranspose(signs);\n"
         "    if (!transposed.every((row) => Number.isFinite(row[0]))) return 0;\n"
         "    let selected = 0;\n"
         "    for (let row = 1; row < size; ++row) "
         "if (Math.abs(transposed[row][0]) > Math.abs(transposed[selected][0])) selected = row;\n"
         "    let dual = 0;\n"
         "    for (let row = 0; row < size; ++row) dual += transposed[row][0] * vector[row][0];\n"
         "    if (Math.abs(transposed[selected][0]) <= dual) break;\n"
         "    vector = Array.from({ length: size }, (_, row) => [row === selected ? 1 : 0]);\n"
         "  }\n"
         "  const product = norm * inverseNorm;\n"
         "  return product > 0 && Number.isFinite(product) ? Math.min(1, 1 / product) : 0;\n"
         "}\n"
         "function __mpf_matlab_lu_rcond(coefficients, factor) {\n"
         "  if (factor.singular) return 0;\n"
         "  return __mpf_matlab_solver_rcond(\n"
         "      coefficients, (values) => __mpf_matlab_lu_apply(factor, values),\n"
         "      (values) => __mpf_matlab_lu_apply_transpose(factor, values));\n"
         "}\n"
         "function __mpf_matlab_warn_square_condition(rcond) {\n"
         "  if (rcond === 0) {\n"
         "    console.warn('MPF Matlab matrix is singular to working precision.');\n"
         "  } else if (rcond < Number.EPSILON) {\n"
         "    console.warn(`MPF Matlab matrix is close to singular or badly scaled. "
         "Results may be inaccurate. RCOND = ${rcond}.`);\n"
         "  }\n"
         "}\n"
         "function __mpf_matlab_lu_solve(coefficients, rightHandSide) {\n"
         "  const left = __mpf_matlab_dense_matrix(coefficients, 'coefficient matrix');\n"
         "  const right = __mpf_matlab_dense_matrix(rightHandSide, 'right-hand side');\n"
         "  const size = left.length;\n"
         "  if (left[0].length !== size || right.length !== size) "
         "throw new RangeError('MPF Matlab matrix solve shape mismatch');\n"
         "  const factor = __mpf_matlab_lu_factor(left);\n"
         "  __mpf_matlab_warn_square_condition(__mpf_matlab_lu_rcond(left, factor));\n"
         "  return __mpf_matlab_lu_apply(factor, right);\n"
         "}\n"
         "function __mpf_matlab_square_structure(values) {\n"
         "  let upper = true; let lower = true; let tridiagonal = true; let symmetric = true;\n"
         "  for (let row = 0; row < values.length; ++row) {\n"
         "    for (let column = 0; column < values.length; ++column) {\n"
         "      const value = values[row][column];\n"
         "      if (Math.abs(row - column) > 1 && value !== 0) tridiagonal = false;\n"
         "      if (row > column && value !== values[column][row]) symmetric = false;\n"
         "      if (row === column || value === 0) continue;\n"
         "      if (row > column) upper = false; else lower = false;\n"
         "    }\n"
         "  }\n"
         "  if (upper && lower) return 'diagonal';\n"
         "  if (upper) return 'upper';\n"
         "  if (lower) return 'lower';\n"
         "  if (tridiagonal) return 'tridiagonal';\n"
         "  if (symmetric) return 'symmetric';\n"
         "  return 'dense';\n"
         "}\n"
         "function __mpf_matlab_diagonal_rcond(values) {\n"
         "  let smallest = Infinity; let largest = 0;\n"
         "  for (let index = 0; index < values.length; ++index) {\n"
         "    const magnitude = Math.abs(values[index][index]);\n"
         "    if (magnitude === 0 || !Number.isFinite(magnitude)) return 0;\n"
         "    smallest = Math.min(smallest, magnitude); largest = Math.max(largest, magnitude);\n"
         "  }\n"
         "  return smallest / largest;\n"
         "}\n"
         "function __mpf_matlab_diagonal_apply(coefficients, values) {\n"
         "  return values.map((row, index) => "
         "row.map((value) => value / coefficients[index][index]));\n"
         "}\n"
         "function __mpf_matlab_triangular_apply(coefficients, values, upper) {\n"
         "  const result = values.map((row) => row.slice());\n"
         "  if (upper) {\n"
         "    for (let reverse = coefficients.length; reverse > 0; --reverse) {\n"
         "      const row = reverse - 1;\n"
         "      for (let column = 0; column < result[0].length; ++column) {\n"
         "        let value = result[row][column];\n"
         "        for (let inner = row + 1; inner < coefficients.length; ++inner) "
         "value -= coefficients[row][inner] * result[inner][column];\n"
         "        result[row][column] = value / coefficients[row][row];\n"
         "      }\n"
         "    }\n"
         "  } else {\n"
         "    for (let row = 0; row < coefficients.length; ++row) {\n"
         "      for (let column = 0; column < result[0].length; ++column) {\n"
         "        let value = result[row][column];\n"
         "        for (let inner = 0; inner < row; ++inner) "
         "value -= coefficients[row][inner] * result[inner][column];\n"
         "        result[row][column] = value / coefficients[row][row];\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_triangular_apply_transpose(coefficients, values, upper) {\n"
         "  return __mpf_matlab_triangular_apply("
         "__mpf_matlab_matrix_transpose(coefficients), values, !upper);\n"
         "}\n"
         "function __mpf_matlab_triangular_rcond(coefficients, upper) {\n"
         "  const size = coefficients.length;\n"
         "  for (let index = 0; index < size; ++index) "
         "if (coefficients[index][index] === 0 || !Number.isFinite(coefficients[index][index])) "
         "return 0;\n"
         "  return __mpf_matlab_solver_rcond(\n"
         "      coefficients,\n"
         "      (values) => __mpf_matlab_triangular_apply(coefficients, values, upper),\n"
         "      (values) => "
         "__mpf_matlab_triangular_apply_transpose(coefficients, values, upper));\n"
         "}\n"
         "function __mpf_matlab_tridiagonal_factor(coefficients) {\n"
         "  const size = coefficients.length;\n"
         "  const lower = Array.from({ length: Math.max(0, size - 1) }, "
         "(_, row) => coefficients[row + 1][row]);\n"
         "  const diagonal = Array.from({ length: size }, (_, row) => coefficients[row][row]);\n"
         "  const upper = Array.from({ length: Math.max(0, size - 1) }, "
         "(_, row) => coefficients[row][row + 1]);\n"
         "  const secondUpper = new Array(Math.max(0, size - 2)).fill(0);\n"
         "  const pivots = Array.from({ length: size }, (_, row) => row);\n"
         "  for (let pivot = 0; pivot + 1 < size; ++pivot) {\n"
         "    if (Math.abs(diagonal[pivot]) >= Math.abs(lower[pivot])) {\n"
         "      if (diagonal[pivot] !== 0) {\n"
         "        const factor = lower[pivot] / diagonal[pivot];\n"
         "        lower[pivot] = factor;\n"
         "        diagonal[pivot + 1] -= factor * upper[pivot];\n"
         "      }\n"
         "    } else {\n"
         "      const factor = diagonal[pivot] / lower[pivot];\n"
         "      diagonal[pivot] = lower[pivot];\n"
         "      lower[pivot] = factor;\n"
         "      const previousUpper = upper[pivot];\n"
         "      upper[pivot] = diagonal[pivot + 1];\n"
         "      diagonal[pivot + 1] = previousUpper - factor * diagonal[pivot + 1];\n"
         "      if (pivot + 2 < size) {\n"
         "        secondUpper[pivot] = upper[pivot + 1];\n"
         "        upper[pivot + 1] = -factor * upper[pivot + 1];\n"
         "      }\n"
         "      pivots[pivot] = pivot + 1;\n"
         "    }\n"
         "  }\n"
         "  const singular = diagonal.some((value) => value === 0 || !Number.isFinite(value));\n"
         "  return { lower, diagonal, upper, secondUpper, pivots, singular };\n"
         "}\n"
         "function __mpf_matlab_tridiagonal_apply(factor, values) {\n"
         "  const result = values.map((row) => row.slice());\n"
         "  const size = factor.diagonal.length; const columns = result[0].length;\n"
         "  for (let pivot = 0; pivot + 1 < size; ++pivot) {\n"
         "    for (let column = 0; column < columns; ++column) {\n"
         "      if (factor.pivots[pivot] === pivot) {\n"
         "        result[pivot + 1][column] -= factor.lower[pivot] * result[pivot][column];\n"
         "      } else {\n"
         "        const previous = result[pivot][column];\n"
         "        result[pivot][column] = result[pivot + 1][column];\n"
         "        result[pivot + 1][column] = "
         "previous - factor.lower[pivot] * result[pivot][column];\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let column = 0; column < columns; ++column) {\n"
         "      let value = result[row][column];\n"
         "      if (row + 1 < size) value -= factor.upper[row] * result[row + 1][column];\n"
         "      if (row + 2 < size) value -= factor.secondUpper[row] * result[row + 2][column];\n"
         "      result[row][column] = value / factor.diagonal[row];\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_tridiagonal_apply_transpose(factor, values) {\n"
         "  const result = values.map((row) => row.slice());\n"
         "  const size = factor.diagonal.length; const columns = result[0].length;\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let column = 0; column < columns; ++column) {\n"
         "      let value = result[row][column];\n"
         "      if (row > 0) value -= factor.upper[row - 1] * result[row - 1][column];\n"
         "      if (row > 1) value -= factor.secondUpper[row - 2] * result[row - 2][column];\n"
         "      result[row][column] = value / factor.diagonal[row];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size - 1; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let column = 0; column < columns; ++column) {\n"
         "      if (factor.pivots[row] === row) {\n"
         "        result[row][column] -= factor.lower[row] * result[row + 1][column];\n"
         "      } else {\n"
         "        const following = result[row + 1][column];\n"
         "        result[row + 1][column] = "
         "result[row][column] - factor.lower[row] * following;\n"
         "        result[row][column] = following;\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_tridiagonal_rcond(coefficients, factor) {\n"
         "  if (factor.singular) return 0;\n"
         "  return __mpf_matlab_solver_rcond(\n"
         "      coefficients, (values) => __mpf_matlab_tridiagonal_apply(factor, values),\n"
         "      (values) => __mpf_matlab_tridiagonal_apply_transpose(factor, values));\n"
         "}\n"
         "function __mpf_matlab_cholesky_factor(coefficients) {\n"
         "  const size = coefficients.length;\n"
         "  const lower = Array.from({ length: size }, () => new Array(size).fill(0));\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let column = 0; column <= row; ++column) {\n"
         "      let value = coefficients[row][column];\n"
         "      for (let inner = 0; inner < column; ++inner) "
         "value -= lower[row][inner] * lower[column][inner];\n"
         "      if (row === column) {\n"
         "        if (!(value > 0) || !Number.isFinite(value)) "
         "return { lower, positiveDefinite: false };\n"
         "        lower[row][column] = Math.sqrt(value);\n"
         "      } else {\n"
         "        lower[row][column] = value / lower[column][column];\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  return { lower, positiveDefinite: true };\n"
         "}\n"
         "function __mpf_matlab_cholesky_apply(factor, values) {\n"
         "  const result = values.map((row) => row.slice());\n"
         "  const size = factor.lower.length; const columns = result[0].length;\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let column = 0; column < columns; ++column) {\n"
         "      let value = result[row][column];\n"
         "      for (let inner = 0; inner < row; ++inner) "
         "value -= factor.lower[row][inner] * result[inner][column];\n"
         "      result[row][column] = value / factor.lower[row][row];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let column = 0; column < columns; ++column) {\n"
         "      let value = result[row][column];\n"
         "      for (let inner = row + 1; inner < size; ++inner) "
         "value -= factor.lower[inner][row] * result[inner][column];\n"
         "      result[row][column] = value / factor.lower[row][row];\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_cholesky_rcond(coefficients, factor) {\n"
         "  return __mpf_matlab_solver_rcond(\n"
         "      coefficients, (values) => __mpf_matlab_cholesky_apply(factor, values),\n"
         "      (values) => __mpf_matlab_cholesky_apply(factor, values));\n"
         "}\n"
         "function __mpf_matlab_structured_real_square_solve(left, right) {\n"
         "  const structure = __mpf_matlab_square_structure(left);\n"
         "  if (structure === 'diagonal') {\n"
         "    __mpf_matlab_warn_square_condition(__mpf_matlab_diagonal_rcond(left));\n"
         "    return __mpf_matlab_diagonal_apply(left, right);\n"
         "  }\n"
         "  if (structure === 'upper' || structure === 'lower') {\n"
         "    const upper = structure === 'upper';\n"
         "    __mpf_matlab_warn_square_condition(__mpf_matlab_triangular_rcond(left, upper));\n"
         "    return __mpf_matlab_triangular_apply(left, right, upper);\n"
         "  }\n"
         "  if (structure === 'tridiagonal') {\n"
         "    const factor = __mpf_matlab_tridiagonal_factor(left);\n"
         "    __mpf_matlab_warn_square_condition(__mpf_matlab_tridiagonal_rcond(left, factor));\n"
         "    return __mpf_matlab_tridiagonal_apply(factor, right);\n"
         "  }\n"
         "  if (structure === 'symmetric') {\n"
         "    const factor = __mpf_matlab_cholesky_factor(left);\n"
         "    if (factor.positiveDefinite) {\n"
         "      __mpf_matlab_warn_square_condition(__mpf_matlab_cholesky_rcond(left, factor));\n"
         "      return __mpf_matlab_cholesky_apply(factor, right);\n"
         "    }\n"
         "  }\n"
         "  return __mpf_matlab_lu_solve(left, right);\n"
         "}\n"
         "function __mpf_matlab_cpqr_factor(values) {\n"
         "  const rows = values.length; const columns = values[0].length;\n"
         "  const pivots = Math.min(rows, columns);\n"
         "  const qr = values.map((row) => row.slice());\n"
         "  const tau = new Array(pivots).fill(0);\n"
         "  const permutation = Array.from({ length: columns }, (_, index) => index);\n"
         "  let scale = 0;\n"
         "  for (let column = 0; column < columns; ++column) {\n"
         "    let norm = 0;\n"
         "    for (let row = 0; row < rows; ++row) norm = Math.hypot(norm, qr[row][column]);\n"
         "    scale = Math.max(scale, norm);\n"
         "  }\n"
         "  const tolerance = Number.EPSILON * Math.max(rows, columns) * scale;\n"
         "  let rank = 0;\n"
         "  for (let pivot = 0; pivot < pivots; ++pivot) {\n"
         "    let selected = pivot; let selectedNorm = -1;\n"
         "    for (let column = pivot; column < columns; ++column) {\n"
         "      let norm = 0;\n"
         "      for (let row = pivot; row < rows; ++row) "
         "norm = Math.hypot(norm, qr[row][column]);\n"
         "      if (norm > selectedNorm) { selected = column; selectedNorm = norm; }\n"
         "    }\n"
         "    if (selectedNorm <= tolerance) break;\n"
         "    if (selected !== pivot) {\n"
         "      for (let row = 0; row < rows; ++row) "
         "[qr[row][pivot], qr[row][selected]] = [qr[row][selected], qr[row][pivot]];\n"
         "      [permutation[pivot], permutation[selected]] = "
         "[permutation[selected], permutation[pivot]];\n"
         "    }\n"
         "    const alpha = qr[pivot][pivot];\n"
         "    const beta = alpha <= 0 ? selectedNorm : -selectedNorm;\n"
         "    const leading = alpha - beta;\n"
         "    tau[pivot] = (beta - alpha) / beta;\n"
         "    qr[pivot][pivot] = beta;\n"
         "    for (let row = pivot + 1; row < rows; ++row) qr[row][pivot] /= leading;\n"
         "    for (let column = pivot + 1; column < columns; ++column) {\n"
         "      let projection = qr[pivot][column];\n"
         "      for (let row = pivot + 1; row < rows; ++row) "
         "projection += qr[row][pivot] * qr[row][column];\n"
         "      projection *= tau[pivot];\n"
         "      qr[pivot][column] -= projection;\n"
         "      for (let row = pivot + 1; row < rows; ++row) "
         "qr[row][column] -= qr[row][pivot] * projection;\n"
         "    }\n"
         "    rank = pivot + 1;\n"
         "  }\n"
         "  return { qr, tau, permutation, rank, tolerance };\n"
         "}\n"
         "function __mpf_matlab_apply_cpqr_qt(factor, values) {\n"
         "  const result = values.map((row) => row.slice());\n"
         "  for (let pivot = 0; pivot < factor.rank; ++pivot) {\n"
         "    for (let column = 0; column < result[0].length; ++column) {\n"
         "      let projection = result[pivot][column];\n"
         "      for (let row = pivot + 1; row < result.length; ++row) "
         "projection += factor.qr[row][pivot] * result[row][column];\n"
         "      projection *= factor.tau[pivot];\n"
         "      result[pivot][column] -= projection;\n"
         "      for (let row = pivot + 1; row < result.length; ++row) "
         "result[row][column] -= factor.qr[row][pivot] * projection;\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_basic_least_squares(left, right) {\n"
         "  const factor = __mpf_matlab_cpqr_factor(left);\n"
         "  const transformed = __mpf_matlab_apply_cpqr_qt(factor, right);\n"
         "  const columns = left[0].length; const outputs = right[0].length;\n"
         "  if (factor.rank < Math.min(left.length, columns)) console.warn(\n"
         "    `MPF Matlab matrix is rank deficient to working precision (rank "
         "${factor.rank}, tolerance ${factor.tolerance}); using a basic least-squares "
         "solution`);\n"
         "  const pivoted = Array.from({ length: columns }, () => new Array(outputs).fill(0));\n"
         "  for (let reverse = factor.rank; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let output = 0; output < outputs; ++output) {\n"
         "      let value = transformed[row][output];\n"
         "      for (let inner = row + 1; inner < columns; ++inner) "
         "value -= factor.qr[row][inner] * pivoted[inner][output];\n"
         "      pivoted[row][output] = value / factor.qr[row][row];\n"
         "    }\n"
         "  }\n"
         "  const result = Array.from({ length: columns }, () => new Array(outputs).fill(0));\n"
         "  for (let row = 0; row < columns; ++row) "
         "result[factor.permutation[row]] = pivoted[row];\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_overdetermined_solve(left, right) {\n"
         "  return __mpf_matlab_basic_least_squares(left, right);\n"
         "}\n"
         "function __mpf_matlab_underdetermined_solve(left, right) {\n"
         "  return __mpf_matlab_basic_least_squares(left, right);\n"
         "}\n"
         "function __mpf_matlab_matrix_solve_planned(leftValue, rightValue, solve) {\n"
         "  const left = __mpf_matlab_dense_matrix(leftValue, 'coefficient matrix');\n"
         "  const right = __mpf_matlab_dense_matrix(rightValue, 'right-hand side');\n"
         "  if (right.length !== left.length) "
         "throw new RangeError('MPF Matlab matrix solve shape mismatch');\n"
         "  if (solve === 'structured_real_square' && left.length === left[0].length) "
         "return __mpf_matlab_structured_real_square_solve(left, right);\n"
         "  if (solve === 'overdetermined' && left.length > left[0].length) "
         "return __mpf_matlab_overdetermined_solve(left, right);\n"
         "  if (solve === 'underdetermined' && left.length < left[0].length) "
         "return __mpf_matlab_underdetermined_solve(left, right);\n"
         "  throw new RangeError('MPF Matlab matrix solve disagrees with its static solve "
         "plan');\n"
         "}\n"
         "function __mpf_matlab_mldivide_structured_real_square(left, right) {\n"
         "  return __mpf_matlab_matrix_solve_planned(left, right, 'structured_real_square');\n"
         "}\n"
         "function __mpf_matlab_mldivide_overdetermined(left, right) {\n"
         "  return __mpf_matlab_matrix_solve_planned(left, right, 'overdetermined');\n"
         "}\n"
         "function __mpf_matlab_mldivide_underdetermined(left, right) {\n"
         "  return __mpf_matlab_matrix_solve_planned(left, right, 'underdetermined');\n"
         "}\n"
         "function __mpf_matlab_mrdivide_planned(left, right, solve) {\n"
         "  const normalizedLeft = __mpf_matlab_dense_matrix(left, 'left operand');\n"
         "  const normalizedRight = __mpf_matlab_dense_matrix(right, 'right divisor');\n"
         "  return __mpf_matlab_matrix_transpose(__mpf_matlab_matrix_solve_planned("
         "__mpf_matlab_matrix_transpose(normalizedRight), "
         "__mpf_matlab_matrix_transpose(normalizedLeft), solve));\n"
         "}\n"
         "function __mpf_matlab_mrdivide_structured_real_square(left, right) {\n"
         "  return __mpf_matlab_mrdivide_planned(left, right, 'structured_real_square');\n"
         "}\n"
         "function __mpf_matlab_mrdivide_overdetermined(left, right) {\n"
         "  return __mpf_matlab_mrdivide_planned(left, right, 'overdetermined');\n"
         "}\n"
         "function __mpf_matlab_mrdivide_underdetermined(left, right) {\n"
         "  return __mpf_matlab_mrdivide_planned(left, right, 'underdetermined');\n"
         "}\n";
}

}  // namespace mpf::detail
