#include "matrix_runtime.hpp"

#include <ostream>

namespace mpf::detail {

void emit_javascript_matrix_solve_runtime(std::ostream& output) {
  output
      << "function __mpf_matlab_matrix_one_norm(values) {\n"
         "  let maximum = 0;\n"
         "  for (let column = 0; column < values[0].length; ++column) {\n"
         "    let sum = 0;\n"
         "    for (let row = 0; row < values.length; ++row) {\n"
         "      if (!Number.isFinite(values[row][column])) return Infinity;\n"
         "      sum += Math.abs(values[row][column]);\n"
         "    }\n"
         "    maximum = Math.max(maximum, sum);\n"
         "  }\n"
         "  return maximum;\n"
         "}\n"
         "function __mpf_matlab_lu_factor(coefficients) {\n"
         "  const size = coefficients.length;\n"
         "  const lu = coefficients.map((row) => row.slice());\n"
         "  const swaps = new Array(size);\n"
         "  let singular = false;\n"
         "  for (let pivot = 0; pivot < size; ++pivot) {\n"
         "    let selected = pivot;\n"
         "    for (let row = pivot + 1; row < size; ++row) "
         "if (Math.abs(lu[row][pivot]) > Math.abs(lu[selected][pivot])) selected = row;\n"
         "    swaps[pivot] = selected;\n"
         "    if (selected !== pivot) [lu[pivot], lu[selected]] = [lu[selected], lu[pivot]];\n"
         "    const diagonal = lu[pivot][pivot];\n"
         "    if (diagonal === 0) { singular = true; continue; }\n"
         "    for (let row = pivot + 1; row < size; ++row) {\n"
         "      lu[row][pivot] /= diagonal;\n"
         "      for (let column = pivot + 1; column < size; ++column) "
         "lu[row][column] -= lu[row][pivot] * lu[pivot][column];\n"
         "    }\n"
         "  }\n"
         "  return { lu, swaps, singular };\n"
         "}\n"
         "function __mpf_matlab_lu_apply(factor, values) {\n"
         "  const size = factor.lu.length;\n"
         "  const result = values.map((row) => row.slice());\n"
         "  for (let pivot = 0; pivot < size; ++pivot) {\n"
         "    const selected = factor.swaps[pivot];\n"
         "    if (selected !== pivot) [result[pivot], result[selected]] = "
         "[result[selected], result[pivot]];\n"
         "  }\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let inner = 0; inner < row; ++inner) {\n"
         "      const coefficient = factor.lu[row][inner];\n"
         "      if (coefficient === 0) continue;\n"
         "      for (let column = 0; column < result[0].length; ++column) "
         "result[row][column] -= coefficient * result[inner][column];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let column = 0; column < result[0].length; ++column) {\n"
         "      let value = result[row][column];\n"
         "      for (let inner = row + 1; inner < size; ++inner) {\n"
         "        const coefficient = factor.lu[row][inner];\n"
         "        if (coefficient !== 0) value -= coefficient * result[inner][column];\n"
         "      }\n"
         "      result[row][column] = value / factor.lu[row][row];\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_lu_apply_transpose(factor, values) {\n"
         "  const size = factor.lu.length;\n"
         "  const result = values.map((row) => row.slice());\n"
         "  for (let row = 0; row < size; ++row) {\n"
         "    for (let column = 0; column < result[0].length; ++column) {\n"
         "      let value = result[row][column];\n"
         "      for (let inner = 0; inner < row; ++inner) {\n"
         "        const coefficient = factor.lu[inner][row];\n"
         "        if (coefficient !== 0) value -= coefficient * result[inner][column];\n"
         "      }\n"
         "      result[row][column] = value / factor.lu[row][row];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let inner = row + 1; inner < size; ++inner) {\n"
         "      const coefficient = factor.lu[inner][row];\n"
         "      if (coefficient === 0) continue;\n"
         "      for (let column = 0; column < result[0].length; ++column) "
         "result[row][column] -= coefficient * result[inner][column];\n"
         "    }\n"
         "  }\n"
         "  for (let reverse = size; reverse > 0; --reverse) {\n"
         "    const pivot = reverse - 1; const selected = factor.swaps[pivot];\n"
         "    if (selected !== pivot) [result[pivot], result[selected]] = "
         "[result[selected], result[pivot]];\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_lu_rcond(coefficients, factor) {\n"
         "  if (factor.singular) return 0;\n"
         "  const norm = __mpf_matlab_matrix_one_norm(coefficients);\n"
         "  if (norm === 0 || !Number.isFinite(norm)) return 0;\n"
         "  const size = coefficients.length;\n"
         "  let vector = Array.from({ length: size }, () => [1 / size]);\n"
         "  let inverseNorm = 0;\n"
         "  for (let iteration = 0; iteration < 5; ++iteration) {\n"
         "    const solved = __mpf_matlab_lu_apply(factor, vector);\n"
         "    const estimate = solved.reduce((sum, row) => sum + Math.abs(row[0]), 0);\n"
         "    if (!Number.isFinite(estimate)) return 0;\n"
         "    inverseNorm = Math.max(inverseNorm, estimate);\n"
         "    const signs = solved.map((row) => [row[0] >= 0 ? 1 : -1]);\n"
         "    const transposed = __mpf_matlab_lu_apply_transpose(factor, signs);\n"
         "    if (!transposed.every((row) => Number.isFinite(row[0]))) return 0;\n"
         "    let selected = 0;\n"
         "    for (let row = 1; row < size; ++row) "
         "if (Math.abs(transposed[row][0]) > Math.abs(transposed[selected][0])) selected = row;\n"
         "    let dual = 0;\n"
         "    for (let row = 0; row < size; ++row) dual += transposed[row][0] * vector[row][0];\n"
         "    if (Math.abs(transposed[selected][0]) <= dual) break;\n"
         "    vector = Array.from({ length: size }, (_, row) => [row === selected ? 1 : 0]);\n"
         "  }\n"
         "  const product = norm * inverseNorm;\n"
         "  return product > 0 && Number.isFinite(product) ? Math.min(1, 1 / product) : 0;\n"
         "}\n"
         "function __mpf_matlab_warn_lu_condition(rcond) {\n"
         "  if (rcond === 0) {\n"
         "    console.warn('MPF Matlab matrix is singular to working precision.');\n"
         "  } else if (rcond < Number.EPSILON) {\n"
         "    console.warn(`MPF Matlab matrix is close to singular or badly scaled. "
         "Results may be inaccurate. RCOND = ${rcond}.`);\n"
         "  }\n"
         "}\n"
         "function __mpf_matlab_lu_solve(coefficients, rightHandSide) {\n"
         "  const left = __mpf_matlab_dense_matrix(coefficients, 'coefficient matrix');\n"
         "  const right = __mpf_matlab_dense_matrix(rightHandSide, 'right-hand side');\n"
         "  const size = left.length;\n"
         "  if (left[0].length !== size || right.length !== size) "
         "throw new RangeError('MPF Matlab matrix solve shape mismatch');\n"
         "  const factor = __mpf_matlab_lu_factor(left);\n"
         "  __mpf_matlab_warn_lu_condition(__mpf_matlab_lu_rcond(left, factor));\n"
         "  return __mpf_matlab_lu_apply(factor, right);\n"
         "}\n"
         "function __mpf_matlab_cpqr_factor(values) {\n"
         "  const rows = values.length; const columns = values[0].length;\n"
         "  const pivots = Math.min(rows, columns);\n"
         "  const qr = values.map((row) => row.slice());\n"
         "  const tau = new Array(pivots).fill(0);\n"
         "  const permutation = Array.from({ length: columns }, (_, index) => index);\n"
         "  let scale = 0;\n"
         "  for (let column = 0; column < columns; ++column) {\n"
         "    let norm = 0;\n"
         "    for (let row = 0; row < rows; ++row) norm = Math.hypot(norm, qr[row][column]);\n"
         "    scale = Math.max(scale, norm);\n"
         "  }\n"
         "  const tolerance = Number.EPSILON * Math.max(rows, columns) * scale;\n"
         "  let rank = 0;\n"
         "  for (let pivot = 0; pivot < pivots; ++pivot) {\n"
         "    let selected = pivot; let selectedNorm = -1;\n"
         "    for (let column = pivot; column < columns; ++column) {\n"
         "      let norm = 0;\n"
         "      for (let row = pivot; row < rows; ++row) "
         "norm = Math.hypot(norm, qr[row][column]);\n"
         "      if (norm > selectedNorm) { selected = column; selectedNorm = norm; }\n"
         "    }\n"
         "    if (selectedNorm <= tolerance) break;\n"
         "    if (selected !== pivot) {\n"
         "      for (let row = 0; row < rows; ++row) "
         "[qr[row][pivot], qr[row][selected]] = [qr[row][selected], qr[row][pivot]];\n"
         "      [permutation[pivot], permutation[selected]] = "
         "[permutation[selected], permutation[pivot]];\n"
         "    }\n"
         "    const alpha = qr[pivot][pivot];\n"
         "    const beta = alpha <= 0 ? selectedNorm : -selectedNorm;\n"
         "    const leading = alpha - beta;\n"
         "    tau[pivot] = (beta - alpha) / beta;\n"
         "    qr[pivot][pivot] = beta;\n"
         "    for (let row = pivot + 1; row < rows; ++row) qr[row][pivot] /= leading;\n"
         "    for (let column = pivot + 1; column < columns; ++column) {\n"
         "      let projection = qr[pivot][column];\n"
         "      for (let row = pivot + 1; row < rows; ++row) "
         "projection += qr[row][pivot] * qr[row][column];\n"
         "      projection *= tau[pivot];\n"
         "      qr[pivot][column] -= projection;\n"
         "      for (let row = pivot + 1; row < rows; ++row) "
         "qr[row][column] -= qr[row][pivot] * projection;\n"
         "    }\n"
         "    rank = pivot + 1;\n"
         "  }\n"
         "  return { qr, tau, permutation, rank, tolerance };\n"
         "}\n"
         "function __mpf_matlab_apply_cpqr_qt(factor, values) {\n"
         "  const result = values.map((row) => row.slice());\n"
         "  for (let pivot = 0; pivot < factor.rank; ++pivot) {\n"
         "    for (let column = 0; column < result[0].length; ++column) {\n"
         "      let projection = result[pivot][column];\n"
         "      for (let row = pivot + 1; row < result.length; ++row) "
         "projection += factor.qr[row][pivot] * result[row][column];\n"
         "      projection *= factor.tau[pivot];\n"
         "      result[pivot][column] -= projection;\n"
         "      for (let row = pivot + 1; row < result.length; ++row) "
         "result[row][column] -= factor.qr[row][pivot] * projection;\n"
         "    }\n"
         "  }\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_basic_least_squares(left, right) {\n"
         "  const factor = __mpf_matlab_cpqr_factor(left);\n"
         "  const transformed = __mpf_matlab_apply_cpqr_qt(factor, right);\n"
         "  const columns = left[0].length; const outputs = right[0].length;\n"
         "  if (factor.rank < Math.min(left.length, columns)) console.warn(\n"
         "    `MPF Matlab matrix is rank deficient to working precision (rank "
         "${factor.rank}, tolerance ${factor.tolerance}); using a basic least-squares "
         "solution`);\n"
         "  const pivoted = Array.from({ length: columns }, () => new Array(outputs).fill(0));\n"
         "  for (let reverse = factor.rank; reverse > 0; --reverse) {\n"
         "    const row = reverse - 1;\n"
         "    for (let output = 0; output < outputs; ++output) {\n"
         "      let value = transformed[row][output];\n"
         "      for (let inner = row + 1; inner < columns; ++inner) "
         "value -= factor.qr[row][inner] * pivoted[inner][output];\n"
         "      pivoted[row][output] = value / factor.qr[row][row];\n"
         "    }\n"
         "  }\n"
         "  const result = Array.from({ length: columns }, () => new Array(outputs).fill(0));\n"
         "  for (let row = 0; row < columns; ++row) "
         "result[factor.permutation[row]] = pivoted[row];\n"
         "  return result;\n"
         "}\n"
         "function __mpf_matlab_overdetermined_solve(left, right) {\n"
         "  return __mpf_matlab_basic_least_squares(left, right);\n"
         "}\n"
         "function __mpf_matlab_underdetermined_solve(left, right) {\n"
         "  return __mpf_matlab_basic_least_squares(left, right);\n"
         "}\n"
         "function __mpf_matlab_matrix_solve_planned(leftValue, rightValue, solve) {\n"
         "  const left = __mpf_matlab_dense_matrix(leftValue, 'coefficient matrix');\n"
         "  const right = __mpf_matlab_dense_matrix(rightValue, 'right-hand side');\n"
         "  if (right.length !== left.length) "
         "throw new RangeError('MPF Matlab matrix solve shape mismatch');\n"
         "  if (solve === 'square' && left.length === left[0].length) "
         "return __mpf_matlab_lu_solve(left, right);\n"
         "  if (solve === 'overdetermined' && left.length > left[0].length) "
         "return __mpf_matlab_overdetermined_solve(left, right);\n"
         "  if (solve === 'underdetermined' && left.length < left[0].length) "
         "return __mpf_matlab_underdetermined_solve(left, right);\n"
         "  throw new RangeError('MPF Matlab matrix solve disagrees with its static solve "
         "plan');\n"
         "}\n"
         "function __mpf_matlab_mldivide_square(left, right) {\n"
         "  return __mpf_matlab_matrix_solve_planned(left, right, 'square');\n"
         "}\n"
         "function __mpf_matlab_mldivide_overdetermined(left, right) {\n"
         "  return __mpf_matlab_matrix_solve_planned(left, right, 'overdetermined');\n"
         "}\n"
         "function __mpf_matlab_mldivide_underdetermined(left, right) {\n"
         "  return __mpf_matlab_matrix_solve_planned(left, right, 'underdetermined');\n"
         "}\n"
         "function __mpf_matlab_mrdivide_planned(left, right, solve) {\n"
         "  const normalizedLeft = __mpf_matlab_dense_matrix(left, 'left operand');\n"
         "  const normalizedRight = __mpf_matlab_dense_matrix(right, 'right divisor');\n"
         "  return __mpf_matlab_matrix_transpose(__mpf_matlab_matrix_solve_planned("
         "__mpf_matlab_matrix_transpose(normalizedRight), "
         "__mpf_matlab_matrix_transpose(normalizedLeft), solve));\n"
         "}\n"
         "function __mpf_matlab_mrdivide_square(left, right) {\n"
         "  return __mpf_matlab_mrdivide_planned(left, right, 'square');\n"
         "}\n"
         "function __mpf_matlab_mrdivide_overdetermined(left, right) {\n"
         "  return __mpf_matlab_mrdivide_planned(left, right, 'overdetermined');\n"
         "}\n"
         "function __mpf_matlab_mrdivide_underdetermined(left, right) {\n"
         "  return __mpf_matlab_mrdivide_planned(left, right, 'underdetermined');\n"
         "}\n";
}

}  // namespace mpf::detail
