#include "runtime.hpp"

#include <ostream>

#include "matrix_runtime.hpp"

namespace mpf::detail {
namespace {

class RuntimeEmitter final {
 public:
  explicit RuntimeEmitter(std::ostream& output) : output_(output) {}

  void emit(const javascript::lir::RuntimeFragment fragment) {
    switch (fragment) {
      case javascript::lir::RuntimeFragment::dynamic_values: emit_python_runtime(); break;
      case javascript::lir::RuntimeFragment::character_case:
        emit_fortran_character_runtime();
        break;
      case javascript::lir::RuntimeFragment::arrays: emit_array_runtime(); break;
    }
  }

 private:
  void emit_python_runtime() {
    output_
        << "function __mpf_truthy(value) {\n"
           "  if (Array.isArray(value)) return value.length !== 0;\n"
           "  if (typeof value === \"number\") return value !== 0;\n"
           "  if (typeof value === \"string\") return value.length !== 0;\n"
           "  return value !== null && value !== false;\n"
           "}\n"
           "function __mpf_py_not(value) { return !__mpf_truthy(value); }\n"
           "const __mpf_tuple_tag = Symbol(\"mpf.tuple\");\n"
           "function __mpf_tuple(values) {\n"
           "  Object.defineProperty(values, __mpf_tuple_tag, { value: true });\n"
           "  return values;\n"
           "}\n"
           "function __mpf_sequence_kind(value) {\n"
           "  if (!Array.isArray(value)) return null;\n"
           "  return value[__mpf_tuple_tag] === true ? \"tuple\" : \"list\";\n"
           "}\n"
           "function __mpf_py_equal(left, right) {\n"
           "  const leftNumeric = typeof left === \"number\" || typeof left === \"boolean\";\n"
           "  const rightNumeric = typeof right === \"number\" || typeof right === \"boolean\";\n"
           "  if (leftNumeric && rightNumeric) return Number(left) === Number(right);\n"
           "  const leftKind = __mpf_sequence_kind(left);\n"
           "  const rightKind = __mpf_sequence_kind(right);\n"
           "  if (leftKind !== null || rightKind !== null) {\n"
           "    if (leftKind !== rightKind) return false;\n"
           "    return left.length === right.length && "
           "left.every((value, index) => __mpf_py_equal(value, right[index]));\n"
           "  }\n"
           "  return left === right;\n"
           "}\n"
           "function __mpf_py_is(left, right) { return left === right; }\n"
           "function __mpf_py_contains(container, value) {\n"
           "  if (typeof container === \"string\") {\n"
           "    if (typeof value !== \"string\") throw new TypeError(\"string membership "
           "requires a string\");\n"
           "    return container.includes(value);\n"
           "  }\n"
           "  if (Array.isArray(container)) {\n"
           "    return container.some((element) => __mpf_py_equal(element, value));\n"
           "  }\n"
           "  throw new TypeError(\"MPF membership container is not iterable\");\n"
           "}\n"
           "function __mpf_py_and(left, right) {\n"
           "  const value = left();\n"
           "  return __mpf_truthy(value) ? right() : value;\n"
           "}\n"
           "function __mpf_py_or(left, right) {\n"
           "  const value = left();\n"
           "  return __mpf_truthy(value) ? value : right();\n"
           "}\n"
           "function __mpf_py_float(value) {\n"
           "  if (typeof value === \"number\" || typeof value === \"boolean\") return "
           "Number(value);\n"
           "  if (typeof value !== \"string\") throw new TypeError(\"MPF float argument is not "
           "convertible\");\n"
           "  const text = value.trim().toLowerCase();\n"
           "  if (text === \"\") throw new TypeError(\"MPF float string is empty\");\n"
           "  if (text === \"nan\" || text === \"+nan\" || text === \"-nan\") return Number.NaN;\n"
           "  if (text === \"inf\" || text === \"+inf\" || text === \"infinity\" || "
           "text === \"+infinity\") return Number.POSITIVE_INFINITY;\n"
           "  if (text === \"-inf\" || text === \"-infinity\") return Number.NEGATIVE_INFINITY;\n"
           "  const result = Number(text);\n"
           "  if (Number.isNaN(result)) throw new TypeError(\"MPF float string is invalid\");\n"
           "  return result;\n"
           "}\n";
  }

  void emit_fortran_character_runtime() {
    output_ << "function __mpf_fortran_compare(left, right) {\n"
               "  const width = Math.max(left.length, right.length);\n"
               "  const paddedLeft = left.padEnd(width, \" \");\n"
               "  const paddedRight = right.padEnd(width, \" \");\n"
               "  return paddedLeft < paddedRight ? -1 : paddedLeft > paddedRight ? 1 : 0;\n"
               "}\n";
  }

  void emit_array_runtime() {
    output_
        << "function __mpf_index(values, index, base, allowNegative) {\n"
           "  if (!Number.isSafeInteger(index)) throw new TypeError(\"MPF index must be a safe "
           "integer\");\n"
           "  let normalized = index - base;\n"
           "  if (allowNegative && index < 0) normalized = values.length + index;\n"
           "  if (normalized < 0 || normalized >= values.length) "
           "throw new RangeError(\"MPF index out of bounds\");\n"
           "  return normalized;\n"
           "}\n"
           "const __mpf_shape_tag = Symbol('mpf.shape');\n"
           "function __mpf_checked_shape_size(shape) {\n"
           "  let size = 1;\n"
           "  for (const extent of shape) {\n"
           "    if (!Number.isSafeInteger(extent) || extent < 0 || "
           "(extent !== 0 && size > Number.MAX_SAFE_INTEGER / extent)) "
           "throw new RangeError(\"MPF array shape exceeds safe size limits\");\n"
           "    size *= extent;\n"
           "  }\n"
           "  return size;\n"
           "}\n"
           "function __mpf_record_shape(values, shape) {\n"
           "  if (!Array.isArray(values) || !Array.isArray(shape)) "
           "throw new TypeError(\"MPF shaped value must be an array\");\n"
           "  __mpf_checked_shape_size(shape);\n"
           "  Object.defineProperty(values, __mpf_shape_tag, { value: shape.slice(), "
           "writable: true, configurable: true });\n"
           "  return values;\n"
           "}\n"
           "function __mpf_empty_array(shape) {\n"
           "  if (!Array.isArray(shape) || shape.length < 2 || !shape.includes(0)) "
           "throw new RangeError(\"MPF Matlab empty array shape is invalid\");\n"
           "  return __mpf_build_column_major([], shape);\n"
           "}\n"
           "function __mpf_structural_shape(values, name) {\n"
           "  if (!Array.isArray(values)) return [];\n"
           "  const extent = values.length;\n"
           "  if (extent === 0) return [0];\n"
           "  const childShape = __mpf_structural_shape(values[0], name);\n"
           "  for (let index = 1; index < extent; ++index) {\n"
           "    const actual = __mpf_structural_shape(values[index], name);\n"
           "    if (actual.length !== childShape.length || "
           "actual.some((value, axis) => value !== childShape[axis])) "
           "throw new RangeError(`MPF Matlab ${name} must be rectangular`);\n"
           "  }\n"
           "  return [extent, ...childShape];\n"
           "}\n"
           "function __mpf_shape(values) {\n"
           "  if (Array.isArray(values) && Array.isArray(values[__mpf_shape_tag])) "
           "return values[__mpf_shape_tag].slice();\n"
           "  const shape = [];\n"
           "  let current = values;\n"
           "  while (Array.isArray(current)) {\n"
           "    shape.push(current.length);\n"
           "    current = current.length === 0 ? null : current[0];\n"
           "  }\n"
           "  return shape;\n"
           "}\n"
           "function __mpf_matlab_runtime_shape(values, name) {\n"
           "  if (!Array.isArray(values)) return [];\n"
           "  const structural = __mpf_structural_shape(values, name);\n"
           "  const recorded = values[__mpf_shape_tag];\n"
           "  if (!Array.isArray(recorded)) return structural;\n"
           "  const expectedSize = __mpf_checked_shape_size(recorded);\n"
           "  const actualSize = __mpf_checked_shape_size(structural);\n"
           "  const shared = Math.min(recorded.length, structural.length);\n"
           "  if (expectedSize !== actualSize || structural.length > recorded.length || "
           "Array.from({ length: shared }, (_, axis) => axis).some((axis) => "
           "recorded[axis] !== structural[axis]) || "
           "(expectedSize !== 0 && recorded.length !== structural.length)) "
           "throw new RangeError(`MPF Matlab ${name} shape descriptor is stale`);\n"
           "  return recorded.slice();\n"
           "}\n"
           "function __mpf_matlab_transpose(values) {\n"
           "  if (!Array.isArray(values)) return values;\n"
           "  const shape = __mpf_matlab_runtime_shape(values, 'transpose operand');\n"
           "  if (shape.length === 1) return __mpf_record_shape("
           "values.map((value) => [value]), [shape[0], 1]);\n"
           "  if (shape.length !== 2) throw new RangeError("
           "\"MPF Matlab transpose requires a rectangular rank-2 array\");\n"
           "  const resultShape = [shape[1], shape[0]];\n"
           "  if (__mpf_checked_shape_size(shape) === 0) return __mpf_empty_array(resultShape);\n"
           "  if (!values.every((row) => Array.isArray(row) && "
           "row.length === values[0].length && !row.some(Array.isArray))) "
           "throw new RangeError(\"MPF Matlab transpose requires a rectangular rank-2 "
           "array\");\n"
           "  return __mpf_record_shape(Array.from({ length: values[0].length }, (_, column) => "
           "values.map((row) => row[column])), resultShape);\n"
           "  }\n"
           "function __mpf_matlab_elementwise(left, right, operation, leftShape, rightShape, "
           "resultShape) {\n"
           "  const leftArray = Array.isArray(left);\n"
           "  const rightArray = Array.isArray(right);\n"
           "  if ((leftArray || rightArray) && resultShape !== undefined) {\n"
           "    const size = (shape) => shape.reduce((product, extent) => product * extent, 1);\n"
           "    const leftFlat = leftArray ? __mpf_flatten_column_major(left) : [left];\n"
           "    const rightFlat = rightArray ? __mpf_flatten_column_major(right) : [right];\n"
           "    if (leftFlat.length !== size(leftShape) || rightFlat.length !== size(rightShape)) "
           "throw new RangeError(\"MPF Matlab broadcast operand shape mismatch\");\n"
           "    for (let axis = 0; axis < resultShape.length; ++axis) {\n"
           "      const l = leftShape[axis]; const r = rightShape[axis];\n"
           "      if (l !== r && l !== 1 && r !== 1) throw new RangeError(\"MPF Matlab "
           "broadcast sizes are incompatible\");\n"
           "    }\n"
           "    const leftStrides = []; const rightStrides = [];\n"
           "    let leftStride = 1; let rightStride = 1;\n"
           "    for (let axis = 0; axis < resultShape.length; ++axis) {\n"
           "      leftStrides.push(leftStride); rightStrides.push(rightStride);\n"
           "      leftStride *= leftShape[axis]; rightStride *= rightShape[axis];\n"
           "    }\n"
           "    const resultSize = size(resultShape);\n"
           "    const flattened = new Array(resultSize);\n"
           "    for (let linear = 0; linear < resultSize; ++linear) {\n"
           "      let remainder = linear; let leftLinear = 0; let rightLinear = 0;\n"
           "      for (let axis = 0; axis < resultShape.length; ++axis) {\n"
           "        const coordinate = remainder % resultShape[axis];\n"
           "        remainder = Math.floor(remainder / resultShape[axis]);\n"
           "        if (leftShape[axis] !== 1) leftLinear += coordinate * leftStrides[axis];\n"
           "        if (rightShape[axis] !== 1) rightLinear += coordinate * "
           "rightStrides[axis];\n"
           "      }\n"
           "      flattened[linear] = operation(leftFlat[leftLinear], rightFlat[rightLinear]);\n"
           "    }\n"
           "    return __mpf_build_column_major(flattened, resultShape);\n"
           "  }\n"
           "  if (leftArray && rightArray) {\n"
           "    if (left.length !== right.length) throw new RangeError(\"MPF Matlab "
           "element-wise shape mismatch\");\n"
           "    return left.map((value, index) => "
           "__mpf_matlab_elementwise(value, right[index], operation));\n"
           "  }\n"
           "  if (leftArray) return left.map((value) => "
           "__mpf_matlab_elementwise(value, right, operation));\n"
           "  if (rightArray) return right.map((value) => "
           "__mpf_matlab_elementwise(left, value, operation));\n"
           "  return operation(left, right);\n"
           "}\n"
           "function __mpf_matlab_elementwise_runtime(left, right, operation) {\n"
           "  let leftShape = __mpf_matlab_runtime_shape(left, 'left broadcast operand');\n"
           "  let rightShape = __mpf_matlab_runtime_shape(right, 'right broadcast operand');\n"
           "  if (leftShape.length === 1 && rightShape.length >= 2) leftShape = [1, "
           "...leftShape];\n"
           "  if (rightShape.length === 1 && leftShape.length >= 2) rightShape = [1, "
           "...rightShape];\n"
           "  const rank = Math.max(leftShape.length, rightShape.length);\n"
           "  while (leftShape.length < rank) leftShape.push(1);\n"
           "  while (rightShape.length < rank) rightShape.push(1);\n"
           "  const resultShape = new Array(rank);\n"
           "  for (let axis = 0; axis < rank; ++axis) {\n"
           "    const leftExtent = leftShape[axis]; const rightExtent = rightShape[axis];\n"
           "    if (leftExtent !== rightExtent && leftExtent !== 1 && rightExtent !== 1) "
           "throw new RangeError('MPF Matlab broadcast sizes are incompatible');\n"
           "    resultShape[axis] = leftExtent === 1 ? rightExtent : leftExtent;\n"
           "  }\n"
           "  if (rank === 0) return operation(left, right);\n"
           "  return __mpf_matlab_elementwise(left, right, operation, leftShape, rightShape, "
           "resultShape);\n"
           "}\n"
           "function __mpf_matlab_add(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a + b, ...shapes); }\n"
           "function __mpf_matlab_subtract(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a - b, ...shapes); }\n"
           "function __mpf_matlab_multiply(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a * b, ...shapes); }\n"
           "function __mpf_matlab_divide(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a / b, ...shapes); }\n"
           "function __mpf_matlab_left_divide(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => b / a, ...shapes); }\n"
           "function __mpf_matlab_power(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a ** b, ...shapes); }\n"
           "function __mpf_matlab_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a === b, ...shapes); }\n"
           "function __mpf_matlab_not_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a !== b, ...shapes); }\n"
           "function __mpf_matlab_less(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a < b, ...shapes); }\n"
           "function __mpf_matlab_less_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a <= b, ...shapes); }\n"
           "function __mpf_matlab_greater(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a > b, ...shapes); }\n"
           "function __mpf_matlab_greater_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a >= b, ...shapes); }\n"
           "function __mpf_matlab_add_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a + b); }\n"
           "function __mpf_matlab_subtract_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a - b); }\n"
           "function __mpf_matlab_multiply_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a * b); }\n"
           "function __mpf_matlab_divide_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a / b); }\n"
           "function __mpf_matlab_left_divide_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => b / a); }\n"
           "function __mpf_matlab_power_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a ** b); }\n"
           "function __mpf_matlab_equal_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a === b); }\n"
           "function __mpf_matlab_not_equal_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a !== b); }\n"
           "function __mpf_matlab_less_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a < b); }\n"
           "function __mpf_matlab_less_equal_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a <= b); }\n"
           "function __mpf_matlab_greater_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a > b); }\n"
           "function __mpf_matlab_greater_equal_runtime(left, right) { return "
           "__mpf_matlab_elementwise_runtime(left, right, (a, b) => a >= b); }\n"
           "function __mpf_matlab_mtimes(left, right) {\n"
           "  if (!Array.isArray(left) || !Array.isArray(right)) return "
           "__mpf_matlab_multiply(left, right);\n"
           "  if (left.length === 0 || right.length === 0 || "
           "!left.every(Array.isArray) || !right.every(Array.isArray)) "
           "throw new RangeError(\"MPF Matlab matrix multiplication requires non-empty "
           "rank-2 arrays\");\n"
           "  const leftColumns = left[0].length;\n"
           "  const rightColumns = right[0].length;\n"
           "  if (!left.every((row) => row.length === leftColumns) || "
           "!right.every((row) => row.length === rightColumns)) "
           "throw new RangeError(\"MPF Matlab matrix must be rectangular\");\n"
           "  if (leftColumns !== right.length) throw new RangeError(\"MPF Matlab matrix "
           "multiplication shape mismatch\");\n"
           "  return left.map((row) => Array.from({ length: rightColumns }, (_, column) => "
           "row.reduce((sum, value, inner) => sum + value * right[inner][column], 0)));\n"
           "}\n"
           "function __mpf_matlab_dense_matrix(values, name) {\n"
           "  if (!Array.isArray(values) || values.length === 0) throw new RangeError("
           "`MPF Matlab ${name} must be a non-empty matrix`);\n"
           "  if (values.every((value) => !Array.isArray(value))) values = [values];\n"
           "  if (!values.every(Array.isArray)) throw new RangeError("
           "`MPF Matlab ${name} must be a rectangular rank-2 matrix`);\n"
           "  const columns = values[0].length;\n"
           "  if (columns === 0 || !values.every((row) => row.length === columns)) "
           "throw new RangeError(`MPF Matlab ${name} must be a non-empty rectangular "
           "matrix`);\n"
           "  return values.map((row) => row.map((value) => {\n"
           "    if (typeof value !== 'number' || !Number.isFinite(value)) "
           "throw new TypeError(`MPF Matlab ${name} requires finite real values`);\n"
           "    return value;\n"
           "  }));\n"
           "}\n"
           "function __mpf_matlab_matrix_transpose(values) {\n"
           "  return Array.from({ length: values[0].length }, (_, column) => "
           "values.map((row) => row[column]));\n"
           "}\n"
           "function __mpf_matlab_identity(size) {\n"
           "  return Array.from({ length: size }, (_, row) => "
           "Array.from({ length: size }, (_, column) => row === column ? 1 : 0));\n"
           "}\n"
           "function __mpf_matlab_lu_solve(coefficients, rightHandSide) {\n"
           "  const left = __mpf_matlab_dense_matrix(coefficients, 'coefficient matrix');\n"
           "  const right = __mpf_matlab_dense_matrix(rightHandSide, 'right-hand side');\n"
           "  const size = left.length;\n"
           "  if (left[0].length !== size || right.length !== size) "
           "throw new RangeError('MPF Matlab matrix solve shape mismatch');\n"
           "  let maximum = 0;\n"
           "  for (const row of left) for (const value of row) "
           "maximum = Math.max(maximum, Math.abs(value));\n"
           "  const tolerance = Number.EPSILON * Math.max(1, size) * maximum;\n"
           "  for (let pivot = 0; pivot < size; ++pivot) {\n"
           "    let selected = pivot;\n"
           "    for (let row = pivot + 1; row < size; ++row) "
           "if (Math.abs(left[row][pivot]) > Math.abs(left[selected][pivot])) selected = row;\n"
           "    if (Math.abs(left[selected][pivot]) <= tolerance) "
           "throw new RangeError('MPF Matlab matrix is singular to working precision');\n"
           "    if (selected !== pivot) { [left[pivot], left[selected]] = "
           "[left[selected], left[pivot]]; [right[pivot], right[selected]] = "
           "[right[selected], right[pivot]]; }\n"
           "    for (let row = pivot + 1; row < size; ++row) {\n"
           "      const factor = left[row][pivot] / left[pivot][pivot];\n"
           "      left[row][pivot] = 0;\n"
           "      for (let column = pivot + 1; column < size; ++column) "
           "left[row][column] -= factor * left[pivot][column];\n"
           "      for (let column = 0; column < right[0].length; ++column) "
           "right[row][column] -= factor * right[pivot][column];\n"
           "    }\n"
           "  }\n"
           "  const result = Array.from({ length: size }, () => "
           "new Array(right[0].length).fill(0));\n"
           "  for (let row = size - 1; row >= 0; --row) {\n"
           "    for (let column = 0; column < right[0].length; ++column) {\n"
           "      let value = right[row][column];\n"
           "      for (let inner = row + 1; inner < size; ++inner) "
           "value -= left[row][inner] * result[inner][column];\n"
           "      result[row][column] = value / left[row][row];\n"
           "    }\n"
           "  }\n"
           "  return result;\n"
           "}\n";
    emit_javascript_matrix_solve_runtime(output_);
    output_
        << "function __mpf_matlab_mpower(values, exponent) {\n"
           "  let factor = __mpf_matlab_dense_matrix(values, 'matrix power base');\n"
           "  if (factor.length !== factor[0].length) "
           "throw new RangeError('MPF Matlab matrix power requires a square matrix');\n"
           "  if (!Number.isSafeInteger(exponent)) throw new RangeError("
           "'MPF Matlab matrix power currently requires a safe integer exponent');\n"
           "  let result = __mpf_matlab_identity(factor.length);\n"
           "  if (exponent < 0) { factor = __mpf_matlab_lu_solve(factor, result); "
           "exponent = -exponent; }\n"
           "  while (exponent > 0) {\n"
           "    if (exponent % 2 === 1) result = __mpf_matlab_mtimes(result, factor);\n"
           "    exponent = Math.floor(exponent / 2);\n"
           "    if (exponent > 0) factor = __mpf_matlab_mtimes(factor, factor);\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "function __mpf_column_major_coordinates(linear, shape) {\n"
           "  const coordinates = [];\n"
           "  for (const extent of shape) { coordinates.push(linear % extent); linear = "
           "Math.floor(linear / extent); }\n"
           "  return coordinates;\n"
           "}\n"
           "function __mpf_at(values, coordinates) {\n"
           "  let result = values;\n"
           "  for (const coordinate of coordinates) result = result[coordinate];\n"
           "  return result;\n"
           "}\n"
           "function __mpf_set_at(values, coordinates, value) {\n"
           "  let target = values;\n"
           "  for (let dimension = 0; dimension + 1 < coordinates.length; ++dimension) "
           "target = target[coordinates[dimension]];\n"
           "  target[coordinates[coordinates.length - 1]] = value;\n"
           "}\n"
           "function __mpf_set_linear_column_major(values, linear, shape, value) {\n"
           "  let target = values;\n"
           "  for (let axis = 0; axis + 1 < shape.length; ++axis) {\n"
           "    const coordinate = linear % shape[axis];\n"
           "    linear = Math.floor(linear / shape[axis]);\n"
           "    target = target[coordinate];\n"
           "  }\n"
           "  target[linear % shape[shape.length - 1]] = value;\n"
           "}\n"
           "function __mpf_flatten_column_major(values) {\n"
           "  const shape = __mpf_shape(values);\n"
           "  const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "  if (shape.length === 1) return values.slice();\n"
           "  const flattened = new Array(size);\n"
           "  const coordinates = new Array(shape.length).fill(0);\n"
           "  for (let linear = 0; linear < size; ++linear) {\n"
           "    flattened[linear] = __mpf_at(values, coordinates);\n"
           "    for (let axis = 0; axis < shape.length; ++axis) {\n"
           "      if (++coordinates[axis] < shape[axis]) break;\n"
           "      coordinates[axis] = 0;\n"
           "    }\n"
           "  }\n"
           "  return flattened;\n"
           "}\n"
           "function __mpf_build_column_major(flattened, shape) {\n"
           "  const size = __mpf_checked_shape_size(shape);\n"
           "  if (!Array.isArray(flattened) || flattened.length !== size) "
           "throw new RangeError(\"MPF array data does not match its shape\");\n"
           "  const strides = new Array(shape.length);\n"
           "  let stride = 1;\n"
           "  for (let axis = 0; axis < shape.length; ++axis) { "
           "strides[axis] = stride; stride *= shape[axis]; }\n"
           "  const build = (dimension, linear) => {\n"
           "    if (dimension === shape.length) return flattened[linear];\n"
           "    return Array.from({ length: shape[dimension] }, (_, coordinate) => "
           "build(dimension + 1, linear + coordinate * strides[dimension]));\n"
           "  };\n"
           "  const result = build(0, 0);\n"
           "  return Array.isArray(result) ? __mpf_record_shape(result, shape) : result;\n"
           "}\n"
           "function __mpf_resolve_extent(value, extent) {\n"
           "  return typeof value === 'function' ? value(extent) : value;\n"
           "}\n"
           "function __mpf_get(values, indices, base, allowNegative, columnMajor) {\n"
           "  if (columnMajor && indices.length === 1 && Array.isArray(values[0])) {\n"
           "    const shape = __mpf_shape(values);\n"
           "    const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "    const linear = __mpf_index({ length: size }, "
           "__mpf_resolve_extent(indices[0], size), base, false);\n"
           "    return __mpf_at(values, __mpf_column_major_coordinates(linear, shape));\n"
           "  }\n"
           "  let result = values;\n"
           "  for (const index of indices) {\n"
           "    const resolved = __mpf_resolve_extent(index, result.length);\n"
           "    result = result[__mpf_index(result, resolved, base, allowNegative)];\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "function __mpf_slice_indices(length, selector, base, allowNegative) {\n"
           "  const requireInteger = (value) => {\n"
           "    if (value !== null && !Number.isSafeInteger(value)) "
           "throw new TypeError(\"MPF slice bounds and step must be safe integers\");\n"
           "  };\n"
           "  requireInteger(selector.start);\n"
           "  requireInteger(selector.stop);\n"
           "  requireInteger(selector.step);\n"
           "  const step = selector.step ?? 1;\n"
           "  if (step === 0) throw new RangeError(\"MPF slice step cannot be zero\");\n"
           "  const result = [];\n"
           "  if (!selector.inclusive) {\n"
           "    let start = selector.start ?? (step > 0 ? 0 : length - 1);\n"
           "    let stop = selector.stop ?? (step > 0 ? length : -1);\n"
           "    if (selector.start !== null && start < 0) start += length;\n"
           "    if (selector.stop !== null && stop < 0) stop += length;\n"
           "    if (step > 0) {\n"
           "      start = Math.max(0, Math.min(start, length));\n"
           "      stop = Math.max(0, Math.min(stop, length));\n"
           "      for (let position = start; position < stop; position += step) "
           "result.push(position);\n"
           "    } else {\n"
           "      start = Math.max(-1, Math.min(start, length - 1));\n"
           "      stop = Math.max(-1, Math.min(stop, length - 1));\n"
           "      for (let position = start; position > stop; position += step) "
           "result.push(position);\n"
           "    }\n"
           "    return result;\n"
           "  }\n"
           "  const start = selector.start ?? (step > 0 ? base : base + length - 1);\n"
           "  const stop = selector.stop ?? (step > 0 ? base + length - 1 : base);\n"
           "  if (step > 0) {\n"
           "    for (let position = start; position <= stop; position += step) "
           "result.push(__mpf_index({ length }, position, base, allowNegative));\n"
           "  } else {\n"
           "    for (let position = start; position >= stop; position += step) "
           "result.push(__mpf_index({ length }, position, base, allowNegative));\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "function __mpf_selector_indices(length, selector, base, allowNegative) {\n"
           "  selector = __mpf_resolve_extent(selector, length);\n"
           "  if (selector.kind === 'empty') return [];\n"
           "  if (selector.kind === 'slice') "
           "return __mpf_slice_indices(length, selector, base, allowNegative);\n"
           "  const flattened = Array.isArray(selector.value) "
           "? __mpf_flatten_column_major(selector.value) : [selector.value];\n"
           "  if (selector.kind === 'numeric') {\n"
           "    if (!flattened.every((value) => Number.isSafeInteger(value))) "
           "throw new TypeError(\"MPF numeric selector requires safe integer values\");\n"
           "    return flattened.map((value) => "
           "__mpf_index({ length }, value, base, allowNegative));\n"
           "  }\n"
           "  if (selector.kind === 'logical') {\n"
           "    if (flattened.length !== length || "
           "!flattened.every((value) => typeof value === 'boolean')) "
           "throw new RangeError(\"MPF Matlab logical selector shape or type mismatch\");\n"
           "    const result = [];\n"
           "    flattened.forEach((value, index) => { if (value) result.push(index); });\n"
           "    return result;\n"
           "  }\n"
           "  return [__mpf_index({ length }, selector.value, base, allowNegative)];\n"
           "}\n"
           "function __mpf_growth_extent(length, selector, base) {\n"
           "  if (selector.kind === 'empty' || selector.kind === 'logical') {\n"
           "    __mpf_selector_indices(length, selector, base, false); return length;\n"
           "  }\n"
           "  let candidates;\n"
           "  if (selector.kind === 'slice') {\n"
           "    const step = selector.step ?? 1;\n"
           "    if (!Number.isSafeInteger(step) || step === 0) "
           "throw new RangeError(\"MPF Matlab growth slice step is invalid\");\n"
           "    candidates = [selector.start, selector.stop].filter((value) => value !== null);\n"
           "    if (candidates.length === 0) return length;\n"
           "  } else {\n"
           "    candidates = selector.kind === 'numeric' && Array.isArray(selector.value) "
           "? __mpf_flatten_column_major(selector.value) : [selector.value];\n"
           "  }\n"
           "  let required = length;\n"
           "  for (const candidate of candidates) {\n"
           "    if (!Number.isSafeInteger(candidate) || candidate < base) "
           "throw new RangeError(\"MPF Matlab growth selector is out of bounds\");\n"
           "    required = Math.max(required, candidate - base + 1);\n"
           "  }\n"
           "  return required;\n"
           "}\n"
           "function __mpf_resize_nested(values, shape, defaultValue, dimension = 0) {\n"
           "  const make = (axis) => axis === shape.length ? defaultValue : "
           "Array.from({ length: shape[axis] }, () => make(axis + 1));\n"
           "  while (values.length < shape[dimension]) values.push(make(dimension + 1));\n"
           "  if (dimension + 1 < shape.length) for (const child of values) {\n"
           "    if (!Array.isArray(child)) throw new RangeError(\"MPF Matlab array rank "
           "mismatch\");\n"
           "    __mpf_resize_nested(child, shape, defaultValue, dimension + 1);\n"
           "  }\n"
           "}\n"
           "function __mpf_grow(values, selectors, replacement, base, allowNegative, "
           "linear, defaultValue, resultShape) {\n"
           "  const shape = __mpf_shape(values);\n"
           "  if (shape.length === 0) throw new RangeError(\"MPF Matlab growth requires an "
           "array\");\n"
           "  const size = __mpf_checked_shape_size(shape);\n"
           "  const resolved = selectors.map((selector, axis) => "
           "__mpf_resolve_extent(selector, linear ? size : shape[axis]));\n"
           "  const grown = shape.slice();\n"
           "  if (linear) {\n"
           "    const required = __mpf_growth_extent(size, resolved[0], base);\n"
           "    if (shape.length === 1) grown[0] = required;\n"
           "    else if (shape.length === 2 && shape[0] === 0 && shape[1] === 0) "
           "{ grown[0] = 1; grown[1] = required; }\n"
           "    else if (shape.length === 2 && shape[0] === 1) grown[1] = required;\n"
           "    else if (shape.length === 2 && shape[1] === 1) grown[0] = required;\n"
           "    else {\n"
           "      const leading = __mpf_checked_shape_size(shape.slice(0, -1));\n"
           "      if (leading === 0) throw new RangeError(\"MPF Matlab linear growth shape is "
           "invalid\");\n"
           "      grown[grown.length - 1] = Math.max(grown[grown.length - 1], "
           "Math.ceil(required / leading));\n"
           "    }\n"
           "  } else {\n"
           "    resolved.forEach((selector, axis) => { "
           "grown[axis] = __mpf_growth_extent(shape[axis], selector, base); });\n"
           "  }\n"
           "  __mpf_resize_nested(values, grown, defaultValue);\n"
           "  if (linear) {\n"
           "    const grownSize = __mpf_checked_shape_size(grown);\n"
           "    const indices = __mpf_selector_indices(grownSize, resolved[0], base, "
           "allowNegative);\n"
           "    const replacements = Array.isArray(replacement) "
           "? __mpf_flatten_column_major(replacement) : replacement;\n"
           "    if (Array.isArray(replacements) && replacements.length !== indices.length) "
           "throw new RangeError(\"MPF Matlab growth replacement size mismatch\");\n"
           "    indices.forEach((index, position) => __mpf_set_linear_column_major(values, index, "
           "grown, Array.isArray(replacements) ? replacements[position] : replacements));\n"
           "  } else {\n"
           "    __mpf_set_section(values, resolved, replacement, base, allowNegative, true, "
           "false);\n"
           "  }\n"
           "  if (resultShape !== undefined && (grown.length !== resultShape.length || "
           "grown.some((extent, axis) => extent !== resultShape[axis]))) "
           "throw new RangeError(\"MPF Matlab growth result shape disagrees with lowering\");\n"
           "  __mpf_record_shape(values, resultShape ?? grown);\n"
           "}\n"
           "function __mpf_erase_axis(values, axis, indices, dimension = 0) {\n"
           "  if (dimension === axis) {\n"
           "    for (const index of indices) values.splice(index, 1); return;\n"
           "  }\n"
           "  for (const child of values) __mpf_erase_axis(child, axis, indices, dimension + 1);\n"
           "}\n"
           "function __mpf_erase(values, selectors, base, allowNegative, linear, axis, "
           "resultShape) {\n"
           "  const shape = __mpf_shape(values);\n"
           "  if (axis < 0 || axis >= shape.length) "
           "throw new RangeError(\"MPF Matlab deletion axis is invalid\");\n"
           "  const extent = linear ? __mpf_checked_shape_size(shape) "
           ": shape[axis];\n"
           "  const selector = __mpf_resolve_extent(selectors[linear ? 0 : axis], extent);\n"
           "  const indices = [...new Set(__mpf_selector_indices(extent, selector, base, "
           "allowNegative))].sort((left, right) => right - left);\n"
           "  __mpf_erase_axis(values, axis, indices);\n"
           "  const derived = shape.slice(); derived[axis] -= indices.length;\n"
           "  if (resultShape !== undefined && (derived.length !== resultShape.length || "
           "derived.some((extent, position) => extent !== resultShape[position]))) "
           "throw new RangeError(\"MPF Matlab deletion result shape disagrees with lowering\");\n"
           "  __mpf_record_shape(values, resultShape ?? derived);\n"
           "}\n"
           "function __mpf_section(values, selectors, base, allowNegative, columnMajor, "
           "resultShape) {\n"
           "  if (columnMajor && selectors.length === 1 && Array.isArray(values[0])) {\n"
           "    const flattened = __mpf_flatten_column_major(values);\n"
           "    const result = __mpf_selector_indices(flattened.length, selectors[0], base, "
           "allowNegative).map((index) => flattened[index]);\n"
           "    return resultShape === undefined ? result : __mpf_record_shape(result, "
           "resultShape);\n"
           "  }\n"
           "  const visit = (value, dimension) => {\n"
           "    if (dimension === selectors.length) return value;\n"
           "    const selector = __mpf_resolve_extent(selectors[dimension], value.length);\n"
           "    if (selector.kind === 'scalar') return visit(value[__mpf_index("
           "value, selector.value, base, allowNegative)], dimension + 1);\n"
           "    return __mpf_selector_indices(value.length, selector, base, allowNegative)"
           ".map((index) => visit(value[index], dimension + 1));\n"
           "  };\n"
           "  const result = visit(values, 0);\n"
           "  return resultShape === undefined || !Array.isArray(result) ? result : "
           "__mpf_record_shape(result, resultShape);\n"
           "}\n"
           "function __mpf_set(values, indices, value, base, allowNegative, columnMajor) {\n"
           "  if (columnMajor && indices.length === 1 && Array.isArray(values[0])) {\n"
           "    const shape = __mpf_shape(values);\n"
           "    const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "    const linear = __mpf_index({ length: size }, "
           "__mpf_resolve_extent(indices[0], size), base, false);\n"
           "    __mpf_set_linear_column_major(values, linear, shape, value);\n"
           "    return;\n"
           "  }\n"
           "  let target = values;\n"
           "  for (let position = 0; position + 1 < indices.length; ++position) {\n"
           "    const resolved = __mpf_resolve_extent(indices[position], target.length);\n"
           "    target = target[__mpf_index(target, resolved, base, allowNegative)];\n"
           "  }\n"
           "  const last = __mpf_resolve_extent(indices[indices.length - 1], target.length);\n"
           "  target[__mpf_index(target, last, base, allowNegative)] = "
           "value;\n"
           "}\n"
           "function __mpf_python_slice_window(length, selector) {\n"
           "  let start = selector.start ?? 0;\n"
           "  let stop = selector.stop ?? length;\n"
           "  if (start < 0) start += length;\n"
           "  if (stop < 0) stop += length;\n"
           "  start = Math.max(0, Math.min(start, length));\n"
           "  stop = Math.max(0, Math.min(stop, length));\n"
           "  return [start, Math.max(start, stop)];\n"
           "}\n"
           "function __mpf_set_section(values, selectors, replacement, base, allowNegative, "
           "columnMajor, pythonResize) {\n"
           "  if (pythonResize && selectors.length === 1 && selectors[0].kind === 'slice') {\n"
           "    if (!Array.isArray(replacement)) "
           "throw new TypeError(\"MPF Python slice replacement must be a list\");\n"
           "    const selector = selectors[0];\n"
           "    const step = selector.step ?? 1;\n"
           "    if (step === 1) {\n"
           "      const [start, stop] = __mpf_python_slice_window(values.length, selector);\n"
           "      values.splice(start, stop - start, ...replacement);\n"
           "      return;\n"
           "    }\n"
           "    const indices = __mpf_slice_indices(values.length, selector, base, "
           "allowNegative);\n"
           "    if (indices.length !== replacement.length) "
           "throw new RangeError(\"MPF extended slice replacement size mismatch\");\n"
           "    indices.forEach((index, position) => { values[index] = replacement[position]; });\n"
           "    return;\n"
           "  }\n"
           "  if (columnMajor && selectors.length === 1 && Array.isArray(values[0])) {\n"
           "    const selector = selectors[0];\n"
           "    const shape = __mpf_shape(values);\n"
           "    const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "    const indices = __mpf_selector_indices(size, selector, base, allowNegative);\n"
           "    const replacements = Array.isArray(replacement) ? "
           "__mpf_flatten_column_major(replacement) : replacement;\n"
           "    if (Array.isArray(replacements) && replacements.length !== indices.length) "
           "throw new RangeError(\"MPF linear section replacement size mismatch\");\n"
           "    indices.forEach((linear, position) => {\n"
           "      __mpf_set_linear_column_major(values, linear, shape, "
           "Array.isArray(replacements) ? replacements[position] : replacements);\n"
           "    });\n"
           "    return;\n"
           "  }\n"
           "  const scalar = (value) => {\n"
           "    let result = value;\n"
           "    while (columnMajor && Array.isArray(result) && result.length === 1) result = "
           "result[0];\n"
           "    return result;\n"
           "  };\n"
           "  const assign = (target, dimension, source) => {\n"
           "    const selector = __mpf_resolve_extent(selectors[dimension], target.length);\n"
           "    const last = dimension + 1 === selectors.length;\n"
           "    if (selector.kind !== 'scalar') {\n"
           "      const indices = __mpf_selector_indices(target.length, selector, base, "
           "allowNegative);\n"
           "      if (Array.isArray(source) && source.length !== indices.length) "
           "throw new RangeError(\"MPF section replacement size mismatch\");\n"
           "      indices.forEach((index, position) => {\n"
           "        const value = Array.isArray(source) ? source[position] : source;\n"
           "        if (last) target[index] = scalar(value); else assign(target[index], dimension "
           "+ 1, value);\n"
           "      });\n"
           "      return;\n"
           "    }\n"
           "    const index = __mpf_index(target, selector.value, base, allowNegative);\n"
           "    if (last) target[index] = scalar(source); else assign(target[index], dimension + "
           "1, source);\n"
           "  };\n"
           "  assign(values, 0, replacement);\n"
           "}\n"
           "function __mpf_sum(values) {\n"
           "  return values.reduce((total, value) => total + "
           "(Array.isArray(value) ? __mpf_sum(value) : value), 0);\n"
           "}\n"
           "function __mpf_numel(values) {\n"
           "  return values.reduce((total, value) => total + "
           "(Array.isArray(value) ? __mpf_numel(value) : 1), 0);\n"
           "}\n"
           "function __mpf_length(values) {\n"
           "  return Math.max(...__mpf_shape(values));\n"
           "}\n"
           "function __mpf_reshape(values, shape) {\n"
           "  if (shape.length === 0 || shape.some((extent) => !Number.isSafeInteger(extent) || "
           "extent < 0)) throw new RangeError(\"MPF RESHAPE shape is invalid\");\n"
           "  const flattened = __mpf_flatten_column_major(values);\n"
           "  const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "  if (flattened.length !== size) throw new RangeError(\"MPF RESHAPE size mismatch\");\n"
           "  return __mpf_build_column_major(flattened, shape);\n"
           "}\n";
  }

  std::ostream& output_;
};

}  // namespace

void emit_javascript_runtime_fragment(std::ostream& output,
                                      const javascript::lir::RuntimeFragment fragment) {
  RuntimeEmitter(output).emit(fragment);
}

}  // namespace mpf::detail
