#include "runtime.hpp"

#include <ostream>

namespace mpf::detail {
namespace {

class RuntimeEmitter final {
 public:
  explicit RuntimeEmitter(std::ostream& output) : output_(output) {}

  void emit(const javascript::lir::RuntimeFragment fragment) {
    switch (fragment) {
      case javascript::lir::RuntimeFragment::dynamic_values: emit_python_runtime(); break;
      case javascript::lir::RuntimeFragment::character_case:
        emit_fortran_character_runtime();
        break;
      case javascript::lir::RuntimeFragment::arrays: emit_array_runtime(); break;
    }
  }

 private:
  void emit_python_runtime() {
    output_
        << "function __mpf_truthy(value) {\n"
           "  if (Array.isArray(value)) return value.length !== 0;\n"
           "  if (typeof value === \"number\") return value !== 0;\n"
           "  if (typeof value === \"string\") return value.length !== 0;\n"
           "  return value !== null && value !== false;\n"
           "}\n"
           "function __mpf_py_not(value) { return !__mpf_truthy(value); }\n"
           "const __mpf_tuple_tag = Symbol(\"mpf.tuple\");\n"
           "function __mpf_tuple(values) {\n"
           "  Object.defineProperty(values, __mpf_tuple_tag, { value: true });\n"
           "  return values;\n"
           "}\n"
           "function __mpf_sequence_kind(value) {\n"
           "  if (!Array.isArray(value)) return null;\n"
           "  return value[__mpf_tuple_tag] === true ? \"tuple\" : \"list\";\n"
           "}\n"
           "function __mpf_py_equal(left, right) {\n"
           "  const leftNumeric = typeof left === \"number\" || typeof left === \"boolean\";\n"
           "  const rightNumeric = typeof right === \"number\" || typeof right === \"boolean\";\n"
           "  if (leftNumeric && rightNumeric) return Number(left) === Number(right);\n"
           "  const leftKind = __mpf_sequence_kind(left);\n"
           "  const rightKind = __mpf_sequence_kind(right);\n"
           "  if (leftKind !== null || rightKind !== null) {\n"
           "    if (leftKind !== rightKind) return false;\n"
           "    return left.length === right.length && "
           "left.every((value, index) => __mpf_py_equal(value, right[index]));\n"
           "  }\n"
           "  return left === right;\n"
           "}\n"
           "function __mpf_py_is(left, right) { return left === right; }\n"
           "function __mpf_py_contains(container, value) {\n"
           "  if (typeof container === \"string\") {\n"
           "    if (typeof value !== \"string\") throw new TypeError(\"string membership "
           "requires a string\");\n"
           "    return container.includes(value);\n"
           "  }\n"
           "  if (Array.isArray(container)) {\n"
           "    return container.some((element) => __mpf_py_equal(element, value));\n"
           "  }\n"
           "  throw new TypeError(\"MPF membership container is not iterable\");\n"
           "}\n"
           "function __mpf_py_and(left, right) {\n"
           "  const value = left();\n"
           "  return __mpf_truthy(value) ? right() : value;\n"
           "}\n"
           "function __mpf_py_or(left, right) {\n"
           "  const value = left();\n"
           "  return __mpf_truthy(value) ? value : right();\n"
           "}\n"
           "function __mpf_py_float(value) {\n"
           "  if (typeof value === \"number\" || typeof value === \"boolean\") return "
           "Number(value);\n"
           "  if (typeof value !== \"string\") throw new TypeError(\"MPF float argument is not "
           "convertible\");\n"
           "  const text = value.trim().toLowerCase();\n"
           "  if (text === \"\") throw new TypeError(\"MPF float string is empty\");\n"
           "  if (text === \"nan\" || text === \"+nan\" || text === \"-nan\") return Number.NaN;\n"
           "  if (text === \"inf\" || text === \"+inf\" || text === \"infinity\" || "
           "text === \"+infinity\") return Number.POSITIVE_INFINITY;\n"
           "  if (text === \"-inf\" || text === \"-infinity\") return Number.NEGATIVE_INFINITY;\n"
           "  const result = Number(text);\n"
           "  if (Number.isNaN(result)) throw new TypeError(\"MPF float string is invalid\");\n"
           "  return result;\n"
           "}\n";
  }

  void emit_fortran_character_runtime() {
    output_ << "function __mpf_fortran_compare(left, right) {\n"
               "  const width = Math.max(left.length, right.length);\n"
               "  const paddedLeft = left.padEnd(width, \" \");\n"
               "  const paddedRight = right.padEnd(width, \" \");\n"
               "  return paddedLeft < paddedRight ? -1 : paddedLeft > paddedRight ? 1 : 0;\n"
               "}\n";
  }

  void emit_array_runtime() {
    output_
        << "function __mpf_index(values, index, base, allowNegative) {\n"
           "  if (!Number.isSafeInteger(index)) throw new TypeError(\"MPF index must be a safe "
           "integer\");\n"
           "  let normalized = index - base;\n"
           "  if (allowNegative && index < 0) normalized = values.length + index;\n"
           "  if (normalized < 0 || normalized >= values.length) "
           "throw new RangeError(\"MPF index out of bounds\");\n"
           "  return normalized;\n"
           "}\n"
           "function __mpf_shape(values) {\n"
           "  const shape = [];\n"
           "  let current = values;\n"
           "  while (Array.isArray(current)) {\n"
           "    shape.push(current.length);\n"
           "    current = current.length === 0 ? null : current[0];\n"
           "  }\n"
           "  return shape;\n"
           "}\n"
           "function __mpf_matlab_transpose(values) {\n"
           "  if (!Array.isArray(values)) return values;\n"
           "  if (values.length === 0) return [];\n"
           "  if (!Array.isArray(values[0])) return values.map((value) => [value]);\n"
           "  if (!values.every((row) => Array.isArray(row) && "
           "row.length === values[0].length && !row.some(Array.isArray))) "
           "throw new RangeError(\"MPF Matlab transpose requires a rectangular rank-2 "
           "array\");\n"
           "  return Array.from({ length: values[0].length }, (_, column) => "
           "values.map((row) => row[column]));\n"
           "}\n"
           "function __mpf_matlab_elementwise(left, right, operation, leftShape, rightShape, "
           "resultShape) {\n"
           "  const leftArray = Array.isArray(left);\n"
           "  const rightArray = Array.isArray(right);\n"
           "  if (leftArray && rightArray && resultShape !== undefined) {\n"
           "    const size = (shape) => shape.reduce((product, extent) => product * extent, 1);\n"
           "    const leftFlat = __mpf_flatten_column_major(left);\n"
           "    const rightFlat = __mpf_flatten_column_major(right);\n"
           "    if (leftFlat.length !== size(leftShape) || rightFlat.length !== size(rightShape)) "
           "throw new RangeError(\"MPF Matlab broadcast operand shape mismatch\");\n"
           "    for (let axis = 0; axis < resultShape.length; ++axis) {\n"
           "      const l = leftShape[axis]; const r = rightShape[axis];\n"
           "      if (l !== r && l !== 1 && r !== 1) throw new RangeError(\"MPF Matlab "
           "broadcast sizes are incompatible\");\n"
           "    }\n"
           "    const leftStrides = []; const rightStrides = [];\n"
           "    let leftStride = 1; let rightStride = 1;\n"
           "    for (let axis = 0; axis < resultShape.length; ++axis) {\n"
           "      leftStrides.push(leftStride); rightStrides.push(rightStride);\n"
           "      leftStride *= leftShape[axis]; rightStride *= rightShape[axis];\n"
           "    }\n"
           "    const resultSize = size(resultShape);\n"
           "    const flattened = new Array(resultSize);\n"
           "    for (let linear = 0; linear < resultSize; ++linear) {\n"
           "      let remainder = linear; let leftLinear = 0; let rightLinear = 0;\n"
           "      for (let axis = 0; axis < resultShape.length; ++axis) {\n"
           "        const coordinate = remainder % resultShape[axis];\n"
           "        remainder = Math.floor(remainder / resultShape[axis]);\n"
           "        if (leftShape[axis] !== 1) leftLinear += coordinate * leftStrides[axis];\n"
           "        if (rightShape[axis] !== 1) rightLinear += coordinate * "
           "rightStrides[axis];\n"
           "      }\n"
           "      flattened[linear] = operation(leftFlat[leftLinear], rightFlat[rightLinear]);\n"
           "    }\n"
           "    return __mpf_build_column_major(flattened, resultShape);\n"
           "  }\n"
           "  if (leftArray && rightArray) {\n"
           "    if (left.length !== right.length) throw new RangeError(\"MPF Matlab "
           "element-wise shape mismatch\");\n"
           "    return left.map((value, index) => "
           "__mpf_matlab_elementwise(value, right[index], operation));\n"
           "  }\n"
           "  if (leftArray) return left.map((value) => "
           "__mpf_matlab_elementwise(value, right, operation));\n"
           "  if (rightArray) return right.map((value) => "
           "__mpf_matlab_elementwise(left, value, operation));\n"
           "  return operation(left, right);\n"
           "}\n"
           "function __mpf_matlab_add(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a + b, ...shapes); }\n"
           "function __mpf_matlab_subtract(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a - b, ...shapes); }\n"
           "function __mpf_matlab_multiply(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a * b, ...shapes); }\n"
           "function __mpf_matlab_divide(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a / b, ...shapes); }\n"
           "function __mpf_matlab_left_divide(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => b / a, ...shapes); }\n"
           "function __mpf_matlab_power(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a ** b, ...shapes); }\n"
           "function __mpf_matlab_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a === b, ...shapes); }\n"
           "function __mpf_matlab_not_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a !== b, ...shapes); }\n"
           "function __mpf_matlab_less(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a < b, ...shapes); }\n"
           "function __mpf_matlab_less_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a <= b, ...shapes); }\n"
           "function __mpf_matlab_greater(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a > b, ...shapes); }\n"
           "function __mpf_matlab_greater_equal(left, right, ...shapes) { return "
           "__mpf_matlab_elementwise(left, right, (a, b) => a >= b, ...shapes); }\n"
           "function __mpf_matlab_mtimes(left, right) {\n"
           "  if (!Array.isArray(left) || !Array.isArray(right)) return "
           "__mpf_matlab_multiply(left, right);\n"
           "  if (left.length === 0 || right.length === 0 || "
           "!left.every(Array.isArray) || !right.every(Array.isArray)) "
           "throw new RangeError(\"MPF Matlab matrix multiplication requires non-empty "
           "rank-2 arrays\");\n"
           "  const leftColumns = left[0].length;\n"
           "  const rightColumns = right[0].length;\n"
           "  if (!left.every((row) => row.length === leftColumns) || "
           "!right.every((row) => row.length === rightColumns)) "
           "throw new RangeError(\"MPF Matlab matrix must be rectangular\");\n"
           "  if (leftColumns !== right.length) throw new RangeError(\"MPF Matlab matrix "
           "multiplication shape mismatch\");\n"
           "  return left.map((row) => Array.from({ length: rightColumns }, (_, column) => "
           "row.reduce((sum, value, inner) => sum + value * right[inner][column], 0)));\n"
           "}\n"
           "function __mpf_column_major_coordinates(linear, shape) {\n"
           "  const coordinates = [];\n"
           "  for (const extent of shape) { coordinates.push(linear % extent); linear = "
           "Math.floor(linear / extent); }\n"
           "  return coordinates;\n"
           "}\n"
           "function __mpf_at(values, coordinates) {\n"
           "  let result = values;\n"
           "  for (const coordinate of coordinates) result = result[coordinate];\n"
           "  return result;\n"
           "}\n"
           "function __mpf_set_at(values, coordinates, value) {\n"
           "  let target = values;\n"
           "  for (let dimension = 0; dimension + 1 < coordinates.length; ++dimension) "
           "target = target[coordinates[dimension]];\n"
           "  target[coordinates[coordinates.length - 1]] = value;\n"
           "}\n"
           "function __mpf_set_linear_column_major(values, linear, shape, value) {\n"
           "  let target = values;\n"
           "  for (let axis = 0; axis + 1 < shape.length; ++axis) {\n"
           "    const coordinate = linear % shape[axis];\n"
           "    linear = Math.floor(linear / shape[axis]);\n"
           "    target = target[coordinate];\n"
           "  }\n"
           "  target[linear % shape[shape.length - 1]] = value;\n"
           "}\n"
           "function __mpf_flatten_column_major(values) {\n"
           "  const shape = __mpf_shape(values);\n"
           "  const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "  if (shape.length === 1) return values.slice();\n"
           "  const flattened = new Array(size);\n"
           "  const coordinates = new Array(shape.length).fill(0);\n"
           "  for (let linear = 0; linear < size; ++linear) {\n"
           "    flattened[linear] = __mpf_at(values, coordinates);\n"
           "    for (let axis = 0; axis < shape.length; ++axis) {\n"
           "      if (++coordinates[axis] < shape[axis]) break;\n"
           "      coordinates[axis] = 0;\n"
           "    }\n"
           "  }\n"
           "  return flattened;\n"
           "}\n"
           "function __mpf_build_column_major(flattened, shape) {\n"
           "  const strides = new Array(shape.length);\n"
           "  let stride = 1;\n"
           "  for (let axis = 0; axis < shape.length; ++axis) { "
           "strides[axis] = stride; stride *= shape[axis]; }\n"
           "  const build = (dimension, linear) => {\n"
           "    if (dimension === shape.length) return flattened[linear];\n"
           "    return Array.from({ length: shape[dimension] }, (_, coordinate) => "
           "build(dimension + 1, linear + coordinate * strides[dimension]));\n"
           "  };\n"
           "  return build(0, 0);\n"
           "}\n"
           "function __mpf_logical_positions(values, mask) {\n"
           "  const valueShape = __mpf_shape(values);\n"
           "  const valueSize = valueShape.reduce((product, extent) => product * extent, 1);\n"
           "  const maskFlat = __mpf_flatten_column_major(mask);\n"
           "  if (maskFlat.length !== valueSize || "
           "!maskFlat.every((value) => typeof value === \"boolean\")) "
           "throw new RangeError(\"MPF Matlab logical mask shape or type mismatch\");\n"
           "  const positions = [];\n"
           "  for (let linear = 0; linear < maskFlat.length; ++linear) "
           "if (maskFlat[linear]) positions.push(linear);\n"
           "  return { positions, shape: valueShape };\n"
           "}\n"
           "function __mpf_logical_get(values, mask) {\n"
           "  const selection = __mpf_logical_positions(values, mask);\n"
           "  const flattened = __mpf_flatten_column_major(values);\n"
           "  return selection.positions.map((linear) => flattened[linear]);\n"
           "}\n"
           "function __mpf_set_logical(values, mask, replacement) {\n"
           "  const selection = __mpf_logical_positions(values, mask);\n"
           "  const replacements = Array.isArray(replacement) "
           "? __mpf_flatten_column_major(replacement) : null;\n"
           "  if (replacements !== null && replacements.length !== selection.positions.length) "
           "throw new RangeError(\"MPF Matlab logical assignment size mismatch\");\n"
           "  for (let selected = 0; selected < selection.positions.length; ++selected) {\n"
           "    __mpf_set_linear_column_major(values, selection.positions[selected], "
           "selection.shape, replacements === null ? replacement : replacements[selected]);\n"
           "  }\n"
           "}\n"
           "function __mpf_get(values, indices, base, allowNegative, columnMajor) {\n"
           "  if (columnMajor && indices.length === 1 && Array.isArray(values[0])) {\n"
           "    const shape = __mpf_shape(values);\n"
           "    const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "    const linear = __mpf_index({ length: size }, indices[0], base, false);\n"
           "    return __mpf_at(values, __mpf_column_major_coordinates(linear, shape));\n"
           "  }\n"
           "  let result = values;\n"
           "  for (const index of indices) "
           "result = result[__mpf_index(result, index, base, allowNegative)];\n"
           "  return result;\n"
           "}\n"
           "function __mpf_slice_indices(length, selector, base, allowNegative) {\n"
           "  const requireInteger = (value) => {\n"
           "    if (value !== null && !Number.isSafeInteger(value)) "
           "throw new TypeError(\"MPF slice bounds and step must be safe integers\");\n"
           "  };\n"
           "  requireInteger(selector.start);\n"
           "  requireInteger(selector.stop);\n"
           "  requireInteger(selector.step);\n"
           "  const step = selector.step ?? 1;\n"
           "  if (step === 0) throw new RangeError(\"MPF slice step cannot be zero\");\n"
           "  const result = [];\n"
           "  if (!selector.inclusive) {\n"
           "    let start = selector.start ?? (step > 0 ? 0 : length - 1);\n"
           "    let stop = selector.stop ?? (step > 0 ? length : -1);\n"
           "    if (selector.start !== null && start < 0) start += length;\n"
           "    if (selector.stop !== null && stop < 0) stop += length;\n"
           "    if (step > 0) {\n"
           "      start = Math.max(0, Math.min(start, length));\n"
           "      stop = Math.max(0, Math.min(stop, length));\n"
           "      for (let position = start; position < stop; position += step) "
           "result.push(position);\n"
           "    } else {\n"
           "      start = Math.max(-1, Math.min(start, length - 1));\n"
           "      stop = Math.max(-1, Math.min(stop, length - 1));\n"
           "      for (let position = start; position > stop; position += step) "
           "result.push(position);\n"
           "    }\n"
           "    return result;\n"
           "  }\n"
           "  const start = selector.start ?? (step > 0 ? base : base + length - 1);\n"
           "  const stop = selector.stop ?? (step > 0 ? base + length - 1 : base);\n"
           "  if (step > 0) {\n"
           "    for (let position = start; position <= stop; position += step) "
           "result.push(__mpf_index({ length }, position, base, allowNegative));\n"
           "  } else {\n"
           "    for (let position = start; position >= stop; position += step) "
           "result.push(__mpf_index({ length }, position, base, allowNegative));\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "function __mpf_section(values, selectors, base, allowNegative, columnMajor) {\n"
           "  if (columnMajor && selectors.length === 1 && Array.isArray(values[0])) {\n"
           "    const flattened = __mpf_flatten_column_major(values);\n"
           "    return __mpf_slice_indices(flattened.length, selectors[0], base, allowNegative)"
           ".map((index) => flattened[index]);\n"
           "  }\n"
           "  const visit = (value, dimension) => {\n"
           "    if (dimension === selectors.length) return value;\n"
           "    const selector = selectors[dimension];\n"
           "    if (selector.slice) return __mpf_slice_indices(value.length, selector, base, "
           "allowNegative)"
           ".map((index) => visit(value[index], dimension + 1));\n"
           "    return visit(value[__mpf_index(value, selector.value, base, allowNegative)], "
           "dimension + 1);\n"
           "  };\n"
           "  return visit(values, 0);\n"
           "}\n"
           "function __mpf_set(values, indices, value, base, allowNegative, columnMajor) {\n"
           "  if (columnMajor && indices.length === 1 && Array.isArray(values[0])) {\n"
           "    const shape = __mpf_shape(values);\n"
           "    const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "    const linear = __mpf_index({ length: size }, indices[0], base, false);\n"
           "    __mpf_set_linear_column_major(values, linear, shape, value);\n"
           "    return;\n"
           "  }\n"
           "  let target = values;\n"
           "  for (let position = 0; position + 1 < indices.length; ++position) "
           "target = target[__mpf_index(target, indices[position], base, allowNegative)];\n"
           "  target[__mpf_index(target, indices[indices.length - 1], base, allowNegative)] = "
           "value;\n"
           "}\n"
           "function __mpf_python_slice_window(length, selector) {\n"
           "  let start = selector.start ?? 0;\n"
           "  let stop = selector.stop ?? length;\n"
           "  if (start < 0) start += length;\n"
           "  if (stop < 0) stop += length;\n"
           "  start = Math.max(0, Math.min(start, length));\n"
           "  stop = Math.max(0, Math.min(stop, length));\n"
           "  return [start, Math.max(start, stop)];\n"
           "}\n"
           "function __mpf_set_section(values, selectors, replacement, base, allowNegative, "
           "columnMajor, pythonResize) {\n"
           "  if (pythonResize && selectors.length === 1 && selectors[0].slice) {\n"
           "    if (!Array.isArray(replacement)) "
           "throw new TypeError(\"MPF Python slice replacement must be a list\");\n"
           "    const selector = selectors[0];\n"
           "    const step = selector.step ?? 1;\n"
           "    if (step === 1) {\n"
           "      const [start, stop] = __mpf_python_slice_window(values.length, selector);\n"
           "      values.splice(start, stop - start, ...replacement);\n"
           "      return;\n"
           "    }\n"
           "    const indices = __mpf_slice_indices(values.length, selector, base, "
           "allowNegative);\n"
           "    if (indices.length !== replacement.length) "
           "throw new RangeError(\"MPF extended slice replacement size mismatch\");\n"
           "    indices.forEach((index, position) => { values[index] = replacement[position]; });\n"
           "    return;\n"
           "  }\n"
           "  if (columnMajor && selectors.length === 1 && Array.isArray(values[0])) {\n"
           "    const selector = selectors[0];\n"
           "    const shape = __mpf_shape(values);\n"
           "    const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "    const indices = __mpf_slice_indices(size, selector, base, allowNegative);\n"
           "    const replacements = Array.isArray(replacement) ? "
           "__mpf_flatten_column_major(replacement) : replacement;\n"
           "    if (Array.isArray(replacements) && replacements.length !== indices.length) "
           "throw new RangeError(\"MPF linear section replacement size mismatch\");\n"
           "    indices.forEach((linear, position) => {\n"
           "      __mpf_set_linear_column_major(values, linear, shape, "
           "Array.isArray(replacements) ? replacements[position] : replacements);\n"
           "    });\n"
           "    return;\n"
           "  }\n"
           "  const scalar = (value) => {\n"
           "    let result = value;\n"
           "    while (columnMajor && Array.isArray(result) && result.length === 1) result = "
           "result[0];\n"
           "    return result;\n"
           "  };\n"
           "  const assign = (target, dimension, source) => {\n"
           "    const selector = selectors[dimension];\n"
           "    const last = dimension + 1 === selectors.length;\n"
           "    if (selector.slice) {\n"
           "      const indices = __mpf_slice_indices(target.length, selector, base, "
           "allowNegative);\n"
           "      if (Array.isArray(source) && source.length !== indices.length) "
           "throw new RangeError(\"MPF section replacement size mismatch\");\n"
           "      indices.forEach((index, position) => {\n"
           "        const value = Array.isArray(source) ? source[position] : source;\n"
           "        if (last) target[index] = scalar(value); else assign(target[index], dimension "
           "+ 1, value);\n"
           "      });\n"
           "      return;\n"
           "    }\n"
           "    const index = __mpf_index(target, selector.value, base, allowNegative);\n"
           "    if (last) target[index] = scalar(source); else assign(target[index], dimension + "
           "1, source);\n"
           "  };\n"
           "  assign(values, 0, replacement);\n"
           "}\n"
           "function __mpf_sum(values) {\n"
           "  return values.reduce((total, value) => total + "
           "(Array.isArray(value) ? __mpf_sum(value) : value), 0);\n"
           "}\n"
           "function __mpf_numel(values) {\n"
           "  return values.reduce((total, value) => total + "
           "(Array.isArray(value) ? __mpf_numel(value) : 1), 0);\n"
           "}\n"
           "function __mpf_length(values) {\n"
           "  return Math.max(...__mpf_shape(values));\n"
           "}\n"
           "function __mpf_reshape(values, shape) {\n"
           "  if (shape.length === 0 || shape.some((extent) => !Number.isSafeInteger(extent) || "
           "extent <= 0)) throw new RangeError(\"MPF RESHAPE shape is invalid\");\n"
           "  const flattened = __mpf_flatten_column_major(values);\n"
           "  const size = shape.reduce((product, extent) => product * extent, 1);\n"
           "  if (flattened.length !== size) throw new RangeError(\"MPF RESHAPE size mismatch\");\n"
           "  return __mpf_build_column_major(flattened, shape);\n"
           "}\n";
  }

  std::ostream& output_;
};

}  // namespace

void emit_javascript_runtime_fragment(std::ostream& output,
                                      const javascript::lir::RuntimeFragment fragment) {
  RuntimeEmitter(output).emit(fragment);
}

}  // namespace mpf::detail
