#include "matrix_runtime.hpp"

#include <ostream>

namespace mpf::detail {

void emit_cpp_matrix_solve_runtime(std::ostream& output) {
  output
      << "inline double matlab_matrix_one_norm(\n"
         "    const std::vector<std::vector<double>>& values) {\n"
         "  double maximum = 0.0;\n"
         "  for (std::size_t column = 0; column < values.front().size(); ++column) {\n"
         "    double sum = 0.0;\n"
         "    for (const auto& row : values) {\n"
         "      if (!std::isfinite(row[column])) return "
         "std::numeric_limits<double>::infinity();\n"
         "      sum += std::fabs(row[column]);\n"
         "    }\n"
         "    maximum = std::max(maximum, sum);\n"
         "  }\n"
         "  return maximum;\n"
         "}\n"
         "struct matlab_lu_factorization {\n"
         "  std::vector<std::vector<double>> lu;\n"
         "  std::vector<std::size_t> swaps;\n"
         "  bool singular{false};\n"
         "};\n"
         "inline matlab_lu_factorization matlab_lu_factor(\n"
         "    const std::vector<std::vector<double>>& coefficients) {\n"
         "  const auto size = coefficients.size();\n"
         "  matlab_lu_factorization factor{coefficients, std::vector<std::size_t>(size), false};\n"
         "  for (std::size_t pivot = 0; pivot < size; ++pivot) {\n"
         "    auto selected = pivot;\n"
         "    for (std::size_t row = pivot + 1; row < size; ++row) "
         "if (std::fabs(factor.lu[row][pivot]) > std::fabs(factor.lu[selected][pivot])) "
         "selected = row;\n"
         "    factor.swaps[pivot] = selected;\n"
         "    if (selected != pivot) std::swap(factor.lu[pivot], factor.lu[selected]);\n"
         "    const auto diagonal = factor.lu[pivot][pivot];\n"
         "    if (diagonal == 0.0) { factor.singular = true; continue; }\n"
         "    for (std::size_t row = pivot + 1; row < size; ++row) {\n"
         "      factor.lu[row][pivot] /= diagonal;\n"
         "      for (std::size_t column = pivot + 1; column < size; ++column) "
         "factor.lu[row][column] -= factor.lu[row][pivot] * factor.lu[pivot][column];\n"
         "    }\n"
         "  }\n"
         "  return factor;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_lu_apply(\n"
         "    const matlab_lu_factorization& factor, "
         "std::vector<std::vector<double>> values) {\n"
         "  const auto size = factor.lu.size();\n"
         "  for (std::size_t pivot = 0; pivot < size; ++pivot) {\n"
         "    const auto selected = factor.swaps[pivot];\n"
         "    if (selected != pivot) std::swap(values[pivot], values[selected]);\n"
         "  }\n"
         "  for (std::size_t row = 0; row < size; ++row) {\n"
         "    for (std::size_t inner = 0; inner < row; ++inner) {\n"
         "      const auto coefficient = factor.lu[row][inner];\n"
         "      if (coefficient == 0.0) continue;\n"
         "      for (std::size_t column = 0; column < values.front().size(); ++column) "
         "values[row][column] -= coefficient * values[inner][column];\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t reverse = size; reverse > 0; --reverse) {\n"
         "    const auto row = reverse - 1;\n"
         "    for (std::size_t column = 0; column < values.front().size(); ++column) {\n"
         "      auto value = values[row][column];\n"
         "      for (std::size_t inner = row + 1; inner < size; ++inner) {\n"
         "        const auto coefficient = factor.lu[row][inner];\n"
         "        if (coefficient != 0.0) value -= coefficient * values[inner][column];\n"
         "      }\n"
         "      values[row][column] = value / factor.lu[row][row];\n"
         "    }\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_lu_apply_transpose(\n"
         "    const matlab_lu_factorization& factor, "
         "std::vector<std::vector<double>> values) {\n"
         "  const auto size = factor.lu.size();\n"
         "  for (std::size_t row = 0; row < size; ++row) {\n"
         "    for (std::size_t column = 0; column < values.front().size(); ++column) {\n"
         "      auto value = values[row][column];\n"
         "      for (std::size_t inner = 0; inner < row; ++inner) {\n"
         "        const auto coefficient = factor.lu[inner][row];\n"
         "        if (coefficient != 0.0) value -= coefficient * values[inner][column];\n"
         "      }\n"
         "      values[row][column] = value / factor.lu[row][row];\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t reverse = size; reverse > 0; --reverse) {\n"
         "    const auto row = reverse - 1;\n"
         "    for (std::size_t inner = row + 1; inner < size; ++inner) {\n"
         "      const auto coefficient = factor.lu[inner][row];\n"
         "      if (coefficient == 0.0) continue;\n"
         "      for (std::size_t column = 0; column < values.front().size(); ++column) "
         "values[row][column] -= coefficient * values[inner][column];\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t reverse = size; reverse > 0; --reverse) {\n"
         "    const auto pivot = reverse - 1; const auto selected = factor.swaps[pivot];\n"
         "    if (selected != pivot) std::swap(values[pivot], values[selected]);\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "template <typename Solve, typename SolveTranspose> inline double matlab_solver_rcond(\n"
         "    const std::vector<std::vector<double>>& coefficients, Solve solve,\n"
         "    SolveTranspose solve_transpose) {\n"
         "  const auto norm = matlab_matrix_one_norm(coefficients);\n"
         "  if (norm == 0.0 || !std::isfinite(norm)) return 0.0;\n"
         "  const auto size = coefficients.size();\n"
         "  std::vector<std::vector<double>> vector(size, "
         "std::vector<double>(1U, 1.0 / static_cast<double>(size)));\n"
         "  double inverse_norm = 0.0;\n"
         "  for (std::size_t iteration = 0; iteration < 5U; ++iteration) {\n"
         "    const auto solved = solve(vector);\n"
         "    double estimate = 0.0;\n"
         "    for (const auto& row : solved) estimate += std::fabs(row.front());\n"
         "    if (!std::isfinite(estimate)) return 0.0;\n"
         "    inverse_norm = std::max(inverse_norm, estimate);\n"
         "    auto signs = solved;\n"
         "    for (auto& row : signs) row.front() = row.front() >= 0.0 ? 1.0 : -1.0;\n"
         "    const auto transposed = solve_transpose(std::move(signs));\n"
         "    auto selected = std::size_t{0};\n"
         "    for (std::size_t row = 0; row < size; ++row) {\n"
         "      if (!std::isfinite(transposed[row].front())) return 0.0;\n"
         "      if (std::fabs(transposed[row].front()) > "
         "std::fabs(transposed[selected].front())) selected = row;\n"
         "    }\n"
         "    double dual = 0.0;\n"
         "    for (std::size_t row = 0; row < size; ++row) "
         "dual += transposed[row].front() * vector[row].front();\n"
         "    if (std::fabs(transposed[selected].front()) <= dual) break;\n"
         "    vector.assign(size, std::vector<double>(1U)); vector[selected].front() = 1.0;\n"
         "  }\n"
         "  const auto product = norm * inverse_norm;\n"
         "  return product > 0.0 && std::isfinite(product) ? std::min(1.0, 1.0 / product) : "
         "0.0;\n"
         "}\n"
         "inline double matlab_lu_rcond(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    const matlab_lu_factorization& factor) {\n"
         "  if (factor.singular) return 0.0;\n"
         "  return matlab_solver_rcond(\n"
         "      coefficients, [&](auto values) { return matlab_lu_apply(factor, "
         "std::move(values)); },\n"
         "      [&](auto values) { return matlab_lu_apply_transpose(factor, "
         "std::move(values)); });\n"
         "}\n"
         "inline void matlab_warn_square_condition(const double reciprocal_condition) {\n"
         "  if (reciprocal_condition == 0.0) {\n"
         "    std::cerr << \"MPF Matlab matrix is singular to working precision.\\n\";\n"
         "  } else if (reciprocal_condition < std::numeric_limits<double>::epsilon()) {\n"
         "    std::cerr << \"MPF Matlab matrix is close to singular or badly scaled. \"\n"
         "                 \"Results may be inaccurate. RCOND = \"\n"
         "              << reciprocal_condition << \".\\n\";\n"
         "  }\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_lu_solve(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    const std::vector<std::vector<double>>& right_hand_side) {\n"
         "  const auto size = coefficients.size();\n"
         "  if (size == 0 || coefficients.front().size() != size || "
         "right_hand_side.size() != size || right_hand_side.empty() || "
         "right_hand_side.front().empty()) throw std::invalid_argument(\n"
         "      \"MPF Matlab matrix solve shape mismatch\");\n"
         "  const auto factor = matlab_lu_factor(coefficients);\n"
         "  matlab_warn_square_condition(matlab_lu_rcond(coefficients, factor));\n"
         "  return matlab_lu_apply(factor, right_hand_side);\n"
         "}\n"
         "enum class matlab_square_structure { diagonal, upper_triangular, lower_triangular, "
         "tridiagonal, symmetric, dense };\n"
         "inline matlab_square_structure matlab_classify_square_structure(\n"
         "    const std::vector<std::vector<double>>& values) {\n"
         "  bool upper = true; bool lower = true; bool tridiagonal = true; "
         "bool symmetric = true;\n"
         "  for (std::size_t row = 0; row < values.size(); ++row) {\n"
         "    for (std::size_t column = 0; column < values.size(); ++column) {\n"
         "      const auto value = values[row][column];\n"
         "      const auto distance = row > column ? row - column : column - row;\n"
         "      if (distance > 1U && value != 0.0) tridiagonal = false;\n"
         "      if (row > column && value != values[column][row]) symmetric = false;\n"
         "      if (row == column || value == 0.0) continue;\n"
         "      if (row > column) upper = false; else lower = false;\n"
         "    }\n"
         "  }\n"
         "  if (upper && lower) return matlab_square_structure::diagonal;\n"
         "  if (upper) return matlab_square_structure::upper_triangular;\n"
         "  if (lower) return matlab_square_structure::lower_triangular;\n"
         "  if (tridiagonal) return matlab_square_structure::tridiagonal;\n"
         "  if (symmetric) return matlab_square_structure::symmetric;\n"
         "  return matlab_square_structure::dense;\n"
         "}\n"
         "inline double matlab_diagonal_rcond(\n"
         "    const std::vector<std::vector<double>>& values) {\n"
         "  auto smallest = std::numeric_limits<double>::infinity(); double largest = 0.0;\n"
         "  for (std::size_t index = 0; index < values.size(); ++index) {\n"
         "    const auto magnitude = std::fabs(values[index][index]);\n"
         "    if (magnitude == 0.0 || !std::isfinite(magnitude)) return 0.0;\n"
         "    smallest = std::min(smallest, magnitude); largest = std::max(largest, magnitude);\n"
         "  }\n"
         "  return smallest / largest;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_diagonal_apply(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    std::vector<std::vector<double>> values) {\n"
         "  for (std::size_t row = 0; row < values.size(); ++row) "
         "for (auto& value : values[row]) value /= coefficients[row][row];\n"
         "  return values;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_triangular_apply(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    std::vector<std::vector<double>> values, const bool upper) {\n"
         "  if (upper) {\n"
         "    for (std::size_t reverse = coefficients.size(); reverse > 0; --reverse) {\n"
         "      const auto row = reverse - 1;\n"
         "      for (std::size_t column = 0; column < values.front().size(); ++column) {\n"
         "        auto value = values[row][column];\n"
         "        for (std::size_t inner = row + 1; inner < coefficients.size(); ++inner) "
         "value -= coefficients[row][inner] * values[inner][column];\n"
         "        values[row][column] = value / coefficients[row][row];\n"
         "      }\n"
         "    }\n"
         "  } else {\n"
         "    for (std::size_t row = 0; row < coefficients.size(); ++row) {\n"
         "      for (std::size_t column = 0; column < values.front().size(); ++column) {\n"
         "        auto value = values[row][column];\n"
         "        for (std::size_t inner = 0; inner < row; ++inner) "
         "value -= coefficients[row][inner] * values[inner][column];\n"
         "        values[row][column] = value / coefficients[row][row];\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_triangular_apply_transpose(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    std::vector<std::vector<double>> values, const bool upper) {\n"
         "  return matlab_triangular_apply(matlab_matrix_transpose(coefficients), "
         "std::move(values), !upper);\n"
         "}\n"
         "inline double matlab_triangular_rcond(\n"
         "    const std::vector<std::vector<double>>& coefficients, const bool upper) {\n"
         "  const auto size = coefficients.size();\n"
         "  for (std::size_t index = 0; index < size; ++index) "
         "if (coefficients[index][index] == 0.0 || "
         "!std::isfinite(coefficients[index][index])) return 0.0;\n"
         "  return matlab_solver_rcond(\n"
         "      coefficients, [&](auto values) { return matlab_triangular_apply(\n"
         "          coefficients, std::move(values), upper); },\n"
         "      [&](auto values) { return matlab_triangular_apply_transpose(\n"
         "          coefficients, std::move(values), upper); });\n"
         "}\n"
         "struct matlab_tridiagonal_factorization {\n"
         "  std::vector<double> lower;\n"
         "  std::vector<double> diagonal;\n"
         "  std::vector<double> upper;\n"
         "  std::vector<double> second_upper;\n"
         "  std::vector<std::size_t> pivots;\n"
         "  bool singular{false};\n"
         "};\n"
         "inline matlab_tridiagonal_factorization matlab_tridiagonal_factor(\n"
         "    const std::vector<std::vector<double>>& coefficients) {\n"
         "  const auto size = coefficients.size();\n"
         "  const auto adjacent = size > 0U ? size - 1U : 0U;\n"
         "  const auto second = size > 1U ? size - 2U : 0U;\n"
         "  matlab_tridiagonal_factorization factor{std::vector<double>(adjacent),\n"
         "      std::vector<double>(size), std::vector<double>(adjacent),\n"
         "      std::vector<double>(second), std::vector<std::size_t>(size), false};\n"
         "  for (std::size_t row = 0; row < size; ++row) {\n"
         "    factor.diagonal[row] = coefficients[row][row];\n"
         "    factor.pivots[row] = row;\n"
         "    if (row + 1U < size) {\n"
         "      factor.lower[row] = coefficients[row + 1U][row];\n"
         "      factor.upper[row] = coefficients[row][row + 1U];\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t pivot = 0; pivot + 1U < size; ++pivot) {\n"
         "    if (std::fabs(factor.diagonal[pivot]) >= std::fabs(factor.lower[pivot])) {\n"
         "      if (factor.diagonal[pivot] != 0.0) {\n"
         "        const auto multiplier = factor.lower[pivot] / factor.diagonal[pivot];\n"
         "        factor.lower[pivot] = multiplier;\n"
         "        factor.diagonal[pivot + 1U] -= multiplier * factor.upper[pivot];\n"
         "      }\n"
         "    } else {\n"
         "      const auto multiplier = factor.diagonal[pivot] / factor.lower[pivot];\n"
         "      factor.diagonal[pivot] = factor.lower[pivot];\n"
         "      factor.lower[pivot] = multiplier;\n"
         "      const auto previous_upper = factor.upper[pivot];\n"
         "      factor.upper[pivot] = factor.diagonal[pivot + 1U];\n"
         "      factor.diagonal[pivot + 1U] =\n"
         "          previous_upper - multiplier * factor.diagonal[pivot + 1U];\n"
         "      if (pivot + 2U < size) {\n"
         "        factor.second_upper[pivot] = factor.upper[pivot + 1U];\n"
         "        factor.upper[pivot + 1U] = -multiplier * factor.upper[pivot + 1U];\n"
         "      }\n"
         "      factor.pivots[pivot] = pivot + 1U;\n"
         "    }\n"
         "  }\n"
         "  for (const auto value : factor.diagonal) {\n"
         "    if (value == 0.0 || !std::isfinite(value)) { factor.singular = true; break; }\n"
         "  }\n"
         "  return factor;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_tridiagonal_apply(\n"
         "    const matlab_tridiagonal_factorization& factor,\n"
         "    std::vector<std::vector<double>> values) {\n"
         "  const auto size = factor.diagonal.size(); const auto columns = values.front().size();\n"
         "  for (std::size_t pivot = 0; pivot + 1U < size; ++pivot) {\n"
         "    for (std::size_t column = 0; column < columns; ++column) {\n"
         "      if (factor.pivots[pivot] == pivot) {\n"
         "        values[pivot + 1U][column] -= factor.lower[pivot] * values[pivot][column];\n"
         "      } else {\n"
         "        const auto previous = values[pivot][column];\n"
         "        values[pivot][column] = values[pivot + 1U][column];\n"
         "        values[pivot + 1U][column] =\n"
         "            previous - factor.lower[pivot] * values[pivot][column];\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t reverse = size; reverse > 0U; --reverse) {\n"
         "    const auto row = reverse - 1U;\n"
         "    for (std::size_t column = 0; column < columns; ++column) {\n"
         "      auto value = values[row][column];\n"
         "      if (row + 1U < size) value -= factor.upper[row] * values[row + 1U][column];\n"
         "      if (row + 2U < size) "
         "value -= factor.second_upper[row] * values[row + 2U][column];\n"
         "      values[row][column] = value / factor.diagonal[row];\n"
         "    }\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_tridiagonal_apply_transpose(\n"
         "    const matlab_tridiagonal_factorization& factor,\n"
         "    std::vector<std::vector<double>> values) {\n"
         "  const auto size = factor.diagonal.size(); const auto columns = values.front().size();\n"
         "  for (std::size_t row = 0; row < size; ++row) {\n"
         "    for (std::size_t column = 0; column < columns; ++column) {\n"
         "      auto value = values[row][column];\n"
         "      if (row > 0U) value -= factor.upper[row - 1U] * values[row - 1U][column];\n"
         "      if (row > 1U) "
         "value -= factor.second_upper[row - 2U] * values[row - 2U][column];\n"
         "      values[row][column] = value / factor.diagonal[row];\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t reverse = size; reverse > 1U; --reverse) {\n"
         "    const auto row = reverse - 2U;\n"
         "    for (std::size_t column = 0; column < columns; ++column) {\n"
         "      if (factor.pivots[row] == row) {\n"
         "        values[row][column] -= factor.lower[row] * values[row + 1U][column];\n"
         "      } else {\n"
         "        const auto following = values[row + 1U][column];\n"
         "        values[row + 1U][column] = values[row][column] - factor.lower[row] * following;\n"
         "        values[row][column] = following;\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "inline double matlab_tridiagonal_rcond(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    const matlab_tridiagonal_factorization& factor) {\n"
         "  if (factor.singular) return 0.0;\n"
         "  return matlab_solver_rcond(\n"
         "      coefficients, [&](auto values) { return matlab_tridiagonal_apply(\n"
         "          factor, std::move(values)); },\n"
         "      [&](auto values) { return matlab_tridiagonal_apply_transpose(\n"
         "          factor, std::move(values)); });\n"
         "}\n"
         "struct matlab_cholesky_factorization {\n"
         "  std::vector<std::vector<double>> lower;\n"
         "  bool positive_definite{true};\n"
         "};\n"
         "inline matlab_cholesky_factorization matlab_cholesky_factor(\n"
         "    const std::vector<std::vector<double>>& coefficients) {\n"
         "  const auto size = coefficients.size();\n"
         "  matlab_cholesky_factorization factor{\n"
         "      std::vector<std::vector<double>>(size, std::vector<double>(size)), true};\n"
         "  for (std::size_t row = 0; row < size; ++row) {\n"
         "    for (std::size_t column = 0; column <= row; ++column) {\n"
         "      auto value = coefficients[row][column];\n"
         "      for (std::size_t inner = 0; inner < column; ++inner)\n"
         "        value -= factor.lower[row][inner] * factor.lower[column][inner];\n"
         "      if (row == column) {\n"
         "        if (!(value > 0.0) || !std::isfinite(value)) {\n"
         "          factor.positive_definite = false; return factor;\n"
         "        }\n"
         "        factor.lower[row][column] = std::sqrt(value);\n"
         "      } else {\n"
         "        factor.lower[row][column] = value / factor.lower[column][column];\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "  return factor;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_cholesky_apply(\n"
         "    const matlab_cholesky_factorization& factor,\n"
         "    std::vector<std::vector<double>> values) {\n"
         "  const auto size = factor.lower.size(); const auto columns = values.front().size();\n"
         "  for (std::size_t row = 0; row < size; ++row) {\n"
         "    for (std::size_t column = 0; column < columns; ++column) {\n"
         "      auto value = values[row][column];\n"
         "      for (std::size_t inner = 0; inner < row; ++inner)\n"
         "        value -= factor.lower[row][inner] * values[inner][column];\n"
         "      values[row][column] = value / factor.lower[row][row];\n"
         "    }\n"
         "  }\n"
         "  for (std::size_t reverse = size; reverse > 0U; --reverse) {\n"
         "    const auto row = reverse - 1U;\n"
         "    for (std::size_t column = 0; column < columns; ++column) {\n"
         "      auto value = values[row][column];\n"
         "      for (std::size_t inner = row + 1U; inner < size; ++inner)\n"
         "        value -= factor.lower[inner][row] * values[inner][column];\n"
         "      values[row][column] = value / factor.lower[row][row];\n"
         "    }\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "inline double matlab_cholesky_rcond(\n"
         "    const std::vector<std::vector<double>>& coefficients,\n"
         "    const matlab_cholesky_factorization& factor) {\n"
         "  return matlab_solver_rcond(\n"
         "      coefficients, [&](auto values) { return matlab_cholesky_apply(\n"
         "          factor, std::move(values)); },\n"
         "      [&](auto values) { return matlab_cholesky_apply(\n"
         "          factor, std::move(values)); });\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_structured_real_square_solve(\n"
         "    const std::vector<std::vector<double>>& left,\n"
         "    const std::vector<std::vector<double>>& right) {\n"
         "  const auto structure = matlab_classify_square_structure(left);\n"
         "  if (structure == matlab_square_structure::diagonal) {\n"
         "    matlab_warn_square_condition(matlab_diagonal_rcond(left));\n"
         "    return matlab_diagonal_apply(left, right);\n"
         "  }\n"
         "  if (structure == matlab_square_structure::upper_triangular ||\n"
         "      structure == matlab_square_structure::lower_triangular) {\n"
         "    const auto upper = structure == matlab_square_structure::upper_triangular;\n"
         "    matlab_warn_square_condition(matlab_triangular_rcond(left, upper));\n"
         "    return matlab_triangular_apply(left, right, upper);\n"
         "  }\n"
         "  if (structure == matlab_square_structure::tridiagonal) {\n"
         "    const auto factor = matlab_tridiagonal_factor(left);\n"
         "    matlab_warn_square_condition(matlab_tridiagonal_rcond(left, factor));\n"
         "    return matlab_tridiagonal_apply(factor, right);\n"
         "  }\n"
         "  if (structure == matlab_square_structure::symmetric) {\n"
         "    const auto factor = matlab_cholesky_factor(left);\n"
         "    if (factor.positive_definite) {\n"
         "      matlab_warn_square_condition(matlab_cholesky_rcond(left, factor));\n"
         "      return matlab_cholesky_apply(factor, right);\n"
         "    }\n"
         "  }\n"
         "  return matlab_lu_solve(left, right);\n"
         "}\n"
         "struct matlab_cpqr_factorization {\n"
         "  std::vector<std::vector<double>> qr;\n"
         "  std::vector<double> tau;\n"
         "  std::vector<std::size_t> permutation;\n"
         "  std::size_t rank{0};\n"
         "  double tolerance{0.0};\n"
         "};\n"
         "inline matlab_cpqr_factorization matlab_cpqr_factor(\n"
         "    const std::vector<std::vector<double>>& values) {\n"
         "  const auto rows = values.size(); const auto columns = values.front().size();\n"
         "  const auto pivots = std::min(rows, columns);\n"
         "  matlab_cpqr_factorization factor{values, std::vector<double>(pivots), {}, 0U, 0.0};\n"
         "  factor.permutation.reserve(columns);\n"
         "  for (std::size_t column = 0; column < columns; ++column) "
         "factor.permutation.push_back(column);\n"
         "  double scale = 0.0;\n"
         "  for (std::size_t column = 0; column < columns; ++column) {\n"
         "    double norm = 0.0;\n"
         "    for (std::size_t row = 0; row < rows; ++row) "
         "norm = std::hypot(norm, factor.qr[row][column]);\n"
         "    scale = std::max(scale, norm);\n"
         "  }\n"
         "  factor.tolerance = std::numeric_limits<double>::epsilon() * "
         "static_cast<double>(std::max(rows, columns)) * scale;\n"
         "  for (std::size_t pivot = 0; pivot < pivots; ++pivot) {\n"
         "    auto selected = pivot; double selected_norm = -1.0;\n"
         "    for (std::size_t column = pivot; column < columns; ++column) {\n"
         "      double norm = 0.0;\n"
         "      for (std::size_t row = pivot; row < rows; ++row) "
         "norm = std::hypot(norm, factor.qr[row][column]);\n"
         "      if (norm > selected_norm) { selected = column; selected_norm = norm; }\n"
         "    }\n"
         "    if (selected_norm <= factor.tolerance) break;\n"
         "    if (selected != pivot) {\n"
         "      for (std::size_t row = 0; row < rows; ++row) "
         "std::swap(factor.qr[row][pivot], factor.qr[row][selected]);\n"
         "      std::swap(factor.permutation[pivot], factor.permutation[selected]);\n"
         "    }\n"
         "    const auto alpha = factor.qr[pivot][pivot];\n"
         "    const auto beta = alpha <= 0.0 ? selected_norm : -selected_norm;\n"
         "    const auto leading = alpha - beta;\n"
         "    factor.tau[pivot] = (beta - alpha) / beta;\n"
         "    factor.qr[pivot][pivot] = beta;\n"
         "    for (std::size_t row = pivot + 1; row < rows; ++row) "
         "factor.qr[row][pivot] /= leading;\n"
         "    for (std::size_t column = pivot + 1; column < columns; ++column) {\n"
         "      auto projection = factor.qr[pivot][column];\n"
         "      for (std::size_t row = pivot + 1; row < rows; ++row) "
         "projection += factor.qr[row][pivot] * factor.qr[row][column];\n"
         "      projection *= factor.tau[pivot];\n"
         "      factor.qr[pivot][column] -= projection;\n"
         "      for (std::size_t row = pivot + 1; row < rows; ++row) "
         "factor.qr[row][column] -= factor.qr[row][pivot] * projection;\n"
         "    }\n"
         "    factor.rank = pivot + 1U;\n"
         "  }\n"
         "  return factor;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_apply_cpqr_qt(\n"
         "    const matlab_cpqr_factorization& factor, "
         "std::vector<std::vector<double>> values) {\n"
         "  for (std::size_t pivot = 0; pivot < factor.rank; ++pivot) {\n"
         "    for (std::size_t column = 0; column < values.front().size(); ++column) {\n"
         "      auto projection = values[pivot][column];\n"
         "      for (std::size_t row = pivot + 1; row < values.size(); ++row) "
         "projection += factor.qr[row][pivot] * values[row][column];\n"
         "      projection *= factor.tau[pivot];\n"
         "      values[pivot][column] -= projection;\n"
         "      for (std::size_t row = pivot + 1; row < values.size(); ++row) "
         "values[row][column] -= factor.qr[row][pivot] * projection;\n"
         "    }\n"
         "  }\n"
         "  return values;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_basic_least_squares(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  const auto factor = matlab_cpqr_factor(left);\n"
         "  const auto transformed = matlab_apply_cpqr_qt(factor, right);\n"
         "  const auto columns = left.front().size(); const auto outputs = right.front().size();\n"
         "  if (factor.rank < std::min(left.size(), columns)) std::cerr\n"
         "      << \"MPF Matlab matrix is rank deficient to working precision (rank \"\n"
         "      << factor.rank << \", tolerance \" << factor.tolerance\n"
         "      << \"); using a basic least-squares solution\\n\";\n"
         "  std::vector<std::vector<double>> pivoted(columns, "
         "std::vector<double>(outputs));\n"
         "  for (std::size_t reverse = factor.rank; reverse > 0; --reverse) {\n"
         "    const auto row = reverse - 1;\n"
         "    for (std::size_t output = 0; output < outputs; ++output) {\n"
         "      auto value = transformed[row][output];\n"
         "      for (std::size_t inner = row + 1; inner < columns; ++inner) "
         "value -= factor.qr[row][inner] * pivoted[inner][output];\n"
         "      pivoted[row][output] = value / factor.qr[row][row];\n"
         "    }\n"
         "  }\n"
         "  std::vector<std::vector<double>> result(columns, "
         "std::vector<double>(outputs));\n"
         "  for (std::size_t row = 0; row < columns; ++row) "
         "result[factor.permutation[row]] = std::move(pivoted[row]);\n"
         "  return result;\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_overdetermined_solve(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  return matlab_basic_least_squares(left, right);\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_underdetermined_solve(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  return matlab_basic_least_squares(left, right);\n"
         "}\n"
         "inline void matlab_validate_matrix_solve_shape(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  if (right.size() != left.size()) throw std::invalid_argument(\n"
         "      \"MPF Matlab matrix solve shape mismatch\");\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_matrix_solve_structured_real_square(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  matlab_validate_matrix_solve_shape(left, right);\n"
         "  if (left.size() != left.front().size()) throw std::invalid_argument(\n"
         "      \"MPF Matlab matrix solve disagrees with its static square plan\");\n"
         "  return matlab_structured_real_square_solve(left, right);\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_matrix_solve_overdetermined(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  matlab_validate_matrix_solve_shape(left, right);\n"
         "  if (left.size() <= left.front().size()) throw std::invalid_argument(\n"
         "      \"MPF Matlab matrix solve disagrees with its static overdetermined plan\");\n"
         "  return matlab_overdetermined_solve(left, right);\n"
         "}\n"
         "inline std::vector<std::vector<double>> matlab_matrix_solve_underdetermined(\n"
         "    const std::vector<std::vector<double>>& left, "
         "const std::vector<std::vector<double>>& right) {\n"
         "  matlab_validate_matrix_solve_shape(left, right);\n"
         "  if (left.size() >= left.front().size()) throw std::invalid_argument(\n"
         "      \"MPF Matlab matrix solve disagrees with its static underdetermined plan\");\n"
         "  return matlab_underdetermined_solve(left, right);\n"
         "}\n"
         "template <typename Left, typename Right> auto matlab_mldivide_structured_real_square(\n"
         "    const std::vector<std::vector<Left>>& left, "
         "const std::vector<std::vector<Right>>& right) {\n"
         "  return matlab_matrix_solve_structured_real_square(matlab_dense_matrix(left, "
         "\"coefficient "
         "matrix\"), matlab_dense_matrix(right, \"right-hand side\"));\n"
         "}\n"
         "template <typename Left, typename Right> auto matlab_mldivide_overdetermined(\n"
         "    const std::vector<std::vector<Left>>& left, "
         "const std::vector<std::vector<Right>>& right) {\n"
         "  return matlab_matrix_solve_overdetermined(matlab_dense_matrix(left, "
         "\"coefficient matrix\"), matlab_dense_matrix(right, \"right-hand side\"));\n"
         "}\n"
         "template <typename Left, typename Right> auto matlab_mldivide_underdetermined(\n"
         "    const std::vector<std::vector<Left>>& left, "
         "const std::vector<std::vector<Right>>& right) {\n"
         "  return matlab_matrix_solve_underdetermined(matlab_dense_matrix(left, "
         "\"coefficient matrix\"), matlab_dense_matrix(right, \"right-hand side\"));\n"
         "}\n"
         "template <typename Left, typename Right> auto matlab_mrdivide_structured_real_square(\n"
         "    const Left& left, const Right& right) {\n"
         "  const auto normalized_left = matlab_dense_matrix(left, \"left operand\");\n"
         "  const auto normalized_right = matlab_dense_matrix(right, \"right divisor\");\n"
         "  return matlab_matrix_transpose(matlab_matrix_solve_structured_real_square(\n"
         "      matlab_matrix_transpose(normalized_right), "
         "matlab_matrix_transpose(normalized_left)));\n"
         "}\n"
         "template <typename Left, typename Right> auto matlab_mrdivide_overdetermined(\n"
         "    const Left& left, const Right& right) {\n"
         "  const auto normalized_left = matlab_dense_matrix(left, \"left operand\");\n"
         "  const auto normalized_right = matlab_dense_matrix(right, \"right divisor\");\n"
         "  return matlab_matrix_transpose(matlab_matrix_solve_overdetermined(\n"
         "      matlab_matrix_transpose(normalized_right), "
         "matlab_matrix_transpose(normalized_left)));\n"
         "}\n"
         "template <typename Left, typename Right> auto matlab_mrdivide_underdetermined(\n"
         "    const Left& left, const Right& right) {\n"
         "  const auto normalized_left = matlab_dense_matrix(left, \"left operand\");\n"
         "  const auto normalized_right = matlab_dense_matrix(right, \"right divisor\");\n"
         "  return matlab_matrix_transpose(matlab_matrix_solve_underdetermined(\n"
         "      matlab_matrix_transpose(normalized_right), "
         "matlab_matrix_transpose(normalized_left)));\n"
         "}\n";
}

}  // namespace mpf::detail
