#include "runtime.hpp"

#include <algorithm>
#include <ostream>

#include "matrix_runtime.hpp"

namespace mpf::detail {
namespace {

class RuntimeEmitter final {
 public:
  explicit RuntimeEmitter(std::ostream& output) : output_(output) {}

  void emit(const std::string_view runtime_namespace,
            const std::vector<cpp::lir::RuntimeFragment>& fragments) {
    const bool include_python_runtime =
        std::find(fragments.begin(), fragments.end(), cpp::lir::RuntimeFragment::dynamic_values) !=
        fragments.end();
    output_ << "namespace " << runtime_namespace << " {\n";
    output_
        << "template <typename T> class optional_argument {\n"
           " public:\n"
           "  optional_argument() = default;\n"
           "  optional_argument(std::nullopt_t) noexcept {}\n"
           "  optional_argument(T& value) noexcept : pointer_(&value) {}\n"
           "  optional_argument(const T& value) : owned_(value), pointer_(&owned_.value()) {}\n"
           "  optional_argument(T&& value) : owned_(std::move(value)), pointer_(&owned_.value()) "
           "{}\n"
           "  optional_argument(const optional_argument& other) : owned_(other.owned_) {\n"
           "    pointer_ = other.owns_value() ? &owned_.value() : other.pointer_;\n"
           "  }\n"
           "  optional_argument(optional_argument&& other) {\n"
           "    const bool owned = other.owns_value();\n"
           "    owned_ = std::move(other.owned_);\n"
           "    pointer_ = owned ? &owned_.value() : other.pointer_;\n"
           "  }\n"
           "  optional_argument& operator=(const optional_argument& other) {\n"
           "    if (this == &other) return *this;\n"
           "    const bool owned = other.owns_value();\n"
           "    owned_ = other.owned_;\n"
           "    pointer_ = owned ? &owned_.value() : other.pointer_;\n"
           "    return *this;\n"
           "  }\n"
           "  optional_argument& operator=(optional_argument&& other) {\n"
           "    if (this == &other) return *this;\n"
           "    const bool owned = other.owns_value();\n"
           "    owned_ = std::move(other.owned_);\n"
           "    pointer_ = owned ? &owned_.value() : other.pointer_;\n"
           "    return *this;\n"
           "  }\n"
           "  bool has_value() const noexcept { return pointer_ != nullptr; }\n"
           "  T& value() { if (pointer_ == nullptr) throw std::bad_optional_access{}; return "
           "*pointer_; }\n"
           "  const T& value() const {\n"
           "    if (pointer_ == nullptr) throw std::bad_optional_access{};\n"
           "    return *pointer_;\n"
           "  }\n"
           " private:\n"
           "  bool owns_value() const noexcept {\n"
           "    return owned_.has_value() && pointer_ == &owned_.value();\n"
           "  }\n"
           "  std::optional<T> owned_;\n"
           "  T* pointer_{nullptr};\n"
           "};\n\n"
           "template <typename T> void print_value(const T& value);\n"
           "template <typename T> void print_value(const std::vector<T>& values);\n"
           "template <typename... T> void print_value(const std::tuple<T...>& values);\n\n"
           "template <typename T> void print_value(const T& value) { std::cout << value; }\n"
           "template <typename T> void print_value(const std::vector<T>& values) {\n"
           "  std::cout << '[';\n"
           "  bool first = true;\n"
           "  for (const auto& value : values) {\n"
           "    if (!first) std::cout << \", \";\n"
           "    print_value(value);\n"
           "    first = false;\n"
           "  }\n"
           "  std::cout << ']';\n"
           "}\n"
           "template <typename... T> void print_value(const std::tuple<T...>& values) {\n"
           "  std::cout << '(';\n"
           "  bool first = true;\n"
           "  std::apply([&](const auto&... value) {\n"
           "    ((std::cout << (first ? \"\" : \", \"), print_value(value), first = false), ...);\n"
           "  }, values);\n"
           "  std::cout << ')';\n"
           "}\n"
           "inline void print() { std::cout << '\\n'; }\n"
           "template <typename... T> void print(const T&... value) {\n"
           "  bool first = true;\n"
           "  ((std::cout << (first ? \"\" : \" \"), print_value(value), first = false), ...);\n"
           "  std::cout << '\\n';\n"
           "}\n"
           "template <typename Cursor, typename Stop, typename Step> bool range_continue(\n"
           "    const Cursor& cursor, const Stop& stop, const Step& step, bool inclusive) {\n"
           "  if (step >= static_cast<Step>(0)) return inclusive ? cursor <= stop : cursor < "
           "stop;\n"
           "  return inclusive ? cursor >= stop : cursor > stop;\n"
           "}\n"
           "template <typename Cursor, typename Stop, typename Step> bool range_next(\n"
           "    Cursor& cursor, const Stop& stop, const Step& step, bool inclusive, bool& "
           "first) {\n"
           "  if (first)\n"
           "    first = false;\n"
           "  else\n"
           "    cursor += step;\n"
           "  return range_continue(cursor, stop, step, inclusive);\n"
           "}\n"
           "inline int fortran_compare(const std::string& left, const std::string& right) {\n"
           "  const auto width = std::max(left.size(), right.size());\n"
           "  for (std::size_t index = 0; index < width; ++index) {\n"
           "    const auto left_character = static_cast<unsigned char>(index < left.size() ? "
           "left[index] : ' ');\n"
           "    const auto right_character = static_cast<unsigned char>(index < right.size() ? "
           "right[index] : ' ');\n"
           "    if (left_character < right_character) return -1;\n"
           "    if (left_character > right_character) return 1;\n"
           "  }\n"
           "  return 0;\n"
           "}\n"
           "inline std::size_t normalize_index(std::size_t size, std::int64_t index, "
           "std::size_t base, bool allow_negative) {\n"
           "  std::int64_t normalized = index - static_cast<std::int64_t>(base);\n"
           "  if (allow_negative && index < 0) normalized = static_cast<std::int64_t>(size) + "
           "index;\n"
           "  if (normalized < 0 || static_cast<std::size_t>(normalized) >= size) "
           "throw std::out_of_range(\"MPF index out of bounds\");\n"
           "  return static_cast<std::size_t>(normalized);\n"
           "}\n"
           "template <typename T> T& index(std::vector<T>& values, std::int64_t position, "
           "std::size_t base, bool allow_negative) {\n"
           "  return values.at(normalize_index(values.size(), position, base, allow_negative));\n"
           "}\n"
           "template <typename T> const T& index(const std::vector<T>& values, "
           "std::int64_t position, std::size_t base, bool allow_negative) {\n"
           "  return values.at(normalize_index(values.size(), position, base, allow_negative));\n"
           "}\n"
           "inline std::vector<std::size_t> slice_indices("
           "std::size_t size, std::optional<std::int64_t> start_value, "
           "std::optional<std::int64_t> stop_value, std::optional<std::int64_t> step_value, "
           "std::size_t base, bool allow_negative, bool inclusive) {\n"
           "  const auto step = step_value.value_or(1);\n"
           "  if (step == 0) throw std::invalid_argument(\"MPF slice step cannot be zero\");\n"
           "  std::vector<std::size_t> result;\n"
           "  if (size == 0) return result;\n"
           "  if (size > static_cast<std::size_t>(std::numeric_limits<std::int64_t>::max())) "
           "throw std::length_error(\"MPF array exceeds signed index range\");\n"
           "  const auto signed_size = static_cast<std::int64_t>(size);\n"
           "  if (!inclusive) {\n"
           "    auto start = start_value.value_or(step > 0 ? 0 : signed_size - 1);\n"
           "    auto stop = stop_value.value_or(step > 0 ? signed_size : -1);\n"
           "    if (start_value.has_value() && start < 0) start += signed_size;\n"
           "    if (stop_value.has_value() && stop < 0) stop += signed_size;\n"
           "    if (step > 0) {\n"
           "      start = std::max<std::int64_t>(0, std::min(start, signed_size));\n"
           "      stop = std::max<std::int64_t>(0, std::min(stop, signed_size));\n"
           "      for (auto position = start; position < stop; position += step) "
           "result.push_back(static_cast<std::size_t>(position));\n"
           "    } else {\n"
           "      start = std::max<std::int64_t>(-1, std::min(start, signed_size - 1));\n"
           "      stop = std::max<std::int64_t>(-1, std::min(stop, signed_size - 1));\n"
           "      for (auto position = start; position > stop; position += step) "
           "result.push_back(static_cast<std::size_t>(position));\n"
           "    }\n"
           "    return result;\n"
           "  }\n"
           "  auto position = start_value.value_or("
           "step > 0 ? static_cast<std::int64_t>(base) "
           ": static_cast<std::int64_t>(base + size - 1));\n"
           "  const auto stop = stop_value.value_or("
           "step > 0 ? static_cast<std::int64_t>(base + size - 1) "
           ": static_cast<std::int64_t>(base));\n"
           "  while (step > 0 ? position <= stop : position >= stop) {\n"
           "    result.push_back(normalize_index(size, position, base, allow_negative));\n"
           "    if (result.size() > size) throw std::out_of_range(\"MPF slice exceeds array "
           "extent\");\n"
           "    if ((step > 0 && position > std::numeric_limits<std::int64_t>::max() - step) ||\n"
           "        (step < 0 && position < std::numeric_limits<std::int64_t>::min() - step)) "
           "break;\n"
           "    position += step;\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<T> slice("
           "const std::vector<T>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive) {\n"
           "  std::vector<T> result;\n"
           "  for (const auto position : slice_indices(values.size(), start, stop, step, base, "
           "allow_negative, inclusive)) result.push_back(values.at(position));\n"
           "  return result;\n"
           "}\n"
           "template <typename T> struct is_vector : std::false_type {};\n"
           "template <typename T> struct is_vector<std::vector<T>> : std::true_type {};\n"
           "template <typename T> struct scalar_type { using type = T; };\n"
           "template <typename T> struct scalar_type<std::vector<T>> { "
           "using type = typename scalar_type<T>::type; };\n"
           "template <typename T> using scalar_type_t = typename scalar_type<T>::type;\n"
           "template <typename T, std::enable_if_t<!is_vector<std::decay_t<T>>::value, int> = 0> "
           "T matlab_transpose(const T& value) { return value; }\n"
           "template <typename T> auto matlab_transpose(const std::vector<T>& values) {\n"
           "  if constexpr (is_vector<T>::value) {\n"
           "    using scalar = typename T::value_type;\n"
           "    const auto columns = values.empty() ? 0 : values.front().size();\n"
           "    for (const auto& row : values) if (row.size() != columns) "
           "throw std::invalid_argument(\"MPF Matlab transpose requires a rectangular "
           "rank-2 array\");\n"
           "    std::vector<std::vector<scalar>> result(columns, "
           "std::vector<scalar>(values.size()));\n"
           "    for (std::size_t row = 0; row < values.size(); ++row) "
           "for (std::size_t column = 0; column < columns; ++column) "
           "result[column][row] = values[row][column];\n"
           "    return result;\n"
           "  } else {\n"
           "    std::vector<std::vector<T>> result; result.reserve(values.size());\n"
           "    for (const auto& value : values) result.push_back({value});\n"
           "    return result;\n"
           "  }\n"
           "}\n"
           "template <typename Left, typename Right, typename Operation> auto "
           "matlab_elementwise(const Left& left, const Right& right, Operation operation) {\n"
           "  if constexpr (is_vector<std::decay_t<Left>>::value && "
           "is_vector<std::decay_t<Right>>::value) {\n"
           "    if (left.size() != right.size()) throw std::invalid_argument(\"MPF Matlab "
           "element-wise shape mismatch\");\n"
           "    using result_type = decltype(matlab_elementwise("
           "std::declval<const typename std::decay_t<Left>::value_type&>(), "
           "std::declval<const typename std::decay_t<Right>::value_type&>(), operation));\n"
           "    std::vector<result_type> result; result.reserve(left.size());\n"
           "    for (std::size_t index = 0; index < left.size(); ++index) "
           "result.push_back(matlab_elementwise(left[index], right[index], operation));\n"
           "    return result;\n"
           "  } else if constexpr (is_vector<std::decay_t<Left>>::value) {\n"
           "    using result_type = decltype(matlab_elementwise("
           "std::declval<const typename std::decay_t<Left>::value_type&>(), right, operation));\n"
           "    std::vector<result_type> result; result.reserve(left.size());\n"
           "    for (const auto& value : left) "
           "result.push_back(matlab_elementwise(value, right, operation));\n"
           "    return result;\n"
           "  } else if constexpr (is_vector<std::decay_t<Right>>::value) {\n"
           "    using result_type = decltype(matlab_elementwise("
           "left, std::declval<const typename std::decay_t<Right>::value_type&>(), operation));\n"
           "    std::vector<result_type> result; result.reserve(right.size());\n"
           "    for (const auto& value : right) "
           "result.push_back(matlab_elementwise(left, value, operation));\n"
           "    return result;\n"
           "  } else {\n"
           "    return operation(left, right);\n"
           "  }\n"
           "}\n"
           "template <typename Left, typename Right> auto matlab_add(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return a + b; }); }\n"
           "template <typename Left, typename Right> auto matlab_subtract(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, const "
           "auto& b) { return a - b; }); }\n"
           "template <typename Left, typename Right> auto matlab_multiply(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, const "
           "auto& b) { return a * b; }); }\n"
           "template <typename Left, typename Right> auto matlab_divide(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return static_cast<double>(a) / static_cast<double>(b); }); }\n"
           "template <typename Left, typename Right> auto matlab_left_divide(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, const "
           "auto& b) { return static_cast<double>(b) / static_cast<double>(a); }); }\n"
           "template <typename Left, typename Right> auto matlab_power(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return std::pow(static_cast<double>(a), static_cast<double>(b)); }); }\n"
           "template <typename Left, typename Right> auto matlab_equal(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return a == b; }); }\n"
           "template <typename Left, typename Right> auto matlab_not_equal(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, "
           "const auto& b) { return a != b; }); }\n"
           "template <typename Left, typename Right> auto matlab_less(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return a < b; }); }\n"
           "template <typename Left, typename Right> auto matlab_less_equal(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, "
           "const auto& b) { return a <= b; }); }\n"
           "template <typename Left, typename Right> auto matlab_greater(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return a > b; }); }\n"
           "template <typename Left, typename Right> auto matlab_greater_equal(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, "
           "const auto& b) { return a >= b; }); }\n"
           "template <typename Left, typename Right> auto matlab_mtimes("
           "const std::vector<std::vector<Left>>& left, "
           "const std::vector<std::vector<Right>>& right) {\n"
           "  if (left.empty() || right.empty() || left.front().empty() || "
           "right.front().empty()) throw std::invalid_argument(\"MPF Matlab matrix "
           "multiplication requires non-empty rank-2 arrays\");\n"
           "  const auto left_columns = left.front().size();\n"
           "  const auto right_columns = right.front().size();\n"
           "  for (const auto& row : left) if (row.size() != left_columns) "
           "throw std::invalid_argument(\"MPF Matlab matrix must be rectangular\");\n"
           "  for (const auto& row : right) if (row.size() != right_columns) "
           "throw std::invalid_argument(\"MPF Matlab matrix must be rectangular\");\n"
           "  if (left_columns != right.size()) throw std::invalid_argument(\"MPF Matlab "
           "matrix multiplication shape mismatch\");\n"
           "  using result_type = std::decay_t<decltype(std::declval<Left>() * "
           "std::declval<Right>())>;\n"
           "  std::vector<std::vector<result_type>> result("
           "left.size(), std::vector<result_type>(right_columns));\n"
           "  for (std::size_t row = 0; row < left.size(); ++row) "
           "for (std::size_t column = 0; column < right_columns; ++column) "
           "for (std::size_t inner = 0; inner < left_columns; ++inner) "
           "result[row][column] += left[row][inner] * right[inner][column];\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<std::vector<double>> matlab_dense_matrix("
           "const std::vector<std::vector<T>>& values, const std::string& name) {\n"
           "  if (values.empty() || values.front().empty()) "
           "throw std::invalid_argument(\"MPF Matlab \" + name + "
           "\" must be a non-empty rank-2 matrix\");\n"
           "  const auto columns = values.front().size();\n"
           "  std::vector<std::vector<double>> result; result.reserve(values.size());\n"
           "  for (const auto& row : values) {\n"
           "    if (row.size() != columns) throw std::invalid_argument(\"MPF Matlab \" + name + "
           "\" must be rectangular\");\n"
           "    std::vector<double> converted; converted.reserve(columns);\n"
           "    for (const auto& value : row) {\n"
           "      const auto numeric = static_cast<double>(value);\n"
           "      if (!std::isfinite(numeric)) throw std::invalid_argument(\"MPF Matlab \" + "
           "name + \" requires finite real values\");\n"
           "      converted.push_back(numeric);\n"
           "    }\n"
           "    result.push_back(std::move(converted));\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<std::vector<double>> matlab_dense_matrix("
           "const std::vector<T>& values, const std::string& name) {\n"
           "  if (values.empty()) throw std::invalid_argument(\"MPF Matlab \" + name + "
           "\" must be a non-empty row matrix\");\n"
           "  std::vector<double> row; row.reserve(values.size());\n"
           "  for (const auto& value : values) {\n"
           "    const auto numeric = static_cast<double>(value);\n"
           "    if (!std::isfinite(numeric)) throw std::invalid_argument(\"MPF Matlab \" + name + "
           "\" requires finite real values\");\n"
           "    row.push_back(numeric);\n"
           "  }\n"
           "  return {std::move(row)};\n"
           "}\n"
           "inline std::vector<std::vector<double>> matlab_matrix_transpose("
           "const std::vector<std::vector<double>>& values) {\n"
           "  std::vector<std::vector<double>> result(values.front().size(), "
           "std::vector<double>(values.size()));\n"
           "  for (std::size_t row = 0; row < values.size(); ++row) "
           "for (std::size_t column = 0; column < values.front().size(); ++column) "
           "result[column][row] = values[row][column];\n"
           "  return result;\n"
           "}\n"
           "inline std::vector<std::vector<double>> matlab_identity(const std::size_t size) {\n"
           "  std::vector<std::vector<double>> result(size, std::vector<double>(size));\n"
           "  for (std::size_t index = 0; index < size; ++index) result[index][index] = 1.0;\n"
           "  return result;\n"
           "}\n"
           "inline std::vector<std::vector<double>> matlab_lu_solve("
           "std::vector<std::vector<double>> left, "
           "std::vector<std::vector<double>> right) {\n"
           "  const auto size = left.size();\n"
           "  if (size == 0 || left.front().size() != size || right.size() != size || "
           "right.empty() || right.front().empty()) throw std::invalid_argument("
           "\"MPF Matlab matrix solve shape mismatch\");\n"
           "  double maximum = 0.0;\n"
           "  for (const auto& row : left) for (const auto value : row) "
           "maximum = std::max(maximum, std::fabs(value));\n"
           "  const auto tolerance = std::numeric_limits<double>::epsilon() * "
           "static_cast<double>(std::max<std::size_t>(1, size)) * maximum;\n"
           "  for (std::size_t pivot = 0; pivot < size; ++pivot) {\n"
           "    std::size_t selected = pivot;\n"
           "    for (std::size_t row = pivot + 1; row < size; ++row) "
           "if (std::fabs(left[row][pivot]) > std::fabs(left[selected][pivot])) selected = "
           "row;\n"
           "    if (std::fabs(left[selected][pivot]) <= tolerance) throw std::domain_error("
           "\"MPF Matlab matrix is singular to working precision\");\n"
           "    if (selected != pivot) { std::swap(left[pivot], left[selected]); "
           "std::swap(right[pivot], right[selected]); }\n"
           "    for (std::size_t row = pivot + 1; row < size; ++row) {\n"
           "      const auto factor = left[row][pivot] / left[pivot][pivot];\n"
           "      left[row][pivot] = 0.0;\n"
           "      for (std::size_t column = pivot + 1; column < size; ++column) "
           "left[row][column] -= factor * left[pivot][column];\n"
           "      for (std::size_t column = 0; column < right.front().size(); ++column) "
           "right[row][column] -= factor * right[pivot][column];\n"
           "    }\n"
           "  }\n"
           "  std::vector<std::vector<double>> result(size, "
           "std::vector<double>(right.front().size()));\n"
           "  for (std::size_t reverse = size; reverse > 0; --reverse) {\n"
           "    const auto row = reverse - 1;\n"
           "    for (std::size_t column = 0; column < right.front().size(); ++column) {\n"
           "      auto value = right[row][column];\n"
           "      for (std::size_t inner = row + 1; inner < size; ++inner) "
           "value -= left[row][inner] * result[inner][column];\n"
           "      result[row][column] = value / left[row][row];\n"
           "    }\n"
           "  }\n"
           "  return result;\n"
           "}\n";
    emit_cpp_matrix_solve_runtime(output_);
    output_
        << "template <typename Value, typename Exponent> auto matlab_mpower("
           "const std::vector<std::vector<Value>>& values, const Exponent exponent_value) {\n"
           "  auto factor = matlab_dense_matrix(values, \"matrix power base\");\n"
           "  if (factor.size() != factor.front().size()) throw std::invalid_argument("
           "\"MPF Matlab matrix power requires a square matrix\");\n"
           "  const auto numeric_exponent = static_cast<double>(exponent_value);\n"
           "  constexpr double maximum_safe_integer = 9007199254740991.0;\n"
           "  if (!std::isfinite(numeric_exponent) || std::trunc(numeric_exponent) != "
           "numeric_exponent || std::fabs(numeric_exponent) > maximum_safe_integer) "
           "throw std::invalid_argument(\"MPF Matlab matrix power currently requires a safe "
           "integer exponent\");\n"
           "  auto exponent = static_cast<std::int64_t>(numeric_exponent);\n"
           "  auto result = matlab_identity(factor.size());\n"
           "  if (exponent < 0) { factor = matlab_lu_solve(factor, result); exponent = "
           "-exponent; }\n"
           "  auto remaining = static_cast<std::uint64_t>(exponent);\n"
           "  while (remaining > 0) {\n"
           "    if ((remaining & 1U) != 0U) result = matlab_mtimes(result, factor);\n"
           "    remaining >>= 1U;\n"
           "    if (remaining > 0) factor = matlab_mtimes(factor, factor);\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "struct scalar_selector { std::int64_t value; };\n"
           "struct slice_selector {\n"
           "  std::optional<std::int64_t> start;\n"
           "  std::optional<std::int64_t> stop;\n"
           "  std::optional<std::int64_t> step;\n"
           "  std::size_t base; bool allow_negative; bool inclusive;\n"
           "};\n"
           "template <typename T> struct numeric_selector { T values; };\n"
           "template <typename T> numeric_selector(T) -> numeric_selector<std::decay_t<T>>;\n"
           "template <typename T> struct logical_selector { T values; };\n"
           "template <typename T> logical_selector(T) -> logical_selector<std::decay_t<T>>;\n"
           "template <typename T> struct empty_selector { T values; };\n"
           "template <typename T> empty_selector(T) -> empty_selector<std::decay_t<T>>;\n"
           "template <typename T> struct is_expanding_selector : std::false_type {};\n"
           "template <> struct is_expanding_selector<slice_selector> : std::true_type {};\n"
           "template <typename T> struct is_expanding_selector<numeric_selector<T>> "
           ": std::true_type {};\n"
           "template <typename T> struct is_expanding_selector<logical_selector<T>> "
           ": std::true_type {};\n"
           "template <typename T> struct is_expanding_selector<empty_selector<T>> "
           ": std::true_type {};\n"
           "template <typename T> void selector_shape(const T&, std::vector<std::size_t>&) {}\n"
           "template <typename T> void selector_shape(const std::vector<T>& values, "
           "std::vector<std::size_t>& shape) {\n"
           "  shape.push_back(values.size());\n"
           "  if (values.empty()) return;\n"
           "  std::vector<std::size_t> expected; selector_shape(values.front(), expected);\n"
           "  for (const auto& value : values) { std::vector<std::size_t> actual; "
           "selector_shape(value, actual); if (actual != expected) throw std::invalid_argument("
           "\"MPF selector must be rectangular\"); }\n"
           "  shape.insert(shape.end(), expected.begin(), expected.end());\n"
           "}\n"
           "template <typename Values> scalar_type_t<Values> selector_value_at("
           "const Values& values, const std::vector<std::size_t>& coordinates, "
           "std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) return selector_value_at("
           "values.at(coordinates.at(dimension)), coordinates, dimension + 1);\n"
           "  else return values;\n"
           "}\n"
           "template <typename Values, typename Scalar> void selector_set_at("
           "Values& values, const std::vector<std::size_t>& coordinates, const Scalar& value, "
           "std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) selector_set_at("
           "values.at(coordinates.at(dimension)), coordinates, value, dimension + 1);\n"
           "  else values = static_cast<Values>(value);\n"
           "}\n"
           "inline std::vector<std::size_t> selector_coordinates("
           "std::size_t linear, const std::vector<std::size_t>& shape) {\n"
           "  std::vector<std::size_t> result(shape.size());\n"
           "  for (std::size_t axis = 0; axis < shape.size(); ++axis) { "
           "result[axis] = linear % shape[axis]; linear /= shape[axis]; }\n"
           "  return result;\n"
           "}\n"
           "template <typename Values> std::vector<scalar_type_t<Values>> "
           "flatten_selector_column_major(const Values& values) {\n"
           "  if constexpr (!is_vector<Values>::value) return {values};\n"
           "  else {\n"
           "    std::vector<std::size_t> shape; selector_shape(values, shape);\n"
           "    std::size_t size = 1; for (const auto extent : shape) { "
           "if (extent != 0 && size > std::numeric_limits<std::size_t>::max() / extent) "
           "throw std::length_error(\"MPF selector exceeds size limits\"); size *= extent; }\n"
           "    std::vector<scalar_type_t<Values>> result; result.reserve(size);\n"
           "    std::vector<std::size_t> coordinates(shape.size());\n"
           "    for (std::size_t linear = 0; linear < size; ++linear) {\n"
           "      result.push_back(selector_value_at(values, coordinates));\n"
           "      for (std::size_t axis = 0; axis < shape.size(); ++axis) { "
           "if (++coordinates[axis] < shape[axis]) break; coordinates[axis] = 0; }\n"
           "    }\n"
           "    return result;\n"
           "  }\n"
           "}\n"
           "inline std::vector<std::size_t> selector_indices(std::size_t size, "
           "const slice_selector& selector, std::size_t, bool) {\n"
           "  return slice_indices(size, selector.start, selector.stop, selector.step, "
           "selector.base, selector.allow_negative, selector.inclusive);\n"
           "}\n"
           "template <typename T> std::vector<std::size_t> selector_indices(std::size_t, "
           "const empty_selector<T>&, std::size_t, bool) { return {}; }\n"
           "template <typename T> std::vector<std::size_t> selector_indices(std::size_t size, "
           "const numeric_selector<T>& selector, std::size_t base, bool allow_negative) {\n"
           "  std::vector<std::size_t> result;\n"
           "  for (const auto value : flatten_selector_column_major(selector.values)) {\n"
           "    const auto numeric = static_cast<double>(value);\n"
           "    if (!std::isfinite(numeric) || std::trunc(numeric) != numeric || "
           "std::fabs(numeric) > 9007199254740991.0) throw std::invalid_argument("
           "\"MPF numeric selector requires safe integer values\");\n"
           "    result.push_back(normalize_index(size, static_cast<std::int64_t>(numeric), "
           "base, allow_negative));\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<std::size_t> selector_indices(std::size_t size, "
           "const logical_selector<T>& selector, std::size_t, bool) {\n"
           "  const auto flattened = flatten_selector_column_major(selector.values);\n"
           "  if (flattened.size() != size) throw std::invalid_argument("
           "\"MPF Matlab logical selector shape mismatch\");\n"
           "  std::vector<std::size_t> result;\n"
           "  for (std::size_t index = 0; index < flattened.size(); ++index) "
           "if (static_cast<bool>(flattened[index])) result.push_back(index);\n"
           "  return result;\n"
           "}\n"
           "template <std::size_t Dimension = 0, typename Values, typename Selectors> auto "
           "section_nd(const Values& values, const Selectors& selectors, std::size_t base, "
           "bool allow_negative) {\n"
           "  if constexpr (Dimension == std::tuple_size<Selectors>::value) {\n"
           "    return values;\n"
           "  } else {\n"
           "    const auto& selector = std::get<Dimension>(selectors);\n"
           "    if constexpr (is_expanding_selector<std::decay_t<decltype(selector)>>::value) {\n"
           "      using child_type = typename Values::value_type;\n"
           "      using result_type = decltype(section_nd<Dimension + 1>("
           "std::declval<const child_type&>(), selectors, base, allow_negative));\n"
           "      std::vector<result_type> result;\n"
           "      const auto indices = selector_indices(values.size(), selector, base, "
           "allow_negative);\n"
           "      result.reserve(indices.size());\n"
           "      for (const auto position : indices) result.push_back(section_nd<Dimension + "
           "1>(values.at(position), selectors, base, allow_negative));\n"
           "      return result;\n"
           "    } else {\n"
           "      return section_nd<Dimension + 1>(index(values, selector.value, base, "
           "allow_negative), selectors, base, allow_negative);\n"
           "    }\n"
           "  }\n"
           "}\n"
           "template <std::size_t Dimension = 0, typename Values, typename Selectors, "
           "typename Replacement> void assign_section_nd(Values& values, const Selectors& "
           "selectors, std::size_t base, bool allow_negative, const Replacement& replacement) {\n"
           "  if constexpr (Dimension == std::tuple_size<Selectors>::value) {\n"
           "    if constexpr (std::is_arithmetic<Values>::value && "
           "std::is_arithmetic<Replacement>::value) values = static_cast<Values>(replacement);\n"
           "    else values = replacement;\n"
           "  } else {\n"
           "    const auto& selector = std::get<Dimension>(selectors);\n"
           "    if constexpr (is_expanding_selector<std::decay_t<decltype(selector)>>::value) {\n"
           "      const auto indices = selector_indices(values.size(), selector, base, "
           "allow_negative);\n"
           "      if constexpr (is_vector<Replacement>::value) {\n"
           "        if (indices.size() != replacement.size()) throw std::invalid_argument("
           "\"MPF N-D section replacement size mismatch\");\n"
           "        for (std::size_t position = 0; position < indices.size(); ++position) "
           "assign_section_nd<Dimension + 1>(values.at(indices[position]), selectors, base, "
           "allow_negative, replacement[position]);\n"
           "      } else {\n"
           "        for (const auto position : indices) assign_section_nd<Dimension + "
           "1>(values.at(position), selectors, base, allow_negative, replacement);\n"
           "      }\n"
           "    } else {\n"
           "      assign_section_nd<Dimension + 1>(index(values, selector.value, base, "
           "allow_negative), selectors, base, allow_negative, replacement);\n"
           "    }\n"
           "  }\n"
           "}\n"
           "template <typename Values, typename Selector> auto linear_section_column_major("
           "const Values& values, const Selector& selector, std::size_t base, "
           "bool allow_negative) {\n"
           "  const auto flattened = flatten_selector_column_major(values);\n"
           "  std::vector<scalar_type_t<Values>> result;\n"
           "  const auto indices = selector_indices(flattened.size(), selector, base, "
           "allow_negative);\n"
           "  result.reserve(indices.size());\n"
           "  for (const auto index : indices) result.push_back(flattened.at(index));\n"
           "  return result;\n"
           "}\n"
           "template <typename Values, typename Selector, typename Replacement> void "
           "assign_linear_section_column_major(Values& values, const Selector& selector, "
           "std::size_t base, bool allow_negative, const Replacement& replacement) {\n"
           "  std::vector<std::size_t> shape; selector_shape(values, shape);\n"
           "  const auto size = flatten_selector_column_major(values).size();\n"
           "  const auto indices = selector_indices(size, selector, base, allow_negative);\n"
           "  if constexpr (is_vector<Replacement>::value) {\n"
           "    const auto replacements = flatten_selector_column_major(replacement);\n"
           "    if (replacements.size() != indices.size()) throw std::invalid_argument("
           "\"MPF linear section replacement size mismatch\");\n"
           "    for (std::size_t position = 0; position < indices.size(); ++position) "
           "selector_set_at(values, selector_coordinates(indices[position], shape), "
           "replacements[position]);\n"
           "  } else {\n"
           "    for (const auto index : indices) selector_set_at("
           "values, selector_coordinates(index, shape), replacement);\n"
           "  }\n"
           "}\n"
           "inline std::pair<std::size_t, std::size_t> python_slice_window("
           "std::size_t size, std::optional<std::int64_t> start_value, "
           "std::optional<std::int64_t> stop_value) {\n"
           "  const auto signed_size = static_cast<std::int64_t>(size);\n"
           "  auto start = start_value.value_or(0);\n"
           "  auto stop = stop_value.value_or(signed_size);\n"
           "  if (start < 0) start += signed_size;\n"
           "  if (stop < 0) stop += signed_size;\n"
           "  start = std::max<std::int64_t>(0, std::min(start, signed_size));\n"
           "  stop = std::max<std::int64_t>(0, std::min(stop, signed_size));\n"
           "  if (stop < start) stop = start;\n"
           "  return {static_cast<std::size_t>(start), static_cast<std::size_t>(stop)};\n"
           "}\n"
           "template <typename T, typename U> void assign_slice("
           "std::vector<T>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive, "
           "const std::vector<U>& replacement, bool python_resize) {\n"
           "  if (python_resize && step.value_or(1) == 1) {\n"
           "    const auto window = python_slice_window(values.size(), start, stop);\n"
           "    values.erase(values.begin() + static_cast<std::ptrdiff_t>(window.first), "
           "values.begin() + static_cast<std::ptrdiff_t>(window.second));\n"
           "    values.insert(values.begin() + static_cast<std::ptrdiff_t>(window.first), "
           "replacement.begin(), replacement.end());\n"
           "    return;\n"
           "  }\n"
           "  const auto indices = slice_indices(values.size(), start, stop, step, base, "
           "allow_negative, inclusive);\n"
           "  if (indices.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF section replacement size mismatch\");\n"
           "  for (std::size_t position = 0; position < indices.size(); ++position) "
           "values.at(indices[position]) = static_cast<T>(replacement[position]);\n"
           "}\n"
           "template <typename T, typename U> void assign_slice("
           "std::vector<T>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive, "
           "const U& replacement, bool) {\n"
           "  for (const auto position : slice_indices(values.size(), start, stop, step, base, "
           "allow_negative, inclusive)) values.at(position) = static_cast<T>(replacement);\n"
           "}\n"
           "template <typename T, typename U> void assign_column("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::int64_t column_position, std::size_t base, bool allow_negative, bool inclusive, "
           "const std::vector<U>& replacement) {\n"
           "  const auto rows = slice_indices(values.size(), row_start, row_stop, row_step, base, "
           "allow_negative, inclusive);\n"
           "  if (rows.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF column replacement size mismatch\");\n"
           "  for (std::size_t position = 0; position < rows.size(); ++position) "
           "index(values.at(rows[position]), column_position, base, allow_negative) = "
           "static_cast<T>(replacement[position]);\n"
           "}\n"
           "template <typename T, typename U> void assign_column("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::int64_t column_position, std::size_t base, bool allow_negative, bool inclusive, "
           "const U& replacement) {\n"
           "  for (const auto row : slice_indices(values.size(), row_start, row_stop, row_step, "
           "base, "
           "allow_negative, inclusive)) "
           "index(values.at(row), column_position, base, allow_negative) = "
           "static_cast<T>(replacement);\n"
           "}\n"
           "template <typename T, typename U> void assign_block("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::optional<std::int64_t> column_start, std::optional<std::int64_t> column_stop, "
           "std::optional<std::int64_t> column_step, std::size_t base, bool allow_negative, "
           "bool inclusive, const std::vector<std::vector<U>>& replacement) {\n"
           "  const auto rows = slice_indices(values.size(), row_start, row_stop, row_step, base, "
           "allow_negative, inclusive);\n"
           "  if (rows.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF block row count mismatch\");\n"
           "  for (std::size_t position = 0; position < rows.size(); ++position) "
           "assign_slice(values.at(rows[position]), column_start, column_stop, column_step, base, "
           "allow_negative, inclusive, replacement[position], false);\n"
           "}\n"
           "template <typename T, typename U> void assign_block("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::optional<std::int64_t> column_start, std::optional<std::int64_t> column_stop, "
           "std::optional<std::int64_t> column_step, std::size_t base, bool allow_negative, "
           "bool inclusive, const U& replacement) {\n"
           "  for (const auto row : slice_indices(values.size(), row_start, row_stop, row_step, "
           "base, "
           "allow_negative, inclusive)) "
           "assign_slice(values.at(row), column_start, column_stop, column_step, base, "
           "allow_negative, inclusive, replacement, false);\n"
           "}\n"
           "template <typename T, typename U> void assign_linear_column_major("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool inclusive, const std::vector<U>& replacement) {\n"
           "  if (values.empty()) return;\n"
           "  const auto indices = slice_indices(values.size() * values.front().size(), start, "
           "stop, "
           "step, base, false, inclusive);\n"
           "  if (indices.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF linear replacement size mismatch\");\n"
           "  for (std::size_t position = 0; position < indices.size(); ++position) {\n"
           "    const auto linear = indices[position];\n"
           "    values.at(linear % values.size()).at(linear / values.size()) = "
           "static_cast<T>(replacement[position]);\n"
           "  }\n"
           "}\n"
           "template <typename T, typename U> void assign_linear_column_major("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool inclusive, const U& replacement) {\n"
           "  if (values.empty()) return;\n"
           "  for (const auto linear : slice_indices(values.size() * values.front().size(), start, "
           "stop, "
           "step, base, false, inclusive)) "
           "values.at(linear % values.size()).at(linear / values.size()) = "
           "static_cast<T>(replacement);\n"
           "}\n"
           "template <typename T> std::vector<T> column("
           "const std::vector<std::vector<T>>& values, std::int64_t position, "
           "std::size_t base, bool allow_negative) {\n"
           "  std::vector<T> result;\n"
           "  result.reserve(values.size());\n"
           "  for (const auto& row : values) result.push_back(index(row, position, base, "
           "allow_negative));\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<std::vector<T>> columns("
           "const std::vector<std::vector<T>>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive) {\n"
           "  std::vector<std::vector<T>> result;\n"
           "  result.reserve(values.size());\n"
           "  for (const auto& row : values) "
           "result.push_back(slice(row, start, stop, step, base, allow_negative, inclusive));\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<T> flatten_column_major("
           "const std::vector<std::vector<T>>& values) {\n"
           "  std::vector<T> result;\n"
           "  if (values.empty()) return result;\n"
           "  const auto columns_count = values.front().size();\n"
           "  result.reserve(values.size() * columns_count);\n"
           "  for (std::size_t column_position = 0; column_position < columns_count; "
           "++column_position)\n"
           "    for (const auto& row : values) {\n"
           "      if (row.size() != columns_count) "
           "throw std::invalid_argument(\"MPF matrix must be rectangular\");\n"
           "      result.push_back(row.at(column_position));\n"
           "    }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> T& matrix_linear_index(std::vector<std::vector<T>>& values, "
           "std::int64_t position, std::size_t base) {\n"
           "  if (values.empty() || values.front().empty()) "
           "throw std::out_of_range(\"MPF index out of bounds\");\n"
           "  const auto rows = values.size();\n"
           "  const auto columns = values.front().size();\n"
           "  const auto linear = normalize_index(rows * columns, position, base, false);\n"
           "  return values.at(linear % rows).at(linear / rows);\n"
           "}\n"
           "template <typename T> const T& matrix_linear_index("
           "const std::vector<std::vector<T>>& values, std::int64_t position, std::size_t base) {\n"
           "  if (values.empty() || values.front().empty()) "
           "throw std::out_of_range(\"MPF index out of bounds\");\n"
           "  const auto rows = values.size();\n"
           "  const auto columns = values.front().size();\n"
           "  const auto linear = normalize_index(rows * columns, position, base, false);\n"
           "  return values.at(linear % rows).at(linear / rows);\n"
           "}\n"
           "template <typename T> T sum_value(const T& value) { return value; }\n"
           "template <typename T> scalar_type_t<std::vector<T>> "
           "sum_value(const std::vector<T>& values) {\n"
           "  scalar_type_t<std::vector<T>> total{};\n"
           "  for (const auto& value : values) total += sum_value(value);\n"
           "  return total;\n"
           "}\n"
           "template <typename T> scalar_type_t<std::vector<T>> sum(const std::vector<T>& values) "
           "{\n"
           "  return sum_value(values);\n"
           "}\n"
           "template <typename T> std::size_t numel_value(const T&) { return 1; }\n"
           "template <typename T> std::size_t numel_value(const std::vector<T>& values) {\n"
           "  std::size_t total = 0;\n"
           "  for (const auto& value : values) total += numel_value(value);\n"
           "  return total;\n"
           "}\n"
           "template <typename T> std::size_t numel(const std::vector<T>& values) {\n"
           "  return numel_value(values);\n"
           "}\n"
           "template <typename T> void append_shape(const T&, std::vector<std::size_t>&) {}\n"
           "template <typename T> void append_shape(const std::vector<T>& values, "
           "std::vector<std::size_t>& shape) {\n"
           "  shape.push_back(values.size());\n"
           "  if (!values.empty()) append_shape(values.front(), shape);\n"
           "}\n"
           "template <typename T> std::size_t length(const std::vector<T>& values) {\n"
           "  std::vector<std::size_t> shape;\n"
           "  append_shape(values, shape);\n"
           "  return shape.empty() ? 0 : *std::max_element(shape.begin(), shape.end());\n"
           "}\n"
           "template <typename T, std::size_t Rank> struct nested_vector {\n"
           "  using type = std::vector<typename nested_vector<T, Rank - 1>::type>;\n"
           "};\n"
           "template <typename T> struct nested_vector<T, 0> { using type = T; };\n"
           "template <typename T, std::size_t Rank> using nested_vector_t = "
           "typename nested_vector<T, Rank>::type;\n"
           "template <std::size_t Dimension, std::size_t Rank, typename Scalar> auto "
           "make_nested(const std::array<std::size_t, Rank>& shape) {\n"
           "  if constexpr (Dimension == Rank) {\n"
           "    return Scalar{};\n"
           "  } else {\n"
           "    auto child = make_nested<Dimension + 1, Rank, Scalar>(shape);\n"
           "    return std::vector<decltype(child)>(shape[Dimension], child);\n"
           "  }\n"
           "}\n"
           "template <typename Values, typename Coordinates> scalar_type_t<Values>& nd_at("
           "Values& values, const Coordinates& coordinates, std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) {\n"
           "    return nd_at(values.at(coordinates.at(dimension)), coordinates, dimension + 1);\n"
           "  } else {\n"
           "    return values;\n"
           "  }\n"
           "}\n"
           "template <typename Values, typename Coordinates> const scalar_type_t<Values>& nd_at("
           "const Values& values, const Coordinates& coordinates, "
           "std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) {\n"
           "    return nd_at(values.at(coordinates.at(dimension)), coordinates, dimension + 1);\n"
           "  } else {\n"
           "    return values;\n"
           "  }\n"
           "}\n"
           "template <typename Values, typename Coordinates> auto nd_value(const Values& values, "
           "const Coordinates& coordinates, std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) {\n"
           "    return nd_value(values.at(coordinates.at(dimension)), coordinates, dimension + "
           "1);\n"
           "  } else {\n"
           "    return values;\n"
           "  }\n"
           "}\n"
           "template <typename Values, typename Coordinates, typename Scalar> void nd_set("
           "Values& values, const Coordinates& coordinates, const Scalar& value, "
           "std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<typename Values::value_type>::value) {\n"
           "    nd_set(values.at(coordinates.at(dimension)), coordinates, value, dimension + 1);\n"
           "  } else {\n"
           "    values.at(coordinates.at(dimension)) = value;\n"
           "  }\n"
           "}\n"
           "template <std::size_t Rank> std::size_t shape_size("
           "const std::array<std::size_t, Rank>& shape) {\n"
           "  std::size_t result = 1;\n"
           "  for (const auto extent : shape) {\n"
           "    if (extent == 0) return 0;\n"
           "    if (result > std::numeric_limits<std::size_t>::max() / extent) "
           "throw std::length_error(\"MPF array shape exceeds size limits\");\n"
           "    result *= extent;\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <std::size_t Rank> std::array<std::size_t, Rank> "
           "column_major_coordinates(std::size_t linear, "
           "const std::array<std::size_t, Rank>& shape) {\n"
           "  std::array<std::size_t, Rank> result{};\n"
           "  for (std::size_t axis = 0; axis < Rank; ++axis) { "
           "result[axis] = linear % shape[axis]; linear /= shape[axis]; }\n"
           "  return result;\n"
           "}\n"
           "template <typename Values, std::size_t SourceRank, std::size_t TargetRank> auto "
           "reshape_column_major_nd(const Values& values, "
           "const std::array<std::size_t, SourceRank>& source_shape, "
           "const std::array<std::size_t, TargetRank>& target_shape) {\n"
           "  static_assert(SourceRank > 0 && TargetRank > 0, \"MPF RESHAPE rank must be "
           "positive\");\n"
           "  const auto source_size = shape_size(source_shape);\n"
           "  if (source_size != shape_size(target_shape)) "
           "throw std::invalid_argument(\"MPF RESHAPE size mismatch\");\n"
           "  auto result = make_nested<0, TargetRank, scalar_type_t<Values>>(target_shape);\n"
           "  for (std::size_t linear = 0; linear < source_size; ++linear) {\n"
           "    nd_set(result, column_major_coordinates(linear, target_shape), "
           "nd_value(values, column_major_coordinates(linear, source_shape)));\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> struct vector_rank : std::integral_constant<std::size_t, 0> "
           "{};\n"
           "template <typename T> struct vector_rank<std::vector<T>> "
           ": std::integral_constant<std::size_t, 1 + vector_rank<T>::value> {};\n"
           "template <std::size_t Rank, std::size_t Axis, typename Values> auto "
           "matlab_broadcast_at_impl(const Values& values, "
           "const std::array<std::size_t, Rank>& coordinates, "
           "const std::array<std::size_t, Rank>& shape) {\n"
           "  if constexpr (is_vector<std::decay_t<Values>>::value) {\n"
           "    constexpr auto value_rank = vector_rank<std::decay_t<Values>>::value;\n"
           "    static_assert(value_rank <= Rank, \"MPF broadcast rank contract is invalid\");\n"
           "    constexpr auto axis = Axis == 0 && value_rank == 1 && Rank >= 2 ? 1 : Axis;\n"
           "    static_assert(axis < Rank, \"MPF broadcast axis contract is invalid\");\n"
           "    const auto position = shape[axis] == 1 ? 0 : coordinates.at(axis);\n"
           "    return matlab_broadcast_at_impl<Rank, axis + 1>(values.at(position), "
           "coordinates, shape);\n"
           "  } else {\n"
           "    return values;\n"
           "  }\n"
           "}\n"
           "template <std::size_t Rank, typename Values> auto matlab_broadcast_at("
           "const Values& values, const std::array<std::size_t, Rank>& coordinates, "
           "const std::array<std::size_t, Rank>& shape) {\n"
           "  return matlab_broadcast_at_impl<Rank, 0>(values, coordinates, shape);\n"
           "}\n"
           "template <typename Left, typename Right, std::size_t Rank, typename Operation> auto "
           "matlab_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape, Operation operation) {\n"
           "  static_assert(Rank > 0, \"MPF broadcast rank must be positive\");\n"
           "  for (std::size_t axis = 0; axis < Rank; ++axis) {\n"
           "    const auto l = left_shape[axis]; const auto r = right_shape[axis];\n"
           "    if (l != r && l != 1 && r != 1) throw std::invalid_argument("
           "\"MPF Matlab broadcast sizes are incompatible\");\n"
           "    const auto expected = l == 1 ? r : l;\n"
           "    if (result_shape[axis] != expected) throw std::invalid_argument("
           "\"MPF Matlab broadcast result shape is invalid\");\n"
           "  }\n"
           "  using result_scalar = std::decay_t<decltype(operation("
           "std::declval<const scalar_type_t<Left>&>(), "
           "std::declval<const scalar_type_t<Right>&>()))>;\n"
           "  auto result = make_nested<0, Rank, result_scalar>(result_shape);\n"
           "  const auto size = shape_size(result_shape);\n"
           "  for (std::size_t linear = 0; linear < size; ++linear) {\n"
           "    const auto coordinates = column_major_coordinates(linear, result_shape);\n"
           "    nd_set(result, coordinates, operation("
           "matlab_broadcast_at<Rank>(left, coordinates, left_shape), "
           "matlab_broadcast_at<Rank>(right, coordinates, right_shape)));\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_add_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a + b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_subtract_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a - b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_multiply_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a * b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_divide_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return static_cast<double>(a) / "
           "static_cast<double>(b); }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_left_divide_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return static_cast<double>(b) / "
           "static_cast<double>(a); }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_power_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return std::pow(static_cast<double>(a), "
           "static_cast<double>(b)); }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_equal_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a == b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_not_equal_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a != b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_less_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a < b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_less_equal_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a <= b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_greater_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a > b; }); }\n"
           "template <typename Left, typename Right, std::size_t Rank> auto "
           "matlab_greater_equal_broadcast(const Left& left, const Right& right, "
           "const std::array<std::size_t, Rank>& left_shape, "
           "const std::array<std::size_t, Rank>& right_shape, "
           "const std::array<std::size_t, Rank>& result_shape) { return matlab_broadcast("
           "left, right, left_shape, right_shape, result_shape, "
           "[](const auto& a, const auto& b) { return a >= b; }); }\n";
    if (include_python_runtime) {
      output_
          << "template <typename Left, typename Right, typename Operation> bool py_compare(\n"
             "    const Left& left, const Right& right, Operation operation) {\n"
             "  if constexpr (std::is_arithmetic<std::decay_t<Left>>::value &&\n"
             "                std::is_arithmetic<std::decay_t<Right>>::value) {\n"
             "    using Common = std::common_type_t<std::decay_t<Left>, "
             "std::decay_t<Right>>;\n"
             "    return operation(static_cast<Common>(left), static_cast<Common>(right));\n"
             "  } else {\n"
             "    return operation(left, right);\n"
             "  }\n"
             "}\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const Left& left, const Right& right);\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const std::vector<Left>& left, const std::vector<Right>& right);\n"
             "template <typename... Left, typename... Right> bool py_equal(\n"
             "    const std::tuple<Left...>& left, const std::tuple<Right...>& right);\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const Left& left, const Right& right) {\n"
             "  using LeftType = std::decay_t<Left>;\n"
             "  using RightType = std::decay_t<Right>;\n"
             "  if constexpr (std::is_arithmetic<LeftType>::value &&\n"
             "                std::is_arithmetic<RightType>::value) {\n"
             "    using Common = std::common_type_t<LeftType, RightType>;\n"
             "    return static_cast<Common>(left) == static_cast<Common>(right);\n"
             "  } else if constexpr (std::is_same<LeftType, RightType>::value) {\n"
             "    return left == right;\n"
             "  } else {\n"
             "    return false;\n"
             "  }\n"
             "}\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const std::vector<Left>& left, const std::vector<Right>& right) {\n"
             "  if (left.size() != right.size()) return false;\n"
             "  for (std::size_t index = 0; index < left.size(); ++index) {\n"
             "    if constexpr (std::is_same<Left, bool>::value || "
             "std::is_same<Right, bool>::value) {\n"
             "      if (!py_equal(static_cast<Left>(left[index]), "
             "static_cast<Right>(right[index]))) return false;\n"
             "    } else if (!py_equal(left[index], right[index])) {\n"
             "      return false;\n"
             "    }\n"
             "  }\n"
             "  return true;\n"
             "}\n"
             "template <typename LeftTuple, typename RightTuple, std::size_t... Index>\n"
             "bool py_tuple_equal(const LeftTuple& left, const RightTuple& right,\n"
             "                    std::index_sequence<Index...>) {\n"
             "  return (true && ... && py_equal(std::get<Index>(left), "
             "std::get<Index>(right)));\n"
             "}\n"
             "template <typename... Left, typename... Right> bool py_equal(\n"
             "    const std::tuple<Left...>& left, const std::tuple<Right...>& right) {\n"
             "  if constexpr (sizeof...(Left) != sizeof...(Right)) {\n"
             "    return false;\n"
             "  } else {\n"
             "    return py_tuple_equal(left, right, std::index_sequence_for<Left...>{});\n"
             "  }\n"
             "}\n"
             "template <typename Left, typename Right> bool py_is(\n"
             "    const Left& left, const Right& right) {\n"
             "  using LeftType = std::decay_t<Left>;\n"
             "  using RightType = std::decay_t<Right>;\n"
             "  if constexpr (std::is_same<LeftType, std::nullptr_t>::value &&\n"
             "                std::is_same<RightType, std::nullptr_t>::value) {\n"
             "    return true;\n"
             "  } else if constexpr (std::is_same<LeftType, bool>::value &&\n"
             "                       std::is_same<RightType, bool>::value) {\n"
             "    return left == right;\n"
             "  } else {\n"
             "    return false;\n"
             "  }\n"
             "}\n"
             "inline bool py_contains(const std::string& container, const std::string& value) {\n"
             "  return container.find(value) != std::string::npos;\n"
             "}\n"
             "template <typename T, typename Value> bool py_contains(\n"
             "    const std::vector<T>& container, const Value& value) {\n"
             "  return std::any_of(container.begin(), container.end(),\n"
             "                     [&](const auto& element) { return py_equal(element, value); "
             "});\n"
             "}\n"
             "template <typename... T, typename Value> bool py_contains(\n"
             "    const std::tuple<T...>& container, const Value& value) {\n"
             "  return std::apply([&](const auto&... element) {\n"
             "    return (false || ... || py_equal(element, value));\n"
             "  }, container);\n"
             "}\n"
             "inline bool truthy(std::nullptr_t) { return false; }\n"
             "inline bool truthy(bool value) { return value; }\n"
             "template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>> "
             "bool truthy(T value) { return value != static_cast<T>(0); }\n"
             "inline bool truthy(const std::string& value) { return !value.empty(); }\n"
             "template <typename T> bool truthy(const std::vector<T>& value) { return "
             "!value.empty(); }\n"
             "template <typename... T> bool truthy(const std::tuple<T...>&) { return sizeof...(T) "
             "!= 0; }\n"
             "template <typename T> bool py_not(const T& value) { return !truthy(value); }\n"
             "template <typename LeftFunction, typename RightFunction> auto py_and("
             "LeftFunction&& left_function, RightFunction&& right_function) {\n"
             "  auto left = left_function();\n"
             "  using Result = std::common_type_t<std::decay_t<decltype(left)>, "
             "std::decay_t<decltype(right_function())>>;\n"
             "  if (!truthy(left)) return static_cast<Result>(left);\n"
             "  return static_cast<Result>(right_function());\n"
             "}\n"
             "template <typename LeftFunction, typename RightFunction> auto py_or("
             "LeftFunction&& left_function, RightFunction&& right_function) {\n"
             "  auto left = left_function();\n"
             "  using Result = std::common_type_t<std::decay_t<decltype(left)>, "
             "std::decay_t<decltype(right_function())>>;\n"
             "  if (truthy(left)) return static_cast<Result>(left);\n"
             "  return static_cast<Result>(right_function());\n"
             "}\n"
             "template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>> "
             "double py_float(T value) { return static_cast<double>(value); }\n"
             "inline double py_float(const std::string& value) {\n"
             "  std::size_t consumed = 0;\n"
             "  const auto result = std::stod(value, &consumed);\n"
             "  if (value.find_first_not_of(\" \\t\\n\\r\\f\\v\", consumed) != std::string::npos) "
             "throw std::invalid_argument(\"MPF float string is invalid\");\n"
             "  return result;\n"
             "}\n";
    }
    output_ << "}  // namespace " << runtime_namespace << "\n\n";
  }

 private:
  std::ostream& output_;
};

}  // namespace

void emit_cpp_runtime(std::ostream& output, const std::string_view runtime_namespace,
                      const std::vector<cpp::lir::RuntimeFragment>& fragments) {
  RuntimeEmitter(output).emit(runtime_namespace, fragments);
}

}  // namespace mpf::detail
