#include "runtime.hpp"

#include <algorithm>
#include <ostream>

namespace mpf::detail {
namespace {

class RuntimeEmitter final {
 public:
  explicit RuntimeEmitter(std::ostream& output) : output_(output) {}

  void emit(const std::string_view runtime_namespace,
            const std::vector<cpp::lir::RuntimeFragment>& fragments) {
    const bool include_python_runtime =
        std::find(fragments.begin(), fragments.end(), cpp::lir::RuntimeFragment::dynamic_values) !=
        fragments.end();
    output_ << "namespace " << runtime_namespace << " {\n";
    output_
        << "template <typename T> class optional_argument {\n"
           " public:\n"
           "  optional_argument() = default;\n"
           "  optional_argument(std::nullopt_t) noexcept {}\n"
           "  optional_argument(T& value) noexcept : pointer_(&value) {}\n"
           "  optional_argument(const T& value) : owned_(value), pointer_(&owned_.value()) {}\n"
           "  optional_argument(T&& value) : owned_(std::move(value)), pointer_(&owned_.value()) "
           "{}\n"
           "  optional_argument(const optional_argument& other) : owned_(other.owned_) {\n"
           "    pointer_ = other.owns_value() ? &owned_.value() : other.pointer_;\n"
           "  }\n"
           "  optional_argument(optional_argument&& other) {\n"
           "    const bool owned = other.owns_value();\n"
           "    owned_ = std::move(other.owned_);\n"
           "    pointer_ = owned ? &owned_.value() : other.pointer_;\n"
           "  }\n"
           "  optional_argument& operator=(const optional_argument& other) {\n"
           "    if (this == &other) return *this;\n"
           "    const bool owned = other.owns_value();\n"
           "    owned_ = other.owned_;\n"
           "    pointer_ = owned ? &owned_.value() : other.pointer_;\n"
           "    return *this;\n"
           "  }\n"
           "  optional_argument& operator=(optional_argument&& other) {\n"
           "    if (this == &other) return *this;\n"
           "    const bool owned = other.owns_value();\n"
           "    owned_ = std::move(other.owned_);\n"
           "    pointer_ = owned ? &owned_.value() : other.pointer_;\n"
           "    return *this;\n"
           "  }\n"
           "  bool has_value() const noexcept { return pointer_ != nullptr; }\n"
           "  T& value() { if (pointer_ == nullptr) throw std::bad_optional_access{}; return "
           "*pointer_; }\n"
           "  const T& value() const {\n"
           "    if (pointer_ == nullptr) throw std::bad_optional_access{};\n"
           "    return *pointer_;\n"
           "  }\n"
           " private:\n"
           "  bool owns_value() const noexcept {\n"
           "    return owned_.has_value() && pointer_ == &owned_.value();\n"
           "  }\n"
           "  std::optional<T> owned_;\n"
           "  T* pointer_{nullptr};\n"
           "};\n\n"
           "template <typename T> void print_value(const T& value);\n"
           "template <typename T> void print_value(const std::vector<T>& values);\n"
           "template <typename... T> void print_value(const std::tuple<T...>& values);\n\n"
           "template <typename T> void print_value(const T& value) { std::cout << value; }\n"
           "template <typename T> void print_value(const std::vector<T>& values) {\n"
           "  std::cout << '[';\n"
           "  bool first = true;\n"
           "  for (const auto& value : values) {\n"
           "    if (!first) std::cout << \", \";\n"
           "    print_value(value);\n"
           "    first = false;\n"
           "  }\n"
           "  std::cout << ']';\n"
           "}\n"
           "template <typename... T> void print_value(const std::tuple<T...>& values) {\n"
           "  std::cout << '(';\n"
           "  bool first = true;\n"
           "  std::apply([&](const auto&... value) {\n"
           "    ((std::cout << (first ? \"\" : \", \"), print_value(value), first = false), ...);\n"
           "  }, values);\n"
           "  std::cout << ')';\n"
           "}\n"
           "inline void print() { std::cout << '\\n'; }\n"
           "template <typename... T> void print(const T&... value) {\n"
           "  bool first = true;\n"
           "  ((std::cout << (first ? \"\" : \" \"), print_value(value), first = false), ...);\n"
           "  std::cout << '\\n';\n"
           "}\n"
           "template <typename Cursor, typename Stop, typename Step> bool range_continue(\n"
           "    const Cursor& cursor, const Stop& stop, const Step& step, bool inclusive) {\n"
           "  if (step >= static_cast<Step>(0)) return inclusive ? cursor <= stop : cursor < "
           "stop;\n"
           "  return inclusive ? cursor >= stop : cursor > stop;\n"
           "}\n"
           "template <typename Cursor, typename Stop, typename Step> bool range_next(\n"
           "    Cursor& cursor, const Stop& stop, const Step& step, bool inclusive, bool& "
           "first) {\n"
           "  if (first)\n"
           "    first = false;\n"
           "  else\n"
           "    cursor += step;\n"
           "  return range_continue(cursor, stop, step, inclusive);\n"
           "}\n"
           "inline int fortran_compare(const std::string& left, const std::string& right) {\n"
           "  const auto width = std::max(left.size(), right.size());\n"
           "  for (std::size_t index = 0; index < width; ++index) {\n"
           "    const auto left_character = static_cast<unsigned char>(index < left.size() ? "
           "left[index] : ' ');\n"
           "    const auto right_character = static_cast<unsigned char>(index < right.size() ? "
           "right[index] : ' ');\n"
           "    if (left_character < right_character) return -1;\n"
           "    if (left_character > right_character) return 1;\n"
           "  }\n"
           "  return 0;\n"
           "}\n"
           "inline std::size_t normalize_index(std::size_t size, std::int64_t index, "
           "std::size_t base, bool allow_negative) {\n"
           "  std::int64_t normalized = index - static_cast<std::int64_t>(base);\n"
           "  if (allow_negative && index < 0) normalized = static_cast<std::int64_t>(size) + "
           "index;\n"
           "  if (normalized < 0 || static_cast<std::size_t>(normalized) >= size) "
           "throw std::out_of_range(\"MPF index out of bounds\");\n"
           "  return static_cast<std::size_t>(normalized);\n"
           "}\n"
           "template <typename T> T& index(std::vector<T>& values, std::int64_t position, "
           "std::size_t base, bool allow_negative) {\n"
           "  return values.at(normalize_index(values.size(), position, base, allow_negative));\n"
           "}\n"
           "template <typename T> const T& index(const std::vector<T>& values, "
           "std::int64_t position, std::size_t base, bool allow_negative) {\n"
           "  return values.at(normalize_index(values.size(), position, base, allow_negative));\n"
           "}\n"
           "inline std::vector<std::size_t> slice_indices("
           "std::size_t size, std::optional<std::int64_t> start_value, "
           "std::optional<std::int64_t> stop_value, std::optional<std::int64_t> step_value, "
           "std::size_t base, bool allow_negative, bool inclusive) {\n"
           "  const auto step = step_value.value_or(1);\n"
           "  if (step == 0) throw std::invalid_argument(\"MPF slice step cannot be zero\");\n"
           "  std::vector<std::size_t> result;\n"
           "  if (size == 0) return result;\n"
           "  if (size > static_cast<std::size_t>(std::numeric_limits<std::int64_t>::max())) "
           "throw std::length_error(\"MPF array exceeds signed index range\");\n"
           "  const auto signed_size = static_cast<std::int64_t>(size);\n"
           "  if (!inclusive) {\n"
           "    auto start = start_value.value_or(step > 0 ? 0 : signed_size - 1);\n"
           "    auto stop = stop_value.value_or(step > 0 ? signed_size : -1);\n"
           "    if (start_value.has_value() && start < 0) start += signed_size;\n"
           "    if (stop_value.has_value() && stop < 0) stop += signed_size;\n"
           "    if (step > 0) {\n"
           "      start = std::max<std::int64_t>(0, std::min(start, signed_size));\n"
           "      stop = std::max<std::int64_t>(0, std::min(stop, signed_size));\n"
           "      for (auto position = start; position < stop; position += step) "
           "result.push_back(static_cast<std::size_t>(position));\n"
           "    } else {\n"
           "      start = std::max<std::int64_t>(-1, std::min(start, signed_size - 1));\n"
           "      stop = std::max<std::int64_t>(-1, std::min(stop, signed_size - 1));\n"
           "      for (auto position = start; position > stop; position += step) "
           "result.push_back(static_cast<std::size_t>(position));\n"
           "    }\n"
           "    return result;\n"
           "  }\n"
           "  auto position = start_value.value_or("
           "step > 0 ? static_cast<std::int64_t>(base) "
           ": static_cast<std::int64_t>(base + size - 1));\n"
           "  const auto stop = stop_value.value_or("
           "step > 0 ? static_cast<std::int64_t>(base + size - 1) "
           ": static_cast<std::int64_t>(base));\n"
           "  while (step > 0 ? position <= stop : position >= stop) {\n"
           "    result.push_back(normalize_index(size, position, base, allow_negative));\n"
           "    if (result.size() > size) throw std::out_of_range(\"MPF slice exceeds array "
           "extent\");\n"
           "    if ((step > 0 && position > std::numeric_limits<std::int64_t>::max() - step) ||\n"
           "        (step < 0 && position < std::numeric_limits<std::int64_t>::min() - step)) "
           "break;\n"
           "    position += step;\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<T> slice("
           "const std::vector<T>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive) {\n"
           "  std::vector<T> result;\n"
           "  for (const auto position : slice_indices(values.size(), start, stop, step, base, "
           "allow_negative, inclusive)) result.push_back(values.at(position));\n"
           "  return result;\n"
           "}\n"
           "template <typename T> struct is_vector : std::false_type {};\n"
           "template <typename T> struct is_vector<std::vector<T>> : std::true_type {};\n"
           "template <typename Left, typename Right, typename Operation> auto "
           "matlab_elementwise(const Left& left, const Right& right, Operation operation) {\n"
           "  if constexpr (is_vector<std::decay_t<Left>>::value && "
           "is_vector<std::decay_t<Right>>::value) {\n"
           "    if (left.size() != right.size()) throw std::invalid_argument(\"MPF Matlab "
           "element-wise shape mismatch\");\n"
           "    using result_type = decltype(matlab_elementwise("
           "std::declval<const typename std::decay_t<Left>::value_type&>(), "
           "std::declval<const typename std::decay_t<Right>::value_type&>(), operation));\n"
           "    std::vector<result_type> result; result.reserve(left.size());\n"
           "    for (std::size_t index = 0; index < left.size(); ++index) "
           "result.push_back(matlab_elementwise(left[index], right[index], operation));\n"
           "    return result;\n"
           "  } else if constexpr (is_vector<std::decay_t<Left>>::value) {\n"
           "    using result_type = decltype(matlab_elementwise("
           "std::declval<const typename std::decay_t<Left>::value_type&>(), right, operation));\n"
           "    std::vector<result_type> result; result.reserve(left.size());\n"
           "    for (const auto& value : left) "
           "result.push_back(matlab_elementwise(value, right, operation));\n"
           "    return result;\n"
           "  } else if constexpr (is_vector<std::decay_t<Right>>::value) {\n"
           "    using result_type = decltype(matlab_elementwise("
           "left, std::declval<const typename std::decay_t<Right>::value_type&>(), operation));\n"
           "    std::vector<result_type> result; result.reserve(right.size());\n"
           "    for (const auto& value : right) "
           "result.push_back(matlab_elementwise(left, value, operation));\n"
           "    return result;\n"
           "  } else {\n"
           "    return operation(left, right);\n"
           "  }\n"
           "}\n"
           "template <typename Left, typename Right> auto matlab_add(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return a + b; }); }\n"
           "template <typename Left, typename Right> auto matlab_subtract(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, const "
           "auto& b) { return a - b; }); }\n"
           "template <typename Left, typename Right> auto matlab_multiply(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, const "
           "auto& b) { return a * b; }); }\n"
           "template <typename Left, typename Right> auto matlab_divide(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return static_cast<double>(a) / static_cast<double>(b); }); }\n"
           "template <typename Left, typename Right> auto matlab_left_divide(const Left& left, "
           "const Right& right) { return matlab_elementwise(left, right, [](const auto& a, const "
           "auto& b) { return static_cast<double>(b) / static_cast<double>(a); }); }\n"
           "template <typename Left, typename Right> auto matlab_power(const Left& left, const "
           "Right& right) { return matlab_elementwise(left, right, [](const auto& a, const auto& "
           "b) { return std::pow(static_cast<double>(a), static_cast<double>(b)); }); }\n"
           "template <typename Left, typename Right> auto matlab_mtimes("
           "const std::vector<std::vector<Left>>& left, "
           "const std::vector<std::vector<Right>>& right) {\n"
           "  if (left.empty() || right.empty() || left.front().empty() || "
           "right.front().empty()) throw std::invalid_argument(\"MPF Matlab matrix "
           "multiplication requires non-empty rank-2 arrays\");\n"
           "  const auto left_columns = left.front().size();\n"
           "  const auto right_columns = right.front().size();\n"
           "  for (const auto& row : left) if (row.size() != left_columns) "
           "throw std::invalid_argument(\"MPF Matlab matrix must be rectangular\");\n"
           "  for (const auto& row : right) if (row.size() != right_columns) "
           "throw std::invalid_argument(\"MPF Matlab matrix must be rectangular\");\n"
           "  if (left_columns != right.size()) throw std::invalid_argument(\"MPF Matlab "
           "matrix multiplication shape mismatch\");\n"
           "  using result_type = std::decay_t<decltype(std::declval<Left>() * "
           "std::declval<Right>())>;\n"
           "  std::vector<std::vector<result_type>> result("
           "left.size(), std::vector<result_type>(right_columns));\n"
           "  for (std::size_t row = 0; row < left.size(); ++row) "
           "for (std::size_t column = 0; column < right_columns; ++column) "
           "for (std::size_t inner = 0; inner < left_columns; ++inner) "
           "result[row][column] += left[row][inner] * right[inner][column];\n"
           "  return result;\n"
           "}\n"
           "struct scalar_selector { std::int64_t value; };\n"
           "struct slice_selector {\n"
           "  std::optional<std::int64_t> start;\n"
           "  std::optional<std::int64_t> stop;\n"
           "  std::optional<std::int64_t> step;\n"
           "  std::size_t base; bool allow_negative; bool inclusive;\n"
           "};\n"
           "template <typename T> struct is_slice_selector : std::false_type {};\n"
           "template <> struct is_slice_selector<slice_selector> : std::true_type {};\n"
           "template <std::size_t Dimension = 0, typename Values, typename Selectors> auto "
           "section_nd(const Values& values, const Selectors& selectors, std::size_t base, "
           "bool allow_negative) {\n"
           "  if constexpr (Dimension == std::tuple_size<Selectors>::value) {\n"
           "    return values;\n"
           "  } else {\n"
           "    const auto& selector = std::get<Dimension>(selectors);\n"
           "    if constexpr (is_slice_selector<std::decay_t<decltype(selector)>>::value) {\n"
           "      using child_type = typename Values::value_type;\n"
           "      using result_type = decltype(section_nd<Dimension + 1>("
           "std::declval<const child_type&>(), selectors, base, allow_negative));\n"
           "      std::vector<result_type> result;\n"
           "      const auto indices = slice_indices(values.size(), selector.start, "
           "selector.stop, selector.step, selector.base, selector.allow_negative, "
           "selector.inclusive);\n"
           "      result.reserve(indices.size());\n"
           "      for (const auto position : indices) result.push_back(section_nd<Dimension + "
           "1>(values.at(position), selectors, base, allow_negative));\n"
           "      return result;\n"
           "    } else {\n"
           "      return section_nd<Dimension + 1>(index(values, selector.value, base, "
           "allow_negative), selectors, base, allow_negative);\n"
           "    }\n"
           "  }\n"
           "}\n"
           "template <std::size_t Dimension = 0, typename Values, typename Selectors, "
           "typename Replacement> void assign_section_nd(Values& values, const Selectors& "
           "selectors, std::size_t base, bool allow_negative, const Replacement& replacement) {\n"
           "  if constexpr (Dimension == std::tuple_size<Selectors>::value) {\n"
           "    if constexpr (std::is_arithmetic<Values>::value && "
           "std::is_arithmetic<Replacement>::value) values = static_cast<Values>(replacement);\n"
           "    else values = replacement;\n"
           "  } else {\n"
           "    const auto& selector = std::get<Dimension>(selectors);\n"
           "    if constexpr (is_slice_selector<std::decay_t<decltype(selector)>>::value) {\n"
           "      const auto indices = slice_indices(values.size(), selector.start, "
           "selector.stop, selector.step, selector.base, selector.allow_negative, "
           "selector.inclusive);\n"
           "      if constexpr (is_vector<Replacement>::value) {\n"
           "        if (indices.size() != replacement.size()) throw std::invalid_argument("
           "\"MPF N-D section replacement size mismatch\");\n"
           "        for (std::size_t position = 0; position < indices.size(); ++position) "
           "assign_section_nd<Dimension + 1>(values.at(indices[position]), selectors, base, "
           "allow_negative, replacement[position]);\n"
           "      } else {\n"
           "        for (const auto position : indices) assign_section_nd<Dimension + "
           "1>(values.at(position), selectors, base, allow_negative, replacement);\n"
           "      }\n"
           "    } else {\n"
           "      assign_section_nd<Dimension + 1>(index(values, selector.value, base, "
           "allow_negative), selectors, base, allow_negative, replacement);\n"
           "    }\n"
           "  }\n"
           "}\n"
           "inline std::pair<std::size_t, std::size_t> python_slice_window("
           "std::size_t size, std::optional<std::int64_t> start_value, "
           "std::optional<std::int64_t> stop_value) {\n"
           "  const auto signed_size = static_cast<std::int64_t>(size);\n"
           "  auto start = start_value.value_or(0);\n"
           "  auto stop = stop_value.value_or(signed_size);\n"
           "  if (start < 0) start += signed_size;\n"
           "  if (stop < 0) stop += signed_size;\n"
           "  start = std::max<std::int64_t>(0, std::min(start, signed_size));\n"
           "  stop = std::max<std::int64_t>(0, std::min(stop, signed_size));\n"
           "  if (stop < start) stop = start;\n"
           "  return {static_cast<std::size_t>(start), static_cast<std::size_t>(stop)};\n"
           "}\n"
           "template <typename T, typename U> void assign_slice("
           "std::vector<T>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive, "
           "const std::vector<U>& replacement, bool python_resize) {\n"
           "  if (python_resize && step.value_or(1) == 1) {\n"
           "    const auto window = python_slice_window(values.size(), start, stop);\n"
           "    values.erase(values.begin() + static_cast<std::ptrdiff_t>(window.first), "
           "values.begin() + static_cast<std::ptrdiff_t>(window.second));\n"
           "    values.insert(values.begin() + static_cast<std::ptrdiff_t>(window.first), "
           "replacement.begin(), replacement.end());\n"
           "    return;\n"
           "  }\n"
           "  const auto indices = slice_indices(values.size(), start, stop, step, base, "
           "allow_negative, inclusive);\n"
           "  if (indices.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF section replacement size mismatch\");\n"
           "  for (std::size_t position = 0; position < indices.size(); ++position) "
           "values.at(indices[position]) = static_cast<T>(replacement[position]);\n"
           "}\n"
           "template <typename T, typename U> void assign_slice("
           "std::vector<T>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive, "
           "const U& replacement, bool) {\n"
           "  for (const auto position : slice_indices(values.size(), start, stop, step, base, "
           "allow_negative, inclusive)) values.at(position) = static_cast<T>(replacement);\n"
           "}\n"
           "template <typename T, typename U> void assign_column("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::int64_t column_position, std::size_t base, bool allow_negative, bool inclusive, "
           "const std::vector<U>& replacement) {\n"
           "  const auto rows = slice_indices(values.size(), row_start, row_stop, row_step, base, "
           "allow_negative, inclusive);\n"
           "  if (rows.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF column replacement size mismatch\");\n"
           "  for (std::size_t position = 0; position < rows.size(); ++position) "
           "index(values.at(rows[position]), column_position, base, allow_negative) = "
           "static_cast<T>(replacement[position]);\n"
           "}\n"
           "template <typename T, typename U> void assign_column("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::int64_t column_position, std::size_t base, bool allow_negative, bool inclusive, "
           "const U& replacement) {\n"
           "  for (const auto row : slice_indices(values.size(), row_start, row_stop, row_step, "
           "base, "
           "allow_negative, inclusive)) "
           "index(values.at(row), column_position, base, allow_negative) = "
           "static_cast<T>(replacement);\n"
           "}\n"
           "template <typename T, typename U> void assign_block("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::optional<std::int64_t> column_start, std::optional<std::int64_t> column_stop, "
           "std::optional<std::int64_t> column_step, std::size_t base, bool allow_negative, "
           "bool inclusive, const std::vector<std::vector<U>>& replacement) {\n"
           "  const auto rows = slice_indices(values.size(), row_start, row_stop, row_step, base, "
           "allow_negative, inclusive);\n"
           "  if (rows.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF block row count mismatch\");\n"
           "  for (std::size_t position = 0; position < rows.size(); ++position) "
           "assign_slice(values.at(rows[position]), column_start, column_stop, column_step, base, "
           "allow_negative, inclusive, replacement[position], false);\n"
           "}\n"
           "template <typename T, typename U> void assign_block("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> row_start, "
           "std::optional<std::int64_t> row_stop, std::optional<std::int64_t> row_step, "
           "std::optional<std::int64_t> column_start, std::optional<std::int64_t> column_stop, "
           "std::optional<std::int64_t> column_step, std::size_t base, bool allow_negative, "
           "bool inclusive, const U& replacement) {\n"
           "  for (const auto row : slice_indices(values.size(), row_start, row_stop, row_step, "
           "base, "
           "allow_negative, inclusive)) "
           "assign_slice(values.at(row), column_start, column_stop, column_step, base, "
           "allow_negative, inclusive, replacement, false);\n"
           "}\n"
           "template <typename T, typename U> void assign_linear_column_major("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool inclusive, const std::vector<U>& replacement) {\n"
           "  if (values.empty()) return;\n"
           "  const auto indices = slice_indices(values.size() * values.front().size(), start, "
           "stop, "
           "step, base, false, inclusive);\n"
           "  if (indices.size() != replacement.size()) "
           "throw std::invalid_argument(\"MPF linear replacement size mismatch\");\n"
           "  for (std::size_t position = 0; position < indices.size(); ++position) {\n"
           "    const auto linear = indices[position];\n"
           "    values.at(linear % values.size()).at(linear / values.size()) = "
           "static_cast<T>(replacement[position]);\n"
           "  }\n"
           "}\n"
           "template <typename T, typename U> void assign_linear_column_major("
           "std::vector<std::vector<T>>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool inclusive, const U& replacement) {\n"
           "  if (values.empty()) return;\n"
           "  for (const auto linear : slice_indices(values.size() * values.front().size(), start, "
           "stop, "
           "step, base, false, inclusive)) "
           "values.at(linear % values.size()).at(linear / values.size()) = "
           "static_cast<T>(replacement);\n"
           "}\n"
           "template <typename T> std::vector<T> column("
           "const std::vector<std::vector<T>>& values, std::int64_t position, "
           "std::size_t base, bool allow_negative) {\n"
           "  std::vector<T> result;\n"
           "  result.reserve(values.size());\n"
           "  for (const auto& row : values) result.push_back(index(row, position, base, "
           "allow_negative));\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<std::vector<T>> columns("
           "const std::vector<std::vector<T>>& values, std::optional<std::int64_t> start, "
           "std::optional<std::int64_t> stop, std::optional<std::int64_t> step, "
           "std::size_t base, bool allow_negative, bool inclusive) {\n"
           "  std::vector<std::vector<T>> result;\n"
           "  result.reserve(values.size());\n"
           "  for (const auto& row : values) "
           "result.push_back(slice(row, start, stop, step, base, allow_negative, inclusive));\n"
           "  return result;\n"
           "}\n"
           "template <typename T> std::vector<T> flatten_column_major("
           "const std::vector<std::vector<T>>& values) {\n"
           "  std::vector<T> result;\n"
           "  if (values.empty()) return result;\n"
           "  const auto columns_count = values.front().size();\n"
           "  result.reserve(values.size() * columns_count);\n"
           "  for (std::size_t column_position = 0; column_position < columns_count; "
           "++column_position)\n"
           "    for (const auto& row : values) {\n"
           "      if (row.size() != columns_count) "
           "throw std::invalid_argument(\"MPF matrix must be rectangular\");\n"
           "      result.push_back(row.at(column_position));\n"
           "    }\n"
           "  return result;\n"
           "}\n"
           "template <typename T> T& matrix_linear_index(std::vector<std::vector<T>>& values, "
           "std::int64_t position, std::size_t base) {\n"
           "  if (values.empty() || values.front().empty()) "
           "throw std::out_of_range(\"MPF index out of bounds\");\n"
           "  const auto rows = values.size();\n"
           "  const auto columns = values.front().size();\n"
           "  const auto linear = normalize_index(rows * columns, position, base, false);\n"
           "  return values.at(linear % rows).at(linear / rows);\n"
           "}\n"
           "template <typename T> const T& matrix_linear_index("
           "const std::vector<std::vector<T>>& values, std::int64_t position, std::size_t base) {\n"
           "  if (values.empty() || values.front().empty()) "
           "throw std::out_of_range(\"MPF index out of bounds\");\n"
           "  const auto rows = values.size();\n"
           "  const auto columns = values.front().size();\n"
           "  const auto linear = normalize_index(rows * columns, position, base, false);\n"
           "  return values.at(linear % rows).at(linear / rows);\n"
           "}\n"
           "template <typename T> struct scalar_type { using type = T; };\n"
           "template <typename T> struct scalar_type<std::vector<T>> { "
           "using type = typename scalar_type<T>::type; };\n"
           "template <typename T> using scalar_type_t = typename scalar_type<T>::type;\n"
           "template <typename T> T sum_value(const T& value) { return value; }\n"
           "template <typename T> scalar_type_t<std::vector<T>> "
           "sum_value(const std::vector<T>& values) {\n"
           "  scalar_type_t<std::vector<T>> total{};\n"
           "  for (const auto& value : values) total += sum_value(value);\n"
           "  return total;\n"
           "}\n"
           "template <typename T> scalar_type_t<std::vector<T>> sum(const std::vector<T>& values) "
           "{\n"
           "  return sum_value(values);\n"
           "}\n"
           "template <typename T> std::size_t numel_value(const T&) { return 1; }\n"
           "template <typename T> std::size_t numel_value(const std::vector<T>& values) {\n"
           "  std::size_t total = 0;\n"
           "  for (const auto& value : values) total += numel_value(value);\n"
           "  return total;\n"
           "}\n"
           "template <typename T> std::size_t numel(const std::vector<T>& values) {\n"
           "  return numel_value(values);\n"
           "}\n"
           "template <typename T> void append_shape(const T&, std::vector<std::size_t>&) {}\n"
           "template <typename T> void append_shape(const std::vector<T>& values, "
           "std::vector<std::size_t>& shape) {\n"
           "  shape.push_back(values.size());\n"
           "  if (!values.empty()) append_shape(values.front(), shape);\n"
           "}\n"
           "template <typename T> std::size_t length(const std::vector<T>& values) {\n"
           "  std::vector<std::size_t> shape;\n"
           "  append_shape(values, shape);\n"
           "  return shape.empty() ? 0 : *std::max_element(shape.begin(), shape.end());\n"
           "}\n"
           "template <typename T, std::size_t Rank> struct nested_vector {\n"
           "  using type = std::vector<typename nested_vector<T, Rank - 1>::type>;\n"
           "};\n"
           "template <typename T> struct nested_vector<T, 0> { using type = T; };\n"
           "template <typename T, std::size_t Rank> using nested_vector_t = "
           "typename nested_vector<T, Rank>::type;\n"
           "template <std::size_t Dimension, std::size_t Rank, typename Scalar> auto "
           "make_nested(const std::array<std::size_t, Rank>& shape) {\n"
           "  if constexpr (Dimension == Rank) {\n"
           "    return Scalar{};\n"
           "  } else {\n"
           "    auto child = make_nested<Dimension + 1, Rank, Scalar>(shape);\n"
           "    return std::vector<decltype(child)>(shape[Dimension], child);\n"
           "  }\n"
           "}\n"
           "template <typename Values> scalar_type_t<Values>& nd_at(Values& values, "
           "const std::vector<std::size_t>& coordinates, std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) {\n"
           "    return nd_at(values.at(coordinates.at(dimension)), coordinates, dimension + 1);\n"
           "  } else {\n"
           "    return values;\n"
           "  }\n"
           "}\n"
           "template <typename Values> const scalar_type_t<Values>& nd_at(const Values& values, "
           "const std::vector<std::size_t>& coordinates, std::size_t dimension = 0) {\n"
           "  if constexpr (is_vector<Values>::value) {\n"
           "    return nd_at(values.at(coordinates.at(dimension)), coordinates, dimension + 1);\n"
           "  } else {\n"
           "    return values;\n"
           "  }\n"
           "}\n"
           "template <std::size_t Rank> std::size_t shape_size("
           "const std::array<std::size_t, Rank>& shape) {\n"
           "  std::size_t result = 1;\n"
           "  for (const auto extent : shape) {\n"
           "    if (extent == 0 || result > std::numeric_limits<std::size_t>::max() / extent) "
           "throw std::length_error(\"MPF array shape exceeds size limits\");\n"
           "    result *= extent;\n"
           "  }\n"
           "  return result;\n"
           "}\n"
           "template <std::size_t Rank> std::vector<std::size_t> "
           "column_major_coordinates(std::size_t linear, "
           "const std::array<std::size_t, Rank>& shape) {\n"
           "  std::vector<std::size_t> result; result.reserve(Rank);\n"
           "  for (const auto extent : shape) { result.push_back(linear % extent); linear /= "
           "extent; }\n"
           "  return result;\n"
           "}\n"
           "template <typename Values, std::size_t SourceRank, std::size_t TargetRank> auto "
           "reshape_column_major_nd(const Values& values, "
           "const std::array<std::size_t, SourceRank>& source_shape, "
           "const std::array<std::size_t, TargetRank>& target_shape) {\n"
           "  static_assert(SourceRank > 0 && TargetRank > 0, \"MPF RESHAPE rank must be "
           "positive\");\n"
           "  const auto source_size = shape_size(source_shape);\n"
           "  if (source_size != shape_size(target_shape)) "
           "throw std::invalid_argument(\"MPF RESHAPE size mismatch\");\n"
           "  auto result = make_nested<0, TargetRank, scalar_type_t<Values>>(target_shape);\n"
           "  for (std::size_t linear = 0; linear < source_size; ++linear) {\n"
           "    nd_at(result, column_major_coordinates(linear, target_shape)) = "
           "nd_at(values, column_major_coordinates(linear, source_shape));\n"
           "  }\n"
           "  return result;\n"
           "}\n";
    if (include_python_runtime) {
      output_
          << "template <typename Left, typename Right, typename Operation> bool py_compare(\n"
             "    const Left& left, const Right& right, Operation operation) {\n"
             "  if constexpr (std::is_arithmetic<std::decay_t<Left>>::value &&\n"
             "                std::is_arithmetic<std::decay_t<Right>>::value) {\n"
             "    using Common = std::common_type_t<std::decay_t<Left>, "
             "std::decay_t<Right>>;\n"
             "    return operation(static_cast<Common>(left), static_cast<Common>(right));\n"
             "  } else {\n"
             "    return operation(left, right);\n"
             "  }\n"
             "}\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const Left& left, const Right& right);\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const std::vector<Left>& left, const std::vector<Right>& right);\n"
             "template <typename... Left, typename... Right> bool py_equal(\n"
             "    const std::tuple<Left...>& left, const std::tuple<Right...>& right);\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const Left& left, const Right& right) {\n"
             "  using LeftType = std::decay_t<Left>;\n"
             "  using RightType = std::decay_t<Right>;\n"
             "  if constexpr (std::is_arithmetic<LeftType>::value &&\n"
             "                std::is_arithmetic<RightType>::value) {\n"
             "    using Common = std::common_type_t<LeftType, RightType>;\n"
             "    return static_cast<Common>(left) == static_cast<Common>(right);\n"
             "  } else if constexpr (std::is_same<LeftType, RightType>::value) {\n"
             "    return left == right;\n"
             "  } else {\n"
             "    return false;\n"
             "  }\n"
             "}\n"
             "template <typename Left, typename Right> bool py_equal(\n"
             "    const std::vector<Left>& left, const std::vector<Right>& right) {\n"
             "  if (left.size() != right.size()) return false;\n"
             "  for (std::size_t index = 0; index < left.size(); ++index) {\n"
             "    if constexpr (std::is_same<Left, bool>::value || "
             "std::is_same<Right, bool>::value) {\n"
             "      if (!py_equal(static_cast<Left>(left[index]), "
             "static_cast<Right>(right[index]))) return false;\n"
             "    } else if (!py_equal(left[index], right[index])) {\n"
             "      return false;\n"
             "    }\n"
             "  }\n"
             "  return true;\n"
             "}\n"
             "template <typename LeftTuple, typename RightTuple, std::size_t... Index>\n"
             "bool py_tuple_equal(const LeftTuple& left, const RightTuple& right,\n"
             "                    std::index_sequence<Index...>) {\n"
             "  return (true && ... && py_equal(std::get<Index>(left), "
             "std::get<Index>(right)));\n"
             "}\n"
             "template <typename... Left, typename... Right> bool py_equal(\n"
             "    const std::tuple<Left...>& left, const std::tuple<Right...>& right) {\n"
             "  if constexpr (sizeof...(Left) != sizeof...(Right)) {\n"
             "    return false;\n"
             "  } else {\n"
             "    return py_tuple_equal(left, right, std::index_sequence_for<Left...>{});\n"
             "  }\n"
             "}\n"
             "template <typename Left, typename Right> bool py_is(\n"
             "    const Left& left, const Right& right) {\n"
             "  using LeftType = std::decay_t<Left>;\n"
             "  using RightType = std::decay_t<Right>;\n"
             "  if constexpr (std::is_same<LeftType, std::nullptr_t>::value &&\n"
             "                std::is_same<RightType, std::nullptr_t>::value) {\n"
             "    return true;\n"
             "  } else if constexpr (std::is_same<LeftType, bool>::value &&\n"
             "                       std::is_same<RightType, bool>::value) {\n"
             "    return left == right;\n"
             "  } else {\n"
             "    return false;\n"
             "  }\n"
             "}\n"
             "inline bool py_contains(const std::string& container, const std::string& value) {\n"
             "  return container.find(value) != std::string::npos;\n"
             "}\n"
             "template <typename T, typename Value> bool py_contains(\n"
             "    const std::vector<T>& container, const Value& value) {\n"
             "  return std::any_of(container.begin(), container.end(),\n"
             "                     [&](const auto& element) { return py_equal(element, value); "
             "});\n"
             "}\n"
             "template <typename... T, typename Value> bool py_contains(\n"
             "    const std::tuple<T...>& container, const Value& value) {\n"
             "  return std::apply([&](const auto&... element) {\n"
             "    return (false || ... || py_equal(element, value));\n"
             "  }, container);\n"
             "}\n"
             "inline bool truthy(std::nullptr_t) { return false; }\n"
             "inline bool truthy(bool value) { return value; }\n"
             "template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>> "
             "bool truthy(T value) { return value != static_cast<T>(0); }\n"
             "inline bool truthy(const std::string& value) { return !value.empty(); }\n"
             "template <typename T> bool truthy(const std::vector<T>& value) { return "
             "!value.empty(); }\n"
             "template <typename... T> bool truthy(const std::tuple<T...>&) { return sizeof...(T) "
             "!= 0; }\n"
             "template <typename T> bool py_not(const T& value) { return !truthy(value); }\n"
             "template <typename LeftFunction, typename RightFunction> auto py_and("
             "LeftFunction&& left_function, RightFunction&& right_function) {\n"
             "  auto left = left_function();\n"
             "  using Result = std::common_type_t<std::decay_t<decltype(left)>, "
             "std::decay_t<decltype(right_function())>>;\n"
             "  if (!truthy(left)) return static_cast<Result>(left);\n"
             "  return static_cast<Result>(right_function());\n"
             "}\n"
             "template <typename LeftFunction, typename RightFunction> auto py_or("
             "LeftFunction&& left_function, RightFunction&& right_function) {\n"
             "  auto left = left_function();\n"
             "  using Result = std::common_type_t<std::decay_t<decltype(left)>, "
             "std::decay_t<decltype(right_function())>>;\n"
             "  if (truthy(left)) return static_cast<Result>(left);\n"
             "  return static_cast<Result>(right_function());\n"
             "}\n"
             "template <typename T, typename = std::enable_if_t<std::is_arithmetic<T>::value>> "
             "double py_float(T value) { return static_cast<double>(value); }\n"
             "inline double py_float(const std::string& value) {\n"
             "  std::size_t consumed = 0;\n"
             "  const auto result = std::stod(value, &consumed);\n"
             "  if (value.find_first_not_of(\" \\t\\n\\r\\f\\v\", consumed) != std::string::npos) "
             "throw std::invalid_argument(\"MPF float string is invalid\");\n"
             "  return result;\n"
             "}\n";
    }
    output_ << "}  // namespace " << runtime_namespace << "\n\n";
  }

 private:
  std::ostream& output_;
};

}  // namespace

void emit_cpp_runtime(std::ostream& output, const std::string_view runtime_namespace,
                      const std::vector<cpp::lir::RuntimeFragment>& fragments) {
  RuntimeEmitter(output).emit(runtime_namespace, fragments);
}

}  // namespace mpf::detail
