A = sparse([1+2i 0; 0 3-4i]);
B = sparse([1 1 2], [1 2 2], [-1+1i 2-3i 5+4i], 2, 2);
R = sparse([2 0; 4 -1]);
L = sparse([true false; false true]);
row = sparse([1 1], [1 2], [1+1i 2-2i], 1, 2);
column = sparse([1 2], [1 1], [3 4], 2, 1);

sparse_sum = A + B;
sparse_difference = A - B;
mixed_sparse = A + R;
mixed_logical = A + L;
mixed_dense = A + [10 20; 30 40];
dense_left = [10 20; 30 40] - A;
right_scalar = A + (2-1i);
left_scalar = (2-1i) - A;
broadcast = row + column;
cancellation = A - A;
complex_empty = A([], :);
empty_sum = complex_empty + complex_empty;

sum_full = full(sparse_sum);
difference_full = full(sparse_difference);
mixed_sparse_full = full(mixed_sparse);
mixed_logical_full = full(mixed_logical);
broadcast_full = full(broadcast);

disp(real(sum_full(1,1)), imag(sum_full(1,1)), ...
     real(sum_full(1,2)), imag(sum_full(1,2)), ...
     real(sum_full(2,2)), imag(sum_full(2,2)), ...
     real(difference_full(1,1)), imag(difference_full(1,1)), ...
     real(difference_full(1,2)), imag(difference_full(1,2)), ...
     real(difference_full(2,2)), imag(difference_full(2,2)), ...
     real(mixed_sparse_full(1,1)), imag(mixed_sparse_full(1,1)), ...
     real(mixed_sparse_full(2,1)), imag(mixed_sparse_full(2,1)), ...
     real(mixed_sparse_full(2,2)), imag(mixed_sparse_full(2,2)), ...
     real(mixed_logical_full(1,1)), imag(mixed_logical_full(1,1)), ...
     real(mixed_logical_full(2,2)), imag(mixed_logical_full(2,2)), ...
     real(mixed_dense(1,1)), imag(mixed_dense(1,1)), ...
     real(mixed_dense(2,2)), imag(mixed_dense(2,2)), ...
     real(dense_left(1,1)), imag(dense_left(1,1)), ...
     real(dense_left(2,2)), imag(dense_left(2,2)), ...
     real(right_scalar(1,1)), imag(right_scalar(1,1)), ...
     real(right_scalar(2,2)), imag(right_scalar(2,2)), ...
     real(left_scalar(1,1)), imag(left_scalar(1,1)), ...
     real(left_scalar(2,2)), imag(left_scalar(2,2)), ...
     real(broadcast_full(1,1)), imag(broadcast_full(1,1)), ...
     real(broadcast_full(2,2)), imag(broadcast_full(2,2)), ...
     nnz(sparse_sum), nnz(mixed_sparse), nnz(broadcast), nnz(cancellation), ...
     0 + issparse(sparse_sum), 0 + issparse(mixed_sparse), ...
     0 + issparse(mixed_dense), 0 + issparse(right_scalar), ...
     0 + issparse(broadcast), 0 + issparse(cancellation), ...
     0 + issparse(empty_sum), nnz(empty_sum))
