coefficient = [0 1+1i; 2-1i 3];
right_hand_side = [-4-2i -2+4i; -5+6i 6+5i];

solution = coefficient \ right_hand_side;
right_solution = [-5+5i -10+6i] / coefficient;

disp(real(solution(1,1)), imag(solution(1,1)), ...
     real(solution(2,1)), imag(solution(2,1)), ...
     real(solution(1,2)), imag(solution(1,2)), ...
     real(solution(2,2)), imag(solution(2,2)), ...
     real(right_solution(1)), imag(right_solution(1)), ...
     real(right_solution(2)), imag(right_solution(2)))
