hermitian = [4 2i; -2i 5];

product = hermitian * hermitian;
hermitian_solution = hermitian \ [6+8i; 12-7i];

dense = [1i 0; 0 -1i];
dense_solution = dense \ [-1+1i; -1-2i];
right_solution = [2 8-3i] / hermitian;

powered = hermitian ^ 2;
inverse = hermitian ^ -1;

disp(real(product(1,1)), imag(product(1,2)), ...
     real(hermitian_solution(1)), imag(hermitian_solution(1)), ...
     real(hermitian_solution(2)), imag(hermitian_solution(2)), ...
     real(dense_solution(1)), imag(dense_solution(1)), ...
     real(dense_solution(2)), imag(dense_solution(2)), ...
     real(right_solution(1)), imag(right_solution(1)), ...
     real(right_solution(2)), imag(right_solution(2)), ...
     real(powered(2,2)), imag(powered(1,2)), ...
     real(inverse(1,1)) * 16, imag(inverse(1,2)) * 8, ...
     imag(inverse(2,1)) * 8, real(inverse(2,2)) * 4)
