A = sparse([1+2i 0 2-1i; 0 3i -1]);
B = sparse([0 4-1i; 5+2i 0; -2 1+3i]);
R = sparse([1 0 2; 0 3 -1]);
Q = sparse([0 4; 5 0; -2 1]);

complex_product = A * B;
complex_real_product = A * Q;
real_complex_product = R * B;
sparse_dense_product = A * full(B);
dense_sparse_product = full(A) * B;

cancel_left = sparse([1 1], [1 2], [1 1i], 1, 2);
cancel_right = sparse([1 2], [1 1], [1 1i], 2, 1);
cancelled = cancel_left * cancel_right;
outer_empty = A([], :) * B;
inner_empty = A(:, []) * B([], :);

complex_full = full(complex_product);
complex_real_full = full(complex_real_product);
real_complex_full = full(real_complex_product);
inner_full = full(inner_empty);

disp(real(complex_full(1,1)), imag(complex_full(1,1)), ...
     real(complex_full(1,2)), imag(complex_full(1,2)), ...
     real(complex_full(2,1)), imag(complex_full(2,1)), ...
     real(complex_full(2,2)), imag(complex_full(2,2)), ...
     real(complex_real_full(1,2)), imag(complex_real_full(1,2)), ...
     real(complex_real_full(2,1)), imag(complex_real_full(2,1)), ...
     real(real_complex_full(1,2)), imag(real_complex_full(1,2)), ...
     real(real_complex_full(2,1)), imag(real_complex_full(2,1)), ...
     real(sparse_dense_product(1,2)), imag(sparse_dense_product(1,2)), ...
     real(dense_sparse_product(2,1)), imag(dense_sparse_product(2,1)), ...
     real(inner_full(1,1)), imag(inner_full(1,1)), ...
     nnz(complex_product), nnz(complex_real_product), nnz(real_complex_product), ...
     nnz(cancelled), nnz(outer_empty), nnz(inner_empty), ...
     0 + issparse(complex_product), 0 + issparse(complex_real_product), ...
     0 + issparse(real_complex_product), 0 + issparse(sparse_dense_product), ...
     0 + issparse(dense_sparse_product), 0 + issparse(cancelled), ...
     0 + issparse(outer_empty), 0 + issparse(inner_empty))
