overdetermined_coefficient = [1+1i 2-1i; 2 -1+1i; 1-1i 1+2i];
expected_overdetermined = [2+1i -1+2i; 3-1i 4+1i];
overdetermined_rhs = overdetermined_coefficient * expected_overdetermined;
overdetermined = overdetermined_coefficient \ overdetermined_rhs;

underdetermined_coefficient = [1+1i 0 0; 0 1-1i 0];
expected_underdetermined = [2+1i; 3-1i; 0];
underdetermined_rhs = underdetermined_coefficient * expected_underdetermined;
underdetermined = underdetermined_coefficient \ underdetermined_rhs;

right_overdetermined = [1+3i 2-4i 0] / underdetermined_coefficient;
right_underdetermined = [7+1i 3+4i] / overdetermined_coefficient;

disp(round(real(overdetermined(1, 1))), round(imag(overdetermined(1, 1))), ...
     round(real(overdetermined(1, 2))), round(imag(overdetermined(1, 2))), ...
     round(real(overdetermined(2, 1))), round(imag(overdetermined(2, 1))), ...
     round(real(overdetermined(2, 2))), round(imag(overdetermined(2, 2))), ...
     round(real(underdetermined(1))), round(imag(underdetermined(1))), ...
     round(real(underdetermined(2))), round(imag(underdetermined(2))), ...
     round(abs(underdetermined(3))), ...
     round(real(right_overdetermined(1))), round(imag(right_overdetermined(1))), ...
     round(real(right_overdetermined(2))), round(imag(right_overdetermined(2))), ...
     round(real(right_underdetermined(1))), round(imag(right_underdetermined(1))), ...
     round(real(right_underdetermined(2))), round(imag(right_underdetermined(2))), ...
     round(abs(right_underdetermined(3))))
