overdetermined = [1 0; 0 1; 1 1] \ [1; 2; 4];
underdetermined = [1 0 1; 0 1 1] \ [2; 3];
wide_right_division = [2 3 0] / [1 0 0; 0 1 0];
tall_right_division = [1 2] / [1 0; 0 1; 1 1];

disp(round(3 * overdetermined(1)), round(3 * overdetermined(2)), ...
     round(3 * underdetermined(1)), round(3 * underdetermined(2)), ...
     round(3 * underdetermined(3)), ...
     round(wide_right_division(1)), round(wide_right_division(2)), ...
     round(tall_right_division(2)), round(tall_right_division(3)))
