A = sparse([1 0; 0 2]);
B = sparse([0 3; 4 -2]);
D = [5 6; 7 8];
row = sparse([1 1], [1 2], [10 20], 1, 2);
column = sparse([1 2], [1 1], [5 6], 2, 1);

sparse_sum = A + B;
sparse_difference = A - B;
sparse_dense = A + D;
dense_sparse = D - A;
right_scalar = A + 10;
left_scalar = 10 - A;
row_broadcast = row + B;
outer_broadcast = row + column;
logical_sum = sparse([true false; false true]) + ...
              sparse([false true; true false]);
cancellation = A - A;
empty_sparse = sparse(0, 2) + sparse(0, 2);
empty_dense = sparse(0, 2) + reshape([], 0, 2);

sparse_sum_full = full(sparse_sum);
sparse_difference_full = full(sparse_difference);
logical_sum_full = full(logical_sum);
row_broadcast_full = full(row_broadcast);
outer_broadcast_full = full(outer_broadcast);

disp(sparse_sum_full(1,1), sparse_sum_full(1,2), sparse_sum_full(2,1), ...
     sparse_sum_full(2,2), sparse_difference_full(1,2), ...
     sparse_difference_full(2,1), sparse_difference_full(2,2), ...
     sparse_dense(1,1), sparse_dense(2,2), dense_sparse(1,1), dense_sparse(2,2), ...
     right_scalar(1,1), right_scalar(2,2), left_scalar(1,1), left_scalar(2,2), ...
     row_broadcast_full(2,1), row_broadcast_full(2,2), ...
     outer_broadcast_full(1,1), outer_broadcast_full(2,2), ...
     logical_sum_full(1,1), logical_sum_full(2,2), nnz(cancellation), ...
     issparse(sparse_sum) + 0, issparse(sparse_dense) + 0, ...
     issparse(right_scalar) + 0, issparse(row_broadcast) + 0, ...
     issparse(logical_sum) + 0, issparse(empty_sparse) + 0, ...
     issparse(empty_dense) + 0, nnz(empty_sparse))
