A = sparse([1 0 2; 0 3 0; 4 0 5]);

linear_scalar = A(5);
subscript_scalar = A(3, 1);
linear = full(A([9 1; 5 7]));
sliced = full(A(1:2:9));
logical_linear = full(A([true false true false true false true false true]));
mask = [true false true false true false true false true];
dynamic_logical = A(mask);
dynamic_logical_dense = full(dynamic_logical);
selected_rows = full(A([true false true], :));
repeated = full(A([3 1 3], [3 1 3]));
reversed = full(A(3:-1:1, 3:-1:1));
empty_linear = A([]);
empty_block = A([], [1 3]);
empty_block_dense = full(empty_block);
column = full(A(:));

row = sparse(reshape([1 0 2], 1, 3));
row_selected = full(row([3 1]));
row_matrix_selected = full(row([3 1; 1 3]));
column_vector = sparse(reshape([1 0 2], 3, 1));
column_selected = full(column_vector([3 1]));

disp(linear_scalar, subscript_scalar, ...
     linear(1, 1), linear(2, 1), linear(1, 2), linear(2, 2), ...
     sliced(1), sliced(2), sliced(3), sliced(4), sliced(5), ...
     logical_linear(1), logical_linear(2), logical_linear(3), ...
     logical_linear(4), logical_linear(5), ...
     nnz(dynamic_logical), dynamic_logical_dense(5), ...
     selected_rows(1, 1), selected_rows(2, 1), ...
     selected_rows(1, 3), selected_rows(2, 3), ...
     repeated(1, 1), repeated(2, 2), repeated(3, 3), ...
     reversed(1, 1), reversed(3, 3), ...
     nnz(empty_linear), nnz(empty_block), length(empty_block_dense), column(1), column(9), ...
     row_selected(1, 1), row_selected(1, 2), ...
     row_matrix_selected(1, 1), row_matrix_selected(2, 1), ...
     row_matrix_selected(1, 2), row_matrix_selected(2, 2), ...
     column_selected(1, 1), column_selected(2, 1), ...
     0 + issparse(empty_linear), 0 + issparse(empty_block))
