numeric = sparse([1 0 3; 0 0 4; 5 0 0]);
logical_values = sparse([true false; true true]);

by_column_any = any(numeric);
by_column_all = all(logical_values);
by_row_any = any(numeric, 2);
by_row_all = all(logical_values, 2);
total_any = any(numeric, 'all');
total_all = all(logical_values, 'all');

zero_rows = sparse([], [], [], 0, 3);
zero_columns = sparse([], [], [], 3, 0);
empty = sparse([], [], [], 0, 0);
zero_rows_all = all(zero_rows);
zero_rows_any = any(zero_rows);
zero_columns_all = all(zero_columns, 2);
zero_columns_any = any(zero_columns, 2);
empty_all = all(empty);
empty_any = any(empty);

unchanged = any(numeric, 3);
dense_column_any = full(by_column_any);
dense_column_all = full(by_column_all);
dense_row_any = full(by_row_any);
dense_row_all = full(by_row_all);
dense_zero_rows_all = full(zero_rows_all);
dense_zero_columns_all = full(zero_columns_all);
dense_unchanged = full(unchanged);

disp(nnz(by_column_any), nnz(by_column_all), nnz(by_row_any), nnz(by_row_all), ...
     0 + total_any, 0 + total_all, nnz(zero_rows_all), nnz(zero_rows_any), ...
     nnz(zero_columns_all), nnz(zero_columns_any), 0 + empty_all, 0 + empty_any, ...
     nnz(unchanged), 0 + issparse(by_column_any), 0 + issparse(by_column_all), ...
     0 + issparse(by_row_any), 0 + issparse(by_row_all), ...
     0 + issparse(zero_rows_all), 0 + issparse(zero_rows_any), ...
     0 + issparse(zero_columns_all), 0 + issparse(zero_columns_any), ...
     0 + issparse(unchanged), 0 + dense_column_any(1, 1), ...
     0 + dense_column_any(1, 2), 0 + dense_column_any(1, 3), ...
     0 + dense_column_all(1, 1), 0 + dense_column_all(1, 2), ...
     0 + dense_row_any(1, 1), 0 + dense_row_any(2, 1), ...
     0 + dense_row_any(3, 1), 0 + dense_row_all(1, 1), ...
     0 + dense_row_all(2, 1), 0 + dense_zero_rows_all(1, 1), ...
     0 + dense_zero_rows_all(1, 3), 0 + dense_zero_columns_all(1, 1), ...
     0 + dense_zero_columns_all(3, 1), 0 + dense_unchanged(1, 1), ...
     0 + dense_unchanged(2, 1), 0 + dense_unchanged(2, 3))
