cmake_minimum_required(VERSION 3.20)

foreach(required SOURCE_DIR CORPUS_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "prepare_corpus.cmake requires ${required}")
  endif()
endforeach()

file(REAL_PATH "${SOURCE_DIR}" source_root)
if(NOT IS_DIRECTORY "${source_root}/build")
  message(FATAL_ERROR "Configure a build beneath the project's root build/ before preparing seeds")
endif()
file(REAL_PATH "${source_root}/build" build_root)
cmake_path(ABSOLUTE_PATH CORPUS_DIR NORMALIZE OUTPUT_VARIABLE requested_root)
set(existing_parent "${requested_root}")
set(missing_suffix "")
while(NOT EXISTS "${existing_parent}")
  cmake_path(GET existing_parent FILENAME component)
  cmake_path(GET existing_parent PARENT_PATH parent)
  if(parent STREQUAL existing_parent)
    message(FATAL_ERROR "Cannot resolve fuzz corpus output path")
  endif()
  set(missing_suffix "${component}/${missing_suffix}")
  set(existing_parent "${parent}")
endwhile()
file(REAL_PATH "${existing_parent}" resolved_parent)
cmake_path(APPEND resolved_parent "${missing_suffix}" OUTPUT_VARIABLE corpus_root)
cmake_path(NORMAL_PATH corpus_root)
cmake_path(IS_PREFIX build_root "${corpus_root}" NORMALIZE under_build)
if(NOT under_build OR corpus_root STREQUAL build_root)
  message(FATAL_ERROR "Fuzz corpus output must be a directory beneath the project's root build/")
endif()

set(language_code 4)
set(prepared 0)
foreach(language python matlab fortran typescript)
  set(seed_root "${source_root}/tests/fuzz/corpus/${language}")
  file(GLOB_RECURSE seeds LIST_DIRECTORIES false RELATIVE "${seed_root}" "${seed_root}/*")
  foreach(seed IN LISTS seeds)
    file(READ "${seed_root}/${seed}" payload)
    set(target_code 2)
    foreach(target javascript cpp)
      string(ASCII ${language_code} ${target_code} prefix)
      set(output "${corpus_root}/${language}/${target}/${seed}")
      cmake_path(GET output PARENT_PATH parent)
      file(MAKE_DIRECTORY "${parent}")
      file(WRITE "${output}" "${prefix}${payload}")
      math(EXPR target_code "${target_code} + 1")
      math(EXPR prepared "${prepared} + 1")
    endforeach()
  endforeach()
  math(EXPR language_code "${language_code} + 1")
endforeach()
if(prepared EQUAL 0)
  message(FATAL_ERROR "No source seeds were found")
endif()
message(STATUS "Prepared ${prepared} language/target-framed fuzz seeds under ${corpus_root}")
